### ISSUE TITLE
CORE_SYMBOL in ./build.sh

### ISSUE THREAD

**Issue by qpIlIpp** [EOSIO/eosio.cdt#103]
Didn't find it in readme.md.

What should I use as <CORE_SYMBOL> parameter for "build.sh" ? 

Should be "EOS" or "SYS" ?
Or according to "core_symbol.hpp" "S(4,SYS)"?
Or it uint64_t equivalent 1398362884 ?
Or nothing / doesn't matter?

Thank you.

**Comment by dskvr** [comment]
It should be the core symbol for whichever network you are compiling contracts for. The tutorials are network agnostic, so "SYS" is used.

**Comment by qpIlIpp** [comment]
Thank you! IMHO, it should be in "readme".
