### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by tymekm** [EOSIO/eosio.cdt#1059]
The compilation fails for me on archlinux with:
gcc 10.2.0
llvm 11.1.0
cmake 3.19.6
boost 1.75.0

[ 17%] Building CXX object external/wabt/CMakeFiles/libwabt.dir/src/wast-parser-lexer-shared.cc.o
In file included from /usr/include/stdlib.h:568,
                 from /usr/include/c++/10.2.0/cstdlib:75,
                 from /usr/include/c++/10.2.0/bits/stl_algo.h:59,
                 from /usr/include/c++/10.2.0/algorithm:62,
                 from /home/tymek/eosio/eosio.cdt/tools/external/wabt/src/common.h:20,
                 from /home/tymek/eosio/eosio.cdt/tools/external/wabt/src/wast-parser-lexer-shared.cc:19:
/home/tymek/eosio/eosio.cdt/tools/external/wabt/src/wast-parser-lexer-shared.cc: In function ‘void wabt::WastFormatError(wabt::ErrorHandler*, const wabt::Location*, wabt::WastLexer*, const char*, __va_list_tag*)’:
/home/tymek/eosio/eosio.cdt/tools/external/wabt/src/wast-parser-lexer-shared.cc:36:33: error: argument to ‘alloca’ may be too large [-Werror=alloca-larger-than=]
   36 |     buffer = static_cast<char*>(alloca(len + 1));
      |                                 ^~~~~~
cc1plus: all warnings being treated as errors
make[5]: *** [external/wabt/CMakeFiles/libwabt.dir/build.make:193: external/wabt/CMakeFiles/libwabt.dir/src/wast-parser-lexer-shared.cc.o] Error 1
make[5]: Leaving directory '/home/tymek/eosio/eosio.cdt/build/tools'
make[4]: *** [CMakeFiles/Makefile2:838: external/wabt/CMakeFiles/libwabt.dir/all] Error 2
make[4]: Leaving directory '/home/tymek/eosio/eosio.cdt/build/tools'
make[3]: *** [Makefile:84: all] Error 2
make[3]: Leaving directory '/home/tymek/eosio/eosio.cdt/build/tools'
make[2]: *** [CMakeFiles/EosioTools.dir/build.make:113: EosioTools-prefix/src/EosioTools-stamp/EosioTools-build] Error 2
make[2]: Leaving directory '/home/tymek/eosio/eosio.cdt/build'
make[1]: *** [CMakeFiles/Makefile2:526: CMakeFiles/EosioTools.dir/all] Error 2
make[1]: Leaving directory '/home/tymek/eosio/eosio.cdt/build'
make: *** [Makefile:141: all] Error 2

**Comment by aclark-b1** [comment]
Technically ArchLinux isn't one of our supported OS options, but you may want to try using Clang 8 or 9 and see if that helps.
