### ISSUE TITLE
Visual Studio Code cannot locate "eosio.hpp" while trying to run "Hello World"

### ISSUE THREAD

**Issue by wfalcon3** [EOSIO/eosio.cdt#1060]
Hi, I am running this on Ubuntu 20.04. I know I installed the CDT 1.7 and I did all the other steps in the EOSIO guide successfully. Now, when I try to run the "Hello World" program, I get an error when trying to #include <eoslib/eosio.hpp>

How do I get the header file to be properly recognized? I have never had this issue before when developing with C++ for other applications.

![Screenshot from 2021-03-01 20-57-46](https://user-images.githubusercontent.com/49729674/109585086-ce6d7c00-7ad0-11eb-917f-45ea81de9fc8.png)

**Comment by aclark-b1** [comment]
Hi @wfalcon3,

I'm not sure if we can provide much help without more information about how your environment is configured, but you may want to try adding include paths via VSCode's settings json C_Cpp.default.includePath'.  From here you can point it to where your version is installed.
