### ISSUE TITLE
Struct not being added to generated ABI

### ISSUE THREAD

**Issue by znebby** [EOSIO/eosio.cdt#108]
I have a simple struct in my code:

struct vector3 {
    float x;
    float y;
    float z;
};

It is used as a type in my action arguments. In the ABI, the implicit action struct lists fields with a type of "vector3", however, the vector3 struct itself is not listed in the structs in the ABI.

If I add the [[eosio::table]] attribute to it, it does go in the ABI. But this struct is not a table, just a type.

Am I meant to use [[eosio::table]] on all structs required by the ABI, not just those that are tables?

Or is this a bug?

**Comment by lonkly** [comment]
Same issue here, we need more clarification on when to use [[eosio::table]]

**Comment by dskvr** [comment]
`[[eosio::table]]` should only be for when **a struct used to configure a multi_index table** is being defined. 

Having this struct go into the ABI in the way is of no benefit. [Please Read](https://developers.eos.io/eosio-home/docs/the-abi#section-introduction)

**Comment by lonkly** [comment]
If I do not set [[eosio::table]] on struct, it's type does not get into the abi and I am not able to send parameters in a cozy way. Also, [[eosio::abi]] does not work at all (in multiindex example it's used on a function)

**Comment by znebby** [comment]
This does not add the struct to the tables in the ABI but it adds it to the structs part of the ABI.

Otherwise it does not get added to the ABI at all, but it should be needed there, no?

**Comment by larryk85** [comment]
We are releasing 1.3 today that should resolve this.  But to clarify when to use the `table` attribute.  You should put in on any table structs that you want to be reflected in the abi as a table.  The way it handles whats in the abi is if you have any multi_index typedefs that reference this table those will go in the abi, if no multi_index typedefs use that table then it uses the name you give it or the C++ table name if no explicit name is given to the attribute (this is if you want to handle everything yourself and call the db intrinsics manually).
