### ISSUE TITLE
eosio.wasmsdk error

### ISSUE THREAD

**Issue by jonericcook** [EOSIO/eosio.cdt#110]
I am trying to use the following C++ JSON library:

https://github.com/nlohmann/json

Below is the code I am trying to compile with `eosio-cpp gda.cpp -o gda.wasm`
```
#include <eosiolib/eosio.hpp>
#include <nlohmann/json.hpp>
#include <string>

using json = nlohmann::json;

class gda : public eosio::contract {
    public:
        explicit gda(action_name self) : contract(self) {}

        // @abi action
        void doit(const std::string action) {
            json j = {
                {"pi", 3.141},
                {"happy", true},
                {"name", "Niels"},
                {"nothing", nullptr},
                {"answer", {
                    {"everything", 42}
                }},
                {"list", {1, 0, 2}},
                {"object", {
                    {"currency", "USD"},
                    {"value", 42.99}
                }}
            };
            std::string d = j.dump();
        }
};

EOSIO_ABI( gda, (doit) )
```
Below is the output from trying to compile:
```
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: locale.cpp.o: undefined symbol: strftime_l
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: memory.cpp.o: undefined symbol: __cxa_pure_virtual
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: system_error.cpp.o: undefined symbol: __cxa_pure_virtual
If the j.dump() line is commented out, the contract will compile.
```
A similar issue has been raised on stackoverflow.

https://stackoverflow.com/questions/52350514/linking-issue-with-eosio-ld

I was directed here from: https://github.com/EOSIO/eos/issues/5832

**Comment by cppfuns** [comment]
Encounter the same problem, look forward to the solution

**Comment by jonericcook** [comment]
@larryk85 

When I use eosiocpp, the above code will compile.

**Comment by cppfuns** [comment]
> @larryk85
> 
> When I use `eosiocpp`, the above code will compile.

Is it working fine when executing a doit contract? I have an error when I have parse and dump in the contract.

**Comment by jonericcook** [comment]
similar to #141

**Comment by jonericcook** [comment]
> Is it working fine when executing a doit contract? I have an error when I have parse and dump in the contract.

with eoisocpp it would compile (its an old tool so doesnt have that much weight) but it would fail when i would try and execute the action

**Comment by Machine-Hum** [comment]
Does anyone have a fix for this? Using eoscpp isn't a fix as it's deprecated. My specific error is...

'''/usr/local/eosio.cdt/bin/wasm-ld: error: undefined symbol: apply

**Comment by jonericcook** [comment]
with the newest release of eosio.cdt and eosio i am able to use to the above code

please try using the most up to date versions of each and let me know

**Comment by lpx1988** [comment]
> with the newest release of eosio.cdt and eosio i am able to use to the above code
> 
> please try using the most up to date versions of each and let me know

I always used this C++ JSON library(with eosio.cdt-1.5.1 and eosio-1.6.1),
with eoiso-cpp it would compile but it would fail when i would try and execute the action.
why?@jonericcook

**Comment by jonericcook** [comment]
Try this

eosio-cpp —abigen gda.cpp -o gda.wasm

**Comment by lpx1988** [comment]
> Try this
> 
> eosio-cpp —abigen gda.cpp -o gda.wasm

yes, it would compile but it would fail when i would try and execute the action(eg: json::parse and json::dump ). 
the error is "3070002 wasm_execution_error: Runtime Error Processing WASM
wabt execution failure (out of bounds memory access)"

**Comment by lpx1988** [comment]
> Try this
> 
> eosio-cpp —abigen gda.cpp -o gda.wasm

and when i used json::parse,my specific error is 
"3070002 wasm_execution_error: Runtime Error Processing WASM
wabt execution failure (out of bounds memory access)"

**Comment by jonericcook** [comment]
Try this:
Note: I downloaded `json.hpp` from https://github.com/nlohmann/json/releases and put it in the same directory as `demo.hpp`.

`demo.hpp`
```
#pragma once

#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
#include "json.hpp"
#include <string>

using json = nlohmann::json;
using eosio::contract;
using eosio::multi_index;
using eosio::print;

class[[eosio::contract]] demo : public contract
{
  public:
    using contract::contract;

    [[eosio::action]] void demoaction();
};
```

`demo.cpp`
```
#include "demo.hpp"
using json = nlohmann::json;

// ACTION
void demo::demoaction()
{
    json demoInfo = R"(
    {
        "demoInfo": {
            "hello": "world"
        }
    }
    )"_json;
    std::string demoInfoString = demoInfo.dump();
    json demoInfoJson = json::parse(demoInfoString);
    print("It worked\n");
}

EOSIO_DISPATCH(demo, (demoaction))
```

**Comment by lpx1988** [comment]
Thank you @jonericcook
