### ISSUE TITLE
Import contract into CLion, got error

### ISSUE THREAD

**Issue by gs201510** [EOSIO/eosio.cdt#113]
trying import the example/hello contract into CLion, got this error, how should I do?
`/usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /data/soft/eos/hello
-- Setting up Eosio Wasm Toolchain
-- Configuring done
-- Generating done
-- Build files have been written to: /data/soft/eos/hello/cmake-build-debug

Cannot get compiler information:
	Compiler exited with error code 255: /usr/local/eosio.cdt/bin/eosio-cpp -xc++ -O3 -I/home/gs/opt/boost/include -g -fpch-preprocess -v -dD -E
	clang version 7.0.0 (https://github.com/eosio/clang.git 0f0efd6a05ee928dfa1b505c55c0d90ae188488e) (https://github.com/eosio/llvm 31e1613c474cab51a80ac898ec31716273df3729)
	Target: wasm32
	Thread model: single
	InstalledDir: /usr/local/eosio.cdt/bin
	clang-7: warning: /tmp/compiler-file: 'linker' input unused [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-ffreestanding' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-fno-builtin' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-fno-threadsafe-statics' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-D BOOST_DISABLE_ASSERTS' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-D BOOST_EXCEPTION_DISABLE' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-Xclang -load' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-Xclang /usr/local/eosio.cdt/bin/LLVMEosioApply.so' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-mllvm -use-cfl-aa-in-codegen=both' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-I /usr/local/eosio.cdt/bin/../include/libcxx' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-I /usr/local/eosio.cdt/bin/../include/libc' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-I /usr/local/eosio.cdt/bin/../include' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-I /home/gs/opt/boost/include' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-c' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-dD' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-D ___CIDR_DEFINITIONS_END' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-I /home/gs/opt/boost/include' [-Wunused-command-line-argument]
	clang-7: warning: argument unused during compilation: '-O3' [-Wunused-command-line-argument]
	
	

[Finished]`

**Comment by qimiaoguo** [comment]
can anybody help?

**Comment by larryk85** [comment]
We don't currently support `CLion` or any IDE.  Possibly in the future we can focus on making this a better priority.

**Comment by gelldur** [comment]
Even with this issue in Clion you should be able to use & build (At least I can ;))

**Comment by philipp-sorin** [comment]
@gelldur which version do you use?

**Comment by gelldur** [comment]
@philipp-sorin current 2019.03 I build with success on docker. (Remote Toolchain)
