### ISSUE TITLE
Unknown command line argument '-mmacosx-version-min=10.13'

### ISSUE THREAD

**Issue by Kanfudza** [EOSIO/eosio.cdt#115]
Failed to build in macOS(v 10.13.6)
`[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o
eosio-cceosio-cceosio-cc: Unknown command line argument ': Unknown command line argument '-mmacosx-version-min=10.13-mmacosx-version-min=10.13'.  Try: ''.  Try: '/Users/kanf/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc/Users/kanf/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc -help'
 -help'
eosio-cceosio-cc: Did you mean '-: Did you mean '-fcoroutine-ts=10.13fcoroutine-ts=10.13'?
'?
eosio-cc: Unknown command line argument '-mmacosx-version-min=10.13'.  Try: '/Users/kanf/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc -help'
eosio-cc: Did you mean '-fcoroutine-ts=10.13'?
: Unknown command line argument '-mmacosx-version-min=10.13'.  Try: '/Users/kanf/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc -help'
eosio-cc: Did you mean '-fcoroutine-ts=10.13'?
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_des.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_blowfish.c.o] Error 1
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o] Error 1
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o] Error 1
make[1]: *** [libraries/libc/CMakeFiles/c.dir/all] Error 2
make: *** [all] Error 2

**Comment by bestseob93** [comment]
+1

**Comment by lovecactus** [comment]
+1

**Comment by jchaager** [comment]
+1

**Comment by jchaager** [comment]
Why is the build process using the `eosio-cc` compiler to compile the Clang module?

**Comment by RayOshow** [comment]
Me too...

I have been using VM with 12GB.
EOS.IO 1.0 was OK, but  EOS.IO 1.4 is NG.

I don't know why.

**Comment by jeffreyssmith2nd** [comment]
I can't reproduce this on 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.

**Comment by lonkly** [comment]
Reproduced on 1.6.3 (built from GitHub)

`[cmake] The C compiler identification is AppleClang 11.0.0.11000033
[cmake] The CXX compiler identification is AppleClang 11.0.0.11000033
[cmake] Check for working C compiler: /usr/bin/clang
[cmake] Check for working C compiler: /usr/bin/clang -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Check for working CXX compiler: /usr/bin/clang++
[cmake] Check for working CXX compiler: /usr/bin/clang++ -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Detecting CXX compile features
[cmake] Detecting CXX compile features - done
[cmake] Setting up Eosio Wasm Toolchain 1.6.3 at //usr/local
[cmake] Setting up Eosio Wasm Toolchain 1.6.3 at //usr/local
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/lonkly/devel/DurakEOSContracts/build --config Release --target all -- -j 6
[build] Scanning dependencies of target lanterntoken.wasm
[build] Scanning dependencies of target durakgame.wasm
[build] [ 25%] Building CXX object contracts/src/lanterntoken/CMakeFiles/lanterntoken.wasm.dir/lanterntoken.cpp.o
[build] [ 50%] Building CXX object contracts/src/durakgame/CMakeFiles/durakgame.wasm.dir/durakgame.cpp.o
[build] eosio-cpp: Unknown command line argument '-mmacosx-version-min=10.14'.  Try: '//usr/local/bin/eosio-cpp -help'
[build] eosio-cpp: Did you mean '-stats-json=10.14'?
[build] eosio-cpp: Unknown command line argument '-mmacosx-version-min=10.14'.  Try: '//usr/local/bin/eosio-cpp -help'
[build] eosio-cpp: Did you mean '-stats-json=10.14'?
[build] make[2]: *** [contracts/src/durakgame/CMakeFiles/durakgame.wasm.dir/durakgame.cpp.o] Error 1
[build] make[2]: *** [contracts/src/lanterntoken/CMakeFiles/lanterntoken.wasm.dir/lanterntoken.cpp.o] Error 1
[build] make[1]: *** [contracts/src/durakgame/CMakeFiles/durakgame.wasm.dir/all] Error 2
[build] make[1]: *** Waiting for unfinished jobs....
[build] make[1]: *** [contracts/src/lanterntoken/CMakeFiles/lanterntoken.wasm.dir/all] Error 2
[build] make: *** [all] Error 2
[build] Build finished with exit code 2`
