### ISSUE TITLE
eosio-cpp --abigen doesn't define ABIGEN macro

### ISSUE THREAD

**Issue by smlu** [EOSIO/eosio.cdt#121]
When generating abi file through `eosio-cpp` there is no way to detect this in code. Where this is useful is when including data structure from other contracts that shouldn't be defined in contract's abi. E.g. including token's db structure to check the current balance.

The `ABIGEN` macro is also defined in deprecated `eosiocpp`.
https://github.com/EOSIO/eos/blob/master/tools/eosiocpp.in#L113

**Comment by larryk85** [comment]
I am currently working on a better mechanism for this use case.

**Comment by nathanhourt** [comment]
Has this been addressed yet? I'm having trouble getting ABI generation to understand my enum, and I was thinking about doing something like

```cpp
#ifdef ABIGEN
using MyEnum = uint16_t;
#else
enum MyEnum : uint16_t { /*...*/ };
#endif
```
