### ISSUE TITLE
Provide official Docker image on hub.docker.com

### ISSUE THREAD

**Issue by fproulx-eoscanada** [EOSIO/eosio.cdt#124]
It'd be good that you provide an official CDT Docker to replace the https://hub.docker.com/r/eosio/eos-dev/

That one is being updated, but not with the new toolchain and also has old `eosio.system` contracts, etc...

**Comment by flyq** [comment]
badly need it +1

**Comment by kesar** [comment]
+1

**Comment by nerdDan** [comment]
+1

**Comment by GMory** [comment]
+1

**Comment by nerdDan** [comment]
@WMcKibbin download the official `deb` package and install with `debtap`

**Comment by larryk85** [comment]
outdated by events, a docker image can be made from the supplied docker file.

**Comment by beac0n** [comment]
@nerdDan thank you very much for mentioning `debtap`. However, for eosio.cdt to work, I still needed to install `ncurses5-compat-libs`
