### ISSUE TITLE
Using C++ regex causes compile to fail

### ISSUE THREAD

**Issue by znebby** [EOSIO/eosio.cdt#125]
I'm trying to use C++ regex.

#include \<regex>

std::regex poly_regex("[a-z0-9_-]{11}", std::regex::icase);

When I build, I get:

/usr/local/eosio.cdt/bin/wasm-ld: error: locale.cpp.o: undefined symbol: strftime_l
/usr/local/eosio.cdt/bin/wasm-ld: error: memory.cpp.o: undefined symbol: __cxa_pure_virtual
/usr/local/eosio.cdt/bin/wasm-ld: error: system_error.cpp.o: undefined symbol: __cxa_pure_virtual

if I comment out that line (not the include), it builds fine.

**Comment by sim31** [comment]
I get `undefined symbol: __cxa_pure_virtual` error as well, when I have pure virtual functions in my own code.

Related issues:
https://github.com/EOSIO/eos/issues/5832
https://github.com/nlohmann/json/issues/1284

**Comment by larryk85** [comment]
the issue with __cxa_pure_virtual has been resolved for v1.3.0.  But, for classes like regex/stringstream and some other classes that rely on std::locale, most of the functionality is broken. Even if these were patched to work, they will bloat the size of your contract very dramatically, so to keep cpu/ram costs these types shouldn't be used any way.
