### ISSUE TITLE
eosio-cpp freezes while compiling example file

### ISSUE THREAD

**Issue by HJBraaksma** [EOSIO/eosio.cdt#126]
As the title implies, I've tried to run eosio-cpp to compile the hello.cpp example file, but after a short moment, the process appears to stop dead in its tracks. I'm running in an Ubuntu 18.04.1 Virtual Machine, host machine Windows 10.

`> $ eosio-cpp hello.cpp -o hello.wasm -v`
`> clang version 7.0.0 (https://github.com/eosio/clang.git 0f0efd6a05ee928dfa1b505c55c0d90ae188488e) (https://github.com/eosio/llvm 31e1613c474cab51a80ac898ec31716273df3729)`
`> Target: wasm32`
`> Thread model: single`
`> InstalledDir: /usr/local/eosio.cdt/bin`
`>  "/usr/local/eosio.cdt/bin/clang-7" -cc1 -triple wasm32 -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model static -mthread-model single -masm-verbose -mconstructor-aliases -ffreestanding -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -v -coverage-notes-file /home/devteam/eos/contracts/eosio.cdt/examples/hello/hello.gcno -resource-dir /usr/local/eosio.cdt/lib/clang/7.0.0 -D BOOST_DISABLE_ASSERTS -D BOOST_EXCEPTION_DISABLE -I /usr/local/eosio.cdt/bin/../include/libcxx -I /usr/local/eosio.cdt/bin/../include/libc -I /usr/local/eosio.cdt/bin/../include -I /home/devteam/opt/boost/include -isysroot /usr/local/eosio.cdt/bin/../ -internal-isystem /usr/local/eosio.cdt/bin/..//include/c++/v1 -internal-isystem /usr/local/eosio.cdt/bin/..//include -O3 -fdeprecated-macro -fdebug-compilation-dir /home/devteam/eos/contracts/eosio.cdt/examples/hello -ferror-limit 19 -fmessage-length 80 -fno-builtin -fno-rtti -fno-threadsafe-statics -fobjc-runtime=gnustep -fno-common -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load /usr/local/eosio.cdt/bin/LLVMEosioApply.so -mllvm -use-cfl-aa-in-codegen=both -o hello.wasm -x c++ hello.cpp`
`> clang -cc1 version 7.0.0 based upon LLVM 7.0.0svn default target x86_64-unknown-linux-gnu`
`> ignoring nonexistent directory "/usr/local/eosio.cdt/bin/..//include/c++/v1"`
`> ignoring nonexistent directory "/usr/local/eosio.cdt/bin/..//usr/local/include"`
`> ignoring nonexistent directory "/usr/local/eosio.cdt/lib/clang/7.0.0/include"`
`> ignoring nonexistent directory "/usr/local/eosio.cdt/bin/..//usr/include"`
`> ignoring duplicate directory "/usr/local/eosio.cdt/bin/../include"`
`>   as it is a non-system directory that duplicates a system directory`
`> #include "..." search starts here:`
`> #include <...> search starts here:`
`>  /usr/local/eosio.cdt/bin/../include/libcxx`
`>  /usr/local/eosio.cdt/bin/../include/libc`
`>  /home/devteam/opt/boost/include`
`>  /usr/local/eosio.cdt/bin/../include`
`> End of search list.`

**Comment by limulidae** [comment]
https://github.com/EOSIO/eosio.cdt/issues/123

**Comment by HJBraaksma** [comment]
Thank you, I must have missed that one. I'll be waiting for v1.3 then!
