### ISSUE TITLE
[help]  error: undefined symbol: apply

### ISSUE THREAD

**Issue by Danilo0120** [EOSIO/eosio.cdt#134]
~/eosio.cdt/demo1$ eosio-cpp init.cpp -o init.wasm  --abigen

/usr/local/eosio.cdt/bin/wasm-ld: error: undefined symbol: apply

**Comment by Danilo0120** [comment]
anybody knows how to solve this problem?

**Comment by cppfuns** [comment]
In your source dock file, finally join
`EOSIO_ABI( you_class, (you_action_function) ...)`

https://www.bcskill.com & http://knowledge.cryptokylin.io 
Welcome to join the community and do something good for it for eos

**Comment by Danilo0120** [comment]
@cppfuns  OK，Thanks
