### ISSUE TITLE
Including Third-party Libraries 

### ISSUE THREAD

**Issue by basarrcan** [EOSIO/eosio.cdt#141]
I want to accept a stringified JSON value as string, parse it in the contract and use it. I found numerous different libraries for that purpose but when I tried to include these libraries, I was getting an error on contract deployment. 

When I was using eosiocpp for compilation there was no error. But I got an error when I tried to set contract.

`Using already assembled WASM...
Publishing contract...
Error 3070000: WASM Exception`

I switched to the eosio.cdt, it still compiles but shows those error at the end of the compilation.
`/usr/local/eosio.cdt/bin/wasm-ld: error: apim.manager.wasm: undefined symbol: JSON::Parse(wchar_t const*)
/usr/local/eosio.cdt/bin/wasm-ld: error: apim.manager.wasm: undefined symbol: JSONValue::AsObject() const
/usr/local/eosio.cdt/bin/wasm-ld: error: apim.manager.wasm: undefined symbol: JSONValue::AsString() const`

I tried 2 separate libraries, errors are very similar.
Links:
https://github.com/open-source-parsers/jsoncpp
https://github.com/MJPA/SimpleJSON 

Tried another library, got a different error
`/usr/local/eosio.cdt/bin/wasm-ld: error: apim.manager.wasm: undefined symbol: __cxa_pure_virtual
/usr/local/eosio.cdt/bin/wasm-ld: error: memory.cpp.o: undefined symbol: __cxa_pure_virtual`
Link:https://github.com/dropbox/json11

Another library gives the `__cxa_pure_virtual` error: https://github.com/nlohmann/json

**Comment by larryk85** [comment]
The __cxa_pure_virtual issues should have been resolved by v1.3.1, but skip that version and use at the minimum v1.3.2.

**Comment by nidhaloff** [comment]
@basarrcan how did you included the lib in your project?
