### ISSUE TITLE
Can eosio-cpp add more examples? 

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eosio.cdt#155]
1.3.0 modified is too big compared to the previous changes, a little can not keep up ~

**Comment by trakout** [comment]
Yes, also the usage section in the current readme is outdated:

```

**Comment by lonkly** [comment]
Specifically for Multiindex, because it has only basic example. But how to use secondary indexes properly?

**Comment by lonkly** [comment]
> Agreed, secondary indexes is very important but totally ignored in docs.
This is in your struct: 
`uint64_t bysecondary() const { return secondary_id; }`

This is your index typedef.
`typedef eosio::multi_index<"tablename"_n, commits, indexed_by<"bysecondary"_n, const_mem_fun<tableclass, secondarykeytype, &tableclass::bysecondary> > > tb_something_by_secondary;`

Everywhere you had N() macro - "name"_n should be used. But remember to **NOT use underscore** anywhere in those names of indices and tables. by_secondary() won't work.

**Comment by svenpohl** [comment]
eosio-cpp 1.3.2 made significant changes... no N()-Makro, other contructor and Makros so the old written contracts are not compatible with EOSIO.CDT 1.3.2. Can eosio-cpp provide an example with 1) apply-method for receiving token, create an object and call functions of this class? 2) Send an EOS-transaction, 3) Write and read an multi index-table. This 3 functions are crucial for every smart-contract. The Example of developers.eos.com f.e. suggests: 
`void apply(uint64_t receiver, uint64_t code, uint64_t action) 
{   addressbook _addressbook(receiver);...` This instantiation throws an error: "error: no matching constructor for initialization of 'addressbook'"

**Comment by larryk85** [comment]
Examples of how to use multi-index are now in eosio.cdt.
