### ISSUE TITLE
eosio_assert - accept std::string as its second parameter

### ISSUE THREAD

**Issue by jonericcook** [EOSIO/eosio.cdt#156]
Normal use

`eosio_assert(0,"ERROR");`

Desired support

```
std::string user = "carl";
std::string assert_message = user + "cant use this feature";
eosio_assert(user == "doug", assert_message);
```

**Comment by larryk85** [comment]
As @heifner mentioned using the `c_str` method of string will work with eosio_assert. A proper C++ wrapper could be trivially added to the next minor release of eosio.cdt.
