### ISSUE TITLE
Multi_index issue

### ISSUE THREAD

**Issue by trakout** [EOSIO/eosio.cdt#159]
Hi there, using `1.3.1`, having an issue with multi_index, I might be using `eosio::name` incorrectly, or this is a bug.

*.hpp:
```
...
TABLE globalval {
           uint32_t id;
           uint64_t val;
           uint64_t primary_key() const { return id; }
           EOSLIB_SERIALIZE(globalval, (id)(val));
};

typedef eosio::multi_index<"globalval"_n, globalval> globalvalIndex;
...
```

*.cpp
```
...
globalvalIndex globalvals(_self, _self);
...
```

During ABI generation this fails with:
"no matching constructor for initialization of 'Namespacen::Classn::globalvalIndex' (aka 'multi_index<"globalval"_n, Namespacen::Classn::globalval>')"

**Comment by larryk85** [comment]
For multi_index, the scope is still a uint64_t, so change your line to `globalvalIndex globalvals(_self, _self.value)`, this will resolve your issue.
