### ISSUE TITLE
'eosiolib/currency.hpp' file not found

### ISSUE THREAD

**Issue by jonericcook** [EOSIO/eosio.cdt#171]
This is a continuation from #117 

@larryk85 you mentioned to use the `eosio.token` contract. Could you provide a quick example on how to do that. I ask because I am trying to use the new .cdt v1.3+ to write contracts that can handle incoming EOS. I am following the process per this link.

https://gist.github.com/tbfleming/d230f3ab2998e8858d3e51af7e4d9aeb

**Comment by MrToph** [comment]
Did you find out how to do it?

**Comment by MrToph** [comment]
I figured it out and wrote [a tutorial about it](https://cmichel.io/eos-1-3-contract-development-toolkit-updates/). `currency.hpp` was being deprecated and now you can just use the "unpacked" structure. The post contains the example.
