### ISSUE TITLE
3015004 invalid_type_inside_abi: The type defined in the ABI is invalid

### ISSUE THREAD

**Issue by onigirisan** [EOSIO/eosio.cdt#172]
When I use the upgrade cdt from 1.x to 1.3.2 , the generated abi reports this error when set contract. Anyone encountered same problem here? Any help would be appreciated!

**Comment by onigirisan** [comment]
In addition, I run the unit test in eosio.contracts and all failed with following error

```bash
3015004 invalid_type_inside_abi: The type defined in the ABI is invalid
account
    {"type":"account"}
    thread-0  abi_serializer.cpp:261 validate

    {"t":["accounts","account"]}
```

```bash
3015004 invalid_type_inside_abi: The type defined in the ABI is invalid
action[]
    {"type":"action[]"}
    thread-0  abi_serializer.cpp:245 validate

    {"field":{"name":"context_free_actions","type":"action[]"}}
    thread-0  abi_serializer.cpp:246 validate

    {"s":["transaction",{"name":"transaction","base":"transaction_header","fields":[{"name":"context_free_actions","type":"action[]"},{"name":"actions","type":"action[]"},{"name":"transaction_extensions","type":"extension[]"}]}]}
    thread-0  abi_serializer.cpp:247 validate
```

**Comment by jonericcook** [comment]
I am getting the same issue. I used the newest `eosio.cdt` to generate the `.abi` and `.wasm` for `eosio.token`

I am able to set the contract but when I go to create the token, I get this
```
Work-MacBook-Pro:eosio.token joneric.cook$ cleos push action eosio.token create '[ "eosio", "1000000000.0000 SYS"]' -p eosio.token@active
Error 3015004: The type defined in the ABI is invalid
```

@larryk85

**Comment by larryk85** [comment]
Fixes for a couple of ABI generation issues are resolved and will go out in a patch release by the end of today.

**Comment by herman5** [comment]
Thanks @larryk85 - can confirm that I am experiencing this same issue on a fresh build following the [docs](https://developers.eos.io/eosio-home/docs/token-contract) step by step.

**Comment by jonericcook** [comment]
@larryk85 awesome, thank you! Could you post back here for when we can go pull down the newest code?

**Comment by herman5** [comment]
This resolved my problem. Thank you!

**Comment by larryk85** [comment]
@jonericcook v1.3.2 is now available, so pull down the latest and it should resolve your issues.

**Comment by onigirisan** [comment]
@larryk85 awesome! It works great, thank you!
