### ISSUE TITLE
get_table_rows keep failure in "The type defined in the ABI is invalid" (error code 3015004)

### ISSUE THREAD

**Issue by lovecactus** [EOSIO/eosio.cdt#174]
Hi,

I was trying to post to v1/chain/get_table_rows to get my "accounts" table, using the following params:
```
{
 "json": true,
 "code":"tpaccount111", 
"scope":"tpaccount111",
"table":"accounts",
"table_key":"1",
"key_type":"i64",
"index_position":"1"
}
```

It keeps telling me 
```
{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 3015004,
        "name": "invalid_type_inside_abi",
        "what": "The type defined in the ABI is invalid",
        "details": [
            {
                "message": "account",
                "file": "abi_serializer.cpp",
                "line_number": 261,
                "method": "validate"
            },
            {
                "message": "",
                "file": "abi_serializer.cpp",
                "line_number": 262,
                "method": "validate"
            }
        ]
    }
}
```

Any suggestion on which type I used wrong?  Thanks!

UPDATE:

I figured out that when I compile it with 1.3.x branch SDK, this error happens  even in standard eosio.token contracts. 
Switched back to 1.2.x, get_table_rows worked.

**Comment by StarryJapanNight** [comment]
Same for me. I am not sure why, other than I am running cdt1.3.1. I will try upgrading to the latest version of the software.

**Comment by larryk85** [comment]
Please try v1.3.2 as this should have resolved any of these issues.
