### ISSUE TITLE
How to access table in cpp file?

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eosio.cdt#176]
I am using eosio.cdt version 1.3.2
Here is my table code and i want to know that how to access this table in .cpp file
```
 struct [[eosio::table]]
    userdata {
    capi_name user;
    string data;
    uint32_t time; 
    

    capi_name primary_key() const { return user; }
    EOSLIB_SERIALIZE( userdata , (user) (data) (time) );
    };

        typedef eosio::multi_index<"userdata"_n, userdata> usertable;
```

I have tried this         `usertable userdata(get_self(),get_self());`
to access table in .cpp file but it shows me error 
```
 error: unknown type name 'usertable'
        usertable userdata(get_self(),get_self());
```
and also want to know that as we call contract construct in previous versions like 
`test(self) : contract(self) {}; `
we need to call this in newer version also? can we access "self" without this constructor ? if yes, then how to use this constructor in newer version.

**Comment by cppfuns** [comment]
usertable userdata(_self,_self.value);   

No need
test(self) : contract(self) {};

---
Welcome to join [BCSkill](https://www.bcskill.com),A community that loves eos technology

**Comment by yashbhavsar007** [comment]
Thanks for your comment...issue resolved closing now

**Comment by yashbhavsar007** [comment]
It's requested to update this in documentation also because all new developers will not aware of this.
