### ISSUE TITLE
1.3.2: Generated abi file contains no tables

### ISSUE THREAD

**Issue by anykeyjunkie** [EOSIO/eosio.cdt#178]
Hi,
I defined a table in my own contract like:
```
struct [[eosio::table]] mystruct {...}
typedef eosio::multi_index<"tablename"_n,mystruct> s_table;
```
Still, when I run `eosio-cpp` command with `abigen` flag, the generated abi has an empty tables section. Documentation says to take a look into ./examples/abigen_test/test.cpp contract. I tried the source code and compiled via `eosio-cpp -o test.wasm test.cpp --abigen`, but the whole .abi file has empty sections.

Thanks for help in advance.

**Comment by larryk85** [comment]
It appears that you using an older version of cdt the new version of cdt changed that example to abitest.cpp.  But, if you are using v1.3.2.  First make sure that either you define the table struct `mystruct` in the class that is the containing contract (i.e. you are using either the `CONTRACT` macro or `class [[eosio::contract]]`), or you define the table with an explicit `[[eosio::contract("<contract name>")]]` attribute ( so `struct [[eosio::table, eosio::contract("<contract name>")]] mystruct {...}`).  Please read the section `Differences between Version 1.2.x and Version 1.3.x` and specifically the subsection `attributes` to read about the new contract attribute and how that works.

**Comment by anykeyjunkie** [comment]
Thanks for the hints. I solved it:
1. For the sample code, I used the most current one from abitest.cpp, but renamed the file. Wenn it is named abitest.cpp, the abi file gets created properly.
2. In my own contract, I changed
`class hello : public eosio::contract {`
to
`CONTRACT hello : public eosio::contract {`
