### ISSUE TITLE
ABI generation does not resolve contract name when in subfolder

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eosio.cdt#181]
Hi, when I run `eosio-cpp` with the `--abigen` flag and I do not directly point to a file in my cwd, but in a sub-folder, the contract name resolution does not work and an empty `.abi` file is output.

```
eosio-cpp contract/test.cpp -o contract/test.wasm --abigen
```

When I `cd contract` and operate on the file directly, it creates the correct `.abi`:

```
eosio-cpp test.cpp -o test.wasm --abigen
```

## Workaround

A workaround for now is to manually pass the `--contract <name>` flag when compiling files in a subfolder:

```
eosio-cpp contract/test.cpp -o contract/test.wasm --abigen --contract=test
```

**Comment by clar** [comment]
+1 
thanks for the workaround!

**Comment by jeffreyssmith2nd** [comment]
This is no longer an issue in 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.
