### ISSUE TITLE
where is uint256_t defined?

### ISSUE THREAD

**Issue by limulidae** [EOSIO/eosio.cdt#183]
$grep -r uint256_t *
grep: bin/eosio-objdump: No such file or directory
grep: bin/eosio-readelf: No such file or directory
grep: bin/eosio-readobj: No such file or directory
grep: bin/eosio-ranlib: No such file or directory
grep: bin/eosio-strip: No such file or directory
grep: bin/eosio-ar: No such file or directory
grep: bin/eosio-objcopy: No such file or directory
grep: bin/eosio-nm: No such file or directory
include/eosiolib/multi_index.hpp: *  - uint256_t
include/eosiolib/multi_index.hpp: *      uint256_t   secondary_3;
include/eosiolib/multi_index.hpp: *      uint256_t get_secondary_3() const { return secondary_3; }
include/eosiolib/multi_index.hpp: *          indexed_by< N(bysecondary3), const_mem_fun<record, uint256_t, &record::get_secondary_3> >,

**Comment by Jeiwan** [comment]
In "boost/multiprecision/cpp_int.hpp", but there's no `uint256_t` defined in `eosio`, so you cannot use it in contracts.
There are `key256` and `capi_checksum256` but I haven't tested them yet.

**Comment by larryk85** [comment]
uint256_t is not defined, the documentation in the multi-index doxygen comments is outdated.
