### ISSUE TITLE
How to initialize the new multi_index table?

### ISSUE THREAD

**Issue by fundurian** [EOSIO/eosio.cdt#184]
ever since i update the eosio.cdt to version 1.3 I am having huge difficulty to initialize the table

my code as below

ACTION add()
        {
                table_b mytable(_self,_self);

        }

TABLE tabb {
   uint64_t a;
   int b;
    uint64_t primary_key() const {return a;}
};

typedef eosio::multi_index<"tabb"_n, tabb> table_b;

when i compile i got below error

hello.cpp:15:11: error: no matching constructor for initialization of 'hello::table_b' (aka
      'multi_index<"tabb"_n, hello::tabb>')
                table_b mytable(_self,_self);
                        ^       ~~~~~~~~~~~
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:671:7: note: candidate constructor not viable: no known
      conversion from 'eosio::name' to 'uint64_t' (aka 'unsigned long long') for 2nd argument
      multi_index( name code, uint64_t scope )

please help

**Comment by znebby** [comment]
The second argument of the multi-index constructor takes a uint64_t, and name no longer implicitly casts to uint64_t.

Therefore, change your constructor to:

table_b mytable(_self,_self.value);

.value gets the uint64_t representation of a name.

**Comment by fundurian** [comment]
thanks, it work
