### ISSUE TITLE
std::stringstream not working as expected

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eosio.cdt#186]
This code
```
         std::stringstream ss;
         ss << "hello ";
         ss << 12345;
         ss << " abc";
         print((const char *)ss.str().c_str());
``` 
results in ```hello``` only

**Comment by jeffreyssmith2nd** [comment]
On 1.6.2 the following code gives `/usr/local/eosio.cdt/bin/wasm-ld: error: ios.obj: undefined symbol: std::uncaught_exception()` at compilation time.

```
#include <eosio/eosio.hpp>
#include <eosio/print.hpp>

#include <sstream>

using namespace eosio;

class testing : public contract {
    public:
        using contract::contract;

        [[eosio::action]]
        void test() {
            std::stringstream ss;
            ss << "hello ";
            ss << 12345;
            ss << " abc";
            eosio::print((const char *)ss.str().c_str());
        }
};
```

**Comment by kesar** [comment]
also getting same error using stringstream

**Comment by svezyridis** [comment]
same error here

**Comment by jeffreyssmith2nd** [comment]
Issue #458 highlighted issues with `istringstream` as well.

**Comment by swatanabe-b1** [comment]
The cause of the link error is https://github.com/EOSIO/libcxx/commit/ef8d14da3caebbdeb558bec32e7cba3489b94e86#diff-7591bd1d20b1b9023f2b69f7c13a3ca2.  If I revert that, I can't reproduce the original issue.

**Comment by swatanabe-b1** [comment]
The problem is happening because the generic overloads of operator<< in datastream.hpp are a better match than std::basic_ostream::operator<<.
