### ISSUE TITLE
cdt abi generation misses struct, misses struct used in table and misses the key definitions.

### ISSUE THREAD

**Issue by halsaphi** [EOSIO/eosio.cdt#188]
Using:

eosio-cpp -abigen youvote.cpp -o youvote.wasm

on a file containing

   struct [[eosio::table]] **pollvotes** 
    {
        uint64_t     key; 
        uint64_t     pollId;
        std::string  pollName; // name of poll
        std::string  account; //this account has voted, use this to make sure noone votes > 1

        uint64_t primary_key() const { return key; }
        uint64_t by_pollId() const {return pollId; }
    };
    typedef eosio::multi_index<"pollvotes"_n, pollvotes, eosio::indexed_by<"pollid"_n, eosio::const_mem_fun<pollvotes, uint64_t, &pollvotes::by_pollId>>> votes;

Generates an abi with no struct **pollvotes** definition
Generates an abi with a tables section containing 
        {
            "name": "pollvotes",
            "type": "pollvotes",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        }

i.e. missing type (no struct either) and no key_names added.

**Comment by kesar** [comment]
not sure if it will fix it, but try to call the struct in singular -> pollvote

**Comment by larryk85** [comment]
I am not able to replicate this with v1.3.2, I get a struct definition with the fields and the entry in the table section.  The key_names/key_types section has been deprecated for a very long time and not used anywhere internally and as such abigen doesn't fill those in.
