### ISSUE TITLE
1.3.2: action.send() -> compiler error ("No such file or directory")

### ISSUE THREAD

**Issue by anykeyjunkie** [EOSIO/eosio.cdt#197]
Hi,
I have defined a contract `hello `with this method inside:
```
[[eosio::action]]
void hi( capi_name user ) {
  print( "Hello, ", name{user} );
}
```
I would like to trigger this method from a different SC. I typed
```
action myaction = action(eosio::permission_level{get_self(), eosio::name("owner")}, 
        "hello"_n, 
	"hi"_n,				
	std::make_tuple(std::string("Bob")));
myaction.send();
```
If I try to compile, it gives error message
> /usr/opt/eosio.cdt/1.3.2/bin/wasm-ld: error: failed to write the output file: No such file or directory

If I comment out the last line, so I leave out the `myaction.send();`, it compiles. Any ideas? I thought I set the eosio.code permission for my caller and callee contract, but maybe I did something wrong. I apprectiate your help.
Is there somewhere an example contract for calling an action with the new 1.3 syntax? Documentation I found uses the pre 1.3 syntax unfortunately.

**Comment by larryk85** [comment]
This should have thrown a compilation error.  The type of the parameter to make_tuple should be a name type, also the new practice should be to use the C++ eosio::name type for all types, so go ahead and change the capi_name to simply name and then in make_tuple it should be "Bob"_n.  That should fix your issue.

**Comment by jeffreyssmith2nd** [comment]
This is no longer an issue in 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.
