### ISSUE TITLE
Got '0000004: error: bad magic value' after 'eosio-wasm2wast chintailease.wasm -o file.wast'

### ISSUE THREAD

**Issue by johnworthley** [EOSIO/eosio.cdt#199]
[chintailease.wasm.zip](https://github.com/EOSIO/eosio.cdt/files/2513690/chintailease.wasm.zip)

I am trying to disassemble the Chintailease smart contract but keep getting the error in the title. I attached the .wasm file for reference.

**Comment by larryk85** [comment]
Your "wasm" file is a wast file.  This also appears to have been compiled with the old toolchain and not eosio.cdt because of all of the `exports`.

**Comment by johnworthley** [comment]
You are right, it is a wast file. I am now getting error 
`
chintailease.wast:3088:23: error: unexpected token $0, expected end.
        call_indirect $0
                      ^^
chintailease.wast:3110:5: error: unexpected token end, expected ).
    end ;; $block2
    ^^^
`
after using `eosio-wast2wasm chintailease.wast`?

**Comment by larryk85** [comment]
The old toolchain (`eosiocpp`) produces an outdated syntax for `call_indirect`, your best option is to use `get code` with cleos to get a valid wasm then use `eosio-wasm2wast`.

**Comment by johnworthley** [comment]
I used `cleos get code --wasm chintailease`but this command is restricted? 

How would regenerating the .wast file with `eosio-wasm2wast`make it different than the currently generated .wast file?
