### ISSUE TITLE
eosio-cc: no such file or directory

### ISSUE THREAD

**Issue by zheyanglihz** [EOSIO/eosio.cdt#201]
When I tried to compile v1.2.1 on MACos that followed the instruction，I got these errors：

[ 11%] No install step for 'EosioClang'
[ 11%] No test step for 'EosioClang'
[ 11%] Completed 'EosioClang'
[ 12%] Built target EosioClang
[ 12%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_blowfish.c.o
[ 12%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_des.c.o
/bin/sh: /Users/cynthia/contracts/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/cynthia/contracts/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/sh: /Users/cynthia/contracts/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/cynthia/contracts/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_des.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_blowfish.c.o] Error 127
make[1]: *** [libraries/libc/CMakeFiles/c.dir/all] Error 2

I saw someone issued this problem before, but no conclusion. As that problem had been closed, I hope someone who know this can show some solution here.

**Comment by larryk85** [comment]
The main reason I have seen this issue being triggered is from not having enough memory during the build steps.  The build script should handle this better now and we have binary packages available.
