### ISSUE TITLE
I ran into a bug "/usr/local/eosio.cdt/bin/wasm-ld: error: undefined symbol: apply "Who can help me?"

### ISSUE THREAD

**Issue by redshround** [EOSIO/eosio.cdt#204]
When I use "eosio-cpp -o hello.wasm hello.cpp --abigen
", the feedback is "/usr/local/eosio.cdt/bin/wasm-ld: error: undefined symbol: apply
", I don't know what to do. Who can help me?"

![rza u _rnd eo3 vm4xq8p](https://user-images.githubusercontent.com/38822519/47543264-e4bd0900-d913-11e8-9c23-4c182161dc20.png)

**Comment by larryk85** [comment]
Does your contract have an "call' the EOSIO_DISPATCH macro? This defines apply and populates the dispatcher.

**Comment by redshround** [comment]
> 您的合同是否“调用”了EOSIO_DISPATCH宏？这定义了应用并填充调度程序。

Ok, I have solved this problem, thank you very much.

**Comment by wren424** [comment]
I have the same problem even if I call EOSIO_DISPATCH macro. How do you solve this problem?

**Comment by larryk85** [comment]
@wren424 can you supply your contract?

**Comment by wren424** [comment]
I have solved the problem by using EOSIO.cdt 1.3.1

**Comment by wren424** [comment]
@larryk85

**Comment by jeffreyssmith2nd** [comment]
This is no longer an issue in 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.
