### ISSUE TITLE
How to get ram price in eos contract

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eosio.cdt#205]
Used in eosiocpp
```
asset zion_contract::buyrambytes(uint32_t bytes) {
  eosiosystem::rammarket market(N(eosio), N(eosio));
  auto itr = market.find(S(4, RAMCORE));
  eosio_assert(itr != market.end(), "RAMCORE market not found");
  auto tmp = *itr;
  return tmp.convert(asset(bytes, S(0, RAM)), CORE_SYMBOL);
}
```
How to get it in eosio-cpp? I want to calculate in the contract how much ram can be purchased by the current eos.

**Comment by smlu** [comment]
Maybe something like this:
```C++
using namespace eosiosystem;
using namespace eosio;
static constexpr auto k_eosio       = "eosio"_n;
static constexpr auto k_ram_sym     = symbol("RAM", 0);
static constexpr auto k_ramcore_sym = symbol("RAMCORE", 4);


rammarket market(k_eosio, k_eosio.value);
auto it = market.find(k_ramcore_sym.raw());
eosio_assert(it != market.end(), "RAMCORE market not found");
auto tmp = *it;

/* Convert EOS amount to ram bytes */
auto out_ram_bytes = tmp.convert(in_eos_quantity, k_ram_sym);
```
Dep: eosio cdt 1.3.x

**Comment by cppfuns** [comment]
https://github.com/EOSIO/eosio.cdt/search?q=eosiosystem&unscoped_q=eosiosystem

**Comment by smlu** [comment]
Yes, you'll have to copy the source code of `exchange_sate` (.hpp and .cpp) to your code. The blockchain doesn't provide you the 'code' definition of other contracts.

The latest version can be found here: https://github.com/EOSIO/eosio.contracts/blob/master/eosio.system/include/eosio.system

**Comment by cppfuns** [comment]
thank you for your reply
