### ISSUE TITLE
libraries/eosiolib/multi_index.hpp: comments still using N(xx) notation

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.cdt#211]
In libraries/eosiolib/multi_index.hpp, numerous comments explaining the usage of multi_index are still using the old N(xx) notation, instead of the new name("xx") or "xx"n

**Comment by fingera** [comment]
constexpr auto  my = "aaaa"_n; print(my); // evalutate in compiling time
print("bbbb"_n); // evaluate in run time

@larryk85 
https://stackoverflow.com/questions/39650122/how-to-ensure-constexpr-function-never-called-at-runtime

**Comment by fingera** [comment]
#define N(expr) [&]() { constexpr auto x = #expr##_n; return x; }()

Re-add macro N like this? @larryk85

**Comment by larryk85** [comment]
@fingera thanks for bringing that to my attention I just fixed the operator instead of reintroducing a macro.

**Comment by larryk85** [comment]
Resolved by PR #213
