### ISSUE TITLE
eosio-cpp

### ISSUE THREAD

**Issue by philipp-sorin** [EOSIO/eosio.cdt#214]
```eosio-cpp -o mydapp.wasm mydapp.cpp --abigen``` generates empty abi file for 
code written in https://developers.eos.io/eosio-home/docs/data-persistence. 

OS: macOS Hight Seirra 10.13.6 (17G2112), eosio.cdt version is 1.3.2

**Comment by redshround** [comment]
yes,i know these,That is very common and has nothing to do with you，That's because of the official mistake，so if you really need it，I suggest you write your own ABI file.

**Comment by philipp-sorin** [comment]
Sadly, any eta about fix?

**Comment by brianjohnson5972** [comment]
@philipp-sorin The documentation [above](https://developers.eos.io/eosio-home/docs/data-persistence) is written to be compiled with [CDT](https://github.com/EOSIO/eosio.cdt).  eosio-cpp is deprecated and will not support that code.  If you run this example with CDT and have an issue, please create a new issue.

**Comment by philipp-sorin** [comment]
What tool should I use now?
V1.4 reffers me to eosio-cpp(instead of eosiocpp in v 1.3)

**Comment by jgiszczak** [comment]
eosio-cpp is indeed the tool to use.  It was eosiocpp that was deprecated.

Can you paste your cpp file here?  So far as I know it should at least be generating the ABI for the actions.  The bugs have mostly been involved with correctly generating information about all data types in public structures.

**Comment by philipp-sorin** [comment]
@jgiszczak  as example you can take code https://developers.eos.io/eosio-home/docs/data-persistence from there :)

**Comment by larryk85** [comment]
The issue is that you are naming your output .wasm something other than the contract name.  Example: eosio-cpp -abigen -o addressbook.wasm mydapp.cpp or eosio-cpp -abigen --contract=addressbook -o mydapp.wasm mydapp.cpp or you can change the name of the addressbook class to mydapp.

**Comment by NewETown** [comment]
@larryk85 I think @philipp-sorin is bad at explaining the issue, I'm having a similar problem.

The eosio-cpp tool we're supposed to use according to the data-persistence tutorial is using EOS 1.3.x when it needs to be using 1.4.x. There's a mismatch in the constructors that can be seen here, it's a pretty big blocker for people new to the ecosystem:

`
eosio-cpp -o addressbook.wasm addressbook.cpp --abigen
addressbook.cpp:6:9: warning: unknown attribute 'contract' ignored [-Wunknown-attributes]
class [[eosio::contract]] addressbook : public eosio::contract {
        ^
addressbook.cpp:11:71: error: no matching constructor for initialization of 'eosio::contract'
  addressbook(name receiver, name code,  datastream<const char*> ds): contract(receiver, code, ds) {}
`

**Comment by riccardopersiani** [comment]
Any update on that? 

Here what happens if I launch the command:

 `eosio-cpp -o addressbook.wasm addressbook.cpp --abigen` 

with the **addressbook** example:

```addressbook.cpp:6:9: warning: unknown attribute 'contract' ignored [-Wunknown-attributes]
class [[eosio::contract]] addressbook : public eosio::contract {
        ^
addressbook.cpp:11:71: error: no matching constructor for initialization of 'eosio::contract'
  addressbook(name receiver, name code,  datastream<const char*> ds): contract(receiver, code, ds) {}
                                                                      ^        ~~~~~~~~~~~~~~~~~~
/usr/local/eosio.cdt/bin/../include/eosiolib/contract.hpp:26:7: note: candidate constructor not viable: requires
      single argument 'n', but 3 arguments were provided
      contract( account_name n ):_self(n){}
      ^
/usr/local/eosio.cdt/bin/../include/eosiolib/contract.hpp:18:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class contract {
      ^
/usr/local/eosio.cdt/bin/../include/eosiolib/contract.hpp:18:7: note: candidate constructor
      (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
addressbook.cpp:16:29: error: use of undeclared identifier '_code'
    address_index addresses(_code, _code.value);
                            ^
addressbook.cpp:16:36: error: use of undeclared identifier '_code'
    address_index addresses(_code, _code.value);
                                   ^
addressbook.cpp:45:36: error: use of undeclared identifier '_code'
    address_index addresses(_self, _code.value);
                                   ^
addressbook.cpp:66:39: error: unknown type name 'erase'
EOSIO_DISPATCH( addressbook, (upsert)(erase))
                                      ^
addressbook.cpp:66:31: error: C++ requires a type specifier for all declarations
EOSIO_DISPATCH( addressbook, (upsert)(erase))
                              ^
addressbook.cpp:66:46: error: expected function body after function declarator
EOSIO_DISPATCH( addressbook, (upsert)(erase))
                                             ^
1 warning and 7 errors generated.```

**Comment by NewETown** [comment]
@riccardopersiani 

Update - Uninstall and reinstall everything. There seems to be an issue (not sure if it's still there) with the Homebrew installation. Install from source when possible for the greatest likelihood of success :)

Hopefully this gets cleared up soon, sounds like there was latency between the most recent CDT and EOS releases and the updates pushed to the onboarding tutorials.

**Comment by serganus** [comment]
+1

**Comment by WeijiaChe** [comment]
Add 
```
public:
         using contract::contract;
```

**Comment by CodingOnMyCouch** [comment]
These are the errors I get when trying to compile my smart contract. I recently upgraded to eos.cdt v1.4.1 and eos v1.5.1.

To compile I use: eosio-cpp -o cardgame.wasm cardgame.cpp --abigen

The compiler complains:

cardgame.cpp:83:29: error: unknown type name 'startgame'; did you mean
      'cardgame'?
EOSIO_ABI(cardgame, (login)(startgame)(endgame)(nextround));
                            ^~~~~~~~~
                            cardgame
./cardgame.hpp:5:27: note: 'cardgame' declared here
class [[eosio::contract]] cardgame : public eosio::contract {
                          ^
cardgame.cpp:83:40: error: unknown type name 'endgame'
EOSIO_ABI(cardgame, (login)(startgame)(endgame)(nextround));
                                       ^
cardgame.cpp:83:49: error: unknown type name 'nextround'
EOSIO_ABI(cardgame, (login)(startgame)(endgame)(nextround));
                                                ^
cardgame.cpp:83:22: error: C++ requires a type specifier for all declarations
EOSIO_ABI(cardgame, (login)(startgame)(endgame)(nextround));
                     ^
cardgame.cpp:83:1: error: C++ requires a type specifier for all declarations
EOSIO_ABI(cardgame, (login)(startgame)(endgame)(nextround));

**Comment by CodingOnMyCouch** [comment]
Solved! I change EOSIO_ABI for EOSIO_DISPATCH. A non-empty ABI file is generated now
