### ISSUE TITLE
Any different between _code and _self param in contract.hpp?

### ISSUE THREAD

**Issue by lanskytian** [EOSIO/eosio.cdt#216]
The value of _code is same as _self when I print out in my contract class, and I saw there is no _code arg in [https://github.com/EOSIO/eos/blob/v1.4.0/contracts/eosiolib/contract.hpp](url)? because of different version or other reason?

**Comment by larryk85** [comment]
The difference is during notifications, when a notify is dispatched to your account, _code will be name of the contract sending you the notify.  The `contracts` folder in `eos` is very out of date and should be ignored.
