### ISSUE TITLE
How to compare checksums after 1.3.0?

### ISSUE THREAD

**Issue by Jeiwan** [EOSIO/eosio.cdt#217]
I'm comparing two `capi_checksum160` with `==` and get this error:

```
error: invalid operands to binary expression ('capi_checksum160' and
      'capi_checksum160')
      if (commit == check)
          ~~~~~~ ^  ~~~~~
/usr/local/eosio.cdt/bin/../include/eosiolib/fixed_key.hpp:246:9: note: candidate template ignored:
      could not match 'fixed_key<Size>' against 'capi_checksum160'
   bool operator==(const fixed_key<Size> &c1, const fixed_key<Size> &c2) {
```

It worked in an older version.

**Comment by Jeiwan** [comment]
Found this solution:

```cpp
std::equal(std::begin(checksum1.hash), std::end(checksum1.hash), std::begin(checksum2.hash))
```

I'll leave this issue open for now, maybe there's a better solution.

**Comment by Machine-Hum** [comment]
> Found this solution:
> 
> ```c++
> std::equal(std::begin(checksum1.hash), std::end(checksum1.hash), std::begin(checksum2.hash))
> ```
> 
> I'll leave this issue open for now, maybe there's a better solution.

Thanks! I tried looking at the asset256 function. Could not makes heads or tails of it!

**Comment by tradzero** [comment]
seems `memcmp(checksum1.hash, checksum2.hash, sizeof(checksum1.hash)) == 0` works
