### ISSUE TITLE
print.hpp seems broken in 1.4.0

### ISSUE THREAD

**Issue by hqblock** [EOSIO/eosio.cdt#258]
Hello, Noob here playing with EOS in a Ubuntu 18.04 (no VM) and using binaries

-I found that In 1.3.2 to print a string this compiles fine:
`print("Adding ", cname, "\n");`

but in 1.4.0 it fails to compile with **no member named 'print' in 'std::__1::basic_string&lt;char&gt;**

-To make it work I modified this line in print.hpp (as it was in 1.3.2), from:

`inline void print( std::string&& s) {`

to :

`inline void print( std::string& s) {`

and the contract compiles and runs properly.

**Comment by KevinHwangAi** [comment]
In which file?

**Comment by KevinHwangAi** [comment]
In which path of the file?

**Comment by hqblock** [comment]
-After some research I found that to print the string with the current print.hpp implementation you need to cast the string variable to an rvalue. To do so use _std::move_ :
`print("Adding ", std::move(cname), "\n");`

-Other option would be to overload the print method in print.hpp so the 2 methods exist, the one in 1.3.2:
`inline void print( std::string& s)`

and the one in 1.4.0:
`inline void print( std::string&& s)`

**Comment by hqblock** [comment]
Thanks @Trevor-Ultra , Unfortunately `std::to_string` doesn't work when _myvar_ is a string

**Comment by jeffreyssmith2nd** [comment]
This is no longer an issue in 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.
