### ISSUE TITLE
support different naming conventions for the functions.

### ISSUE THREAD

**Issue by hard-fault** [EOSIO/eosio.cdt#262]
At present, we can't have function names like, "onClick" or "on_click". It must be "onclick".
This will make code readability very difficult.

**Comment by arhag** [comment]
Actually, you can name the C++ function whatever you want. But in that case you must specify the EOSIO action name explicitly with the action attribute. For example:
```
[[eosio::action("onclick")]] void on_click( /* arguments */ );
```

**Comment by jeffreyssmith2nd** [comment]
In 1.6.2, using the name parameter to `eosio::action` as shown above will appropriately generate the ABI as well as the WASM.
