### ISSUE TITLE
FREE_MEM=`LANG=C free | grep "Mem:" | awk '{print $4}'`

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eosio.cdt#265]
https://github.com/EOSIO/eosio.cdt/blob/94c517c18ac15f9c69d78e030a1cdaaec06cee0d/build.sh#L66

should changed to FREE_MEM=`LC_ALL=C free | grep "Mem:" | awk '{print $4}'`

 in my computer it will look like this:

> root@efa086bea89f:~/eosio.cdt# LC_ALL=C free
              total        used        free      shared  buff/cache   available
Mem:       16442296     6968172     3722580      407648     5751544     8730388
Swap:      67108860       32800    67076060
root@efa086bea89f:~/eosio.cdt# LANG=C free
              总计         已用        空闲      共享    缓冲/缓存    可用
内存：    16442296     6967972     3716388      413848     5757936     8724388
交换：    67108860       32800    67076060
root@efa086bea89f:~/eosio.cdt# locale
LANG=
LANGUAGE=
LC_CTYPE="zh_CN.utf8"
LC_NUMERIC="zh_CN.utf8"
LC_TIME="zh_CN.utf8"
LC_COLLATE="zh_CN.utf8"
LC_MONETARY="zh_CN.utf8"
LC_MESSAGES="zh_CN.utf8"
LC_PAPER="zh_CN.utf8"
LC_NAME="zh_CN.utf8"
LC_ADDRESS="zh_CN.utf8"
LC_TELEPHONE="zh_CN.utf8"
LC_MEASUREMENT="zh_CN.utf8"
LC_IDENTIFICATION="zh_CN.utf8"
LC_ALL=zh_CN.utf8

**Comment by jeffreyssmith2nd** [comment]
Based on the following two Stack Exchange answers, I agree it looks like `LC_ALL` would be the more appropriate setting to use.

https://stackoverflow.com/a/30480596
https://unix.stackexchange.com/a/87763

**Comment by zacck** [comment]
Is it ok for me to grab this issue?

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
