### ISSUE TITLE
eosiocpp vs eosio-cpp

### ISSUE THREAD

**Issue by rubenabix** [EOSIO/eosio.cdt#266]
I am using https://hub.docker.com/r/eosio/eos-dev/ 1.4.2 but it has eosiocpp but not eosio-cpp.
Any idea about that?

**Comment by gleehokie** [comment]
The eosio/cdt [package](https://hub.docker.com/r/eosio/cdt/) is up to date with the latest CDT release.

If you prefer you can also use the package files available [here](https://github.com/EOSIO/eosio.cdt/releases) or you can build from source (it takes a long time).
