### ISSUE TITLE
Can't compile with cdt v1.4.1

### ISSUE THREAD

**Issue by onigirisan** [EOSIO/eosio.cdt#276]
=========== Building eosio.contracts ===========

-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/local/eosio.cdt/bin/eosio-cc
-- Check for working C compiler: /usr/local/eosio.cdt/bin/eosio-cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/local/eosio.cdt/bin/eosio-cc"

  is not able to compile a simple test program.

  It fails with the following output:

**Comment by onigirisan** [comment]
=========== Building eosio.contracts ===========

-- Setting up Eosio Wasm Toolchain 1.4.1 at /usr/local/eosio.cdt
-- Using eosio.cdt version 1.4.1
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /usr/local/eosio.cdt/bin/eosio-cc
CMAKE_CXX_COMPILER= /usr/local/eosio.cdt/bin/eosio-cpp

-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/local/eosio.cdt/bin/eosio-cc
-- Check for working C compiler: /usr/local/eosio.cdt/bin/eosio-cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/local/eosio.cdt/bin/eosio-cc"

  is not able to compile a simple test program.

**Comment by onigirisan** [comment]
Revert [this](https://github.com/EOSIO/eosio.cdt/commit/3f16857a7a1dcd2aa74dfa6c0559267f6d34a0ed#diff-dbd8fb33f1444780d8d3c74b7e552416) commit solve my problem

**Comment by philipp-sorin** [comment]
Try to remove cmake files
