### ISSUE TITLE
eosio.cdt flat_map error

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eosio.cdt#277]
.hpp file defined the struct like this.

struct [[eosio::table("pool")]] gb_pool{
        uint64_t date;
        flat_map<name,asset> balances;
        asset stake_quantity;
        uint64_t primary_key() const {return date;}
};

when use eosio.cdt generate abi file.
just like this.
 "types": [
        {
            "new_type_name": "asset>",
            "type": ">"
        }
    ],

**Comment by larryk85** [comment]
`flat_map` and `flat_set` are both deprecated and will be completely removed with the next release of `eosio.cdt` (v1.5.0), you should be using `std::map` and `std::set` these are properly supported by `eosio-abigen`

**Comment by tvrc4m** [comment]
> `flat_map` and `flat_set` are both deprecated and will be completely removed with the next release of `eosio.cdt` (v1.5.0), you should be using `std::map` and `std::set` these are properly supported by `eosio-abigen`

it's not working. just like flat_map
using namespace std;
map<name,asset> balances;

 "types": [
        {
            "new_type_name": "asset>",
            "type": ">"
        }
    ],

**Comment by tvrc4m** [comment]
eosio.cdt  version  v1.4.1  ,its ok
