### ISSUE TITLE
Can't find system contracts

### ISSUE THREAD

**Issue by PhillipHamnett** [EOSIO/eosio.cdt#278]
I am trying to compile some code with the following command:

```eosio-cpp mycontract.cpp -I=$(INCLUDE_FOLDER)  -isystem=/path/to/eos/folder --abigen -o mycontract.wasm```

I get the error:
```
mycontract.cpp:13:10: fatal error: 'eosio.system/eosio.system.hpp' file not found
#include <eosio.system/eosio.system.hpp>
```

**Comment by larryk85** [comment]
Quick question, are you trying to compile against the 'system' contract from the `eos` repo or from `eosio.contracts` repo?

**Comment by PhillipHamnett** [comment]
The system contract from the eos repo.

**Comment by PhillipHamnett** [comment]
I tried it aswell with the eosio.contracts repo. Same issue.

However the contract does compile the wasm and abi files. It just produces this error everytime...
@larryk85

**Comment by lonkly** [comment]
This error is not only about system contracts, I have the same issue, but with 
```
#include <eosiolib/eosio.hpp>
#include <eosiolib/transaction.hpp>
#include <eosiolib/crypto.h>
#include <eosiolib/asset.hpp>
```
Still contract compiles and wasm is generated normally, it just kind of ignores includepath specified `"/usr/opt/eosio.cdt/1.4.1/include"`
And the same problem is on my mac, where the includepath links to brew-installed cdt package and still it "can not" find sources, even though I can easily go to definition etc.

**Comment by jeffreyssmith2nd** [comment]
Are you still seeing this issue on 1.6.2?

**Comment by lonkly** [comment]
I did experience it when I was using brew, but now I have build it manually and it worked. Now it only says that `cannot open source file "boost/preprocessor/seq/for_each.hpp" (dependency of "eosio/eosio.hpp")`, but at least I have intellisense now.

**Comment by jchung00** [comment]
This issue persists on version 1.6.2. Any updates on how this could be fixed? @jeffreyssmith2nd

**Comment by jeffreyssmith2nd** [comment]
@jchung00 How did you install CDT?

**Comment by lonkly** [comment]
@jeffreyssmith2nd through brew first, but then I wanted to get rid of this error and built it manually.  Headers were found, but `cannot open source file "boost/preprocessor/seq/for_each.hpp" (dependency of "eosio/eosio.hpp"` remains

**Comment by jchung00** [comment]
Used brew install. I fixed it by using the `-I` option to manually include the header file, but it should not have to be this way right?

**Comment by jeffreyssmith2nd** [comment]
Can you provide a small sample contract? I installed via brew and am not seeing any issues including `eosio` headers.

**Comment by jchung00** [comment]
Building the system contract in `EOSIO/eosio.contracts`. 
Using `eosio-cpp`.

**Comment by lonkly** [comment]
sudo cp /usr/local/Cellar/eosio.cdt/1.6.2/opt/eosio.cdt/include/boost/preprocessor/seq/for_each.hpp /usr/local/eosio.cdt/include/boost/for_each.hpp solved problem in my case. So cdt 1.6.2 installed by brew has the file, but the one built from sources+script does not.

**Comment by jeffreyssmith2nd** [comment]
On source installed 1.6.3, I don't see this issue. Please let me know if you're still having issues, otherwise this issue will be closed.
