### ISSUE TITLE
Wrong table name for ABI with  eosio::singleton

### ISSUE THREAD

**Issue by cz-theng** [EOSIO/eosio.cdt#280]
with this:
struct [[eosio::table, eosio::contract("gbmgameno111")]]  tbl_config{
    uint64_t bonus_down;
    uint64_t bonus_up;
};
typedef eosio::multi_index<"config"_n, tbl_config> midx_config;

CDT will generate right ABI with ： 
        {
            "name": "config",
            "type": "tbl_config",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        },
It's perfect right.

BUT if code is : 
struct [[eosio::table, eosio::contract("gbmgameno111")]]  tbl_config{
    uint64_t bonus_down;
    uint64_t bonus_up;
};
typedef eosio::singleton<"config"_n, tbl_config> config;

CDT give us : 

        {
            "name": "tbl_config",
            "type": "tbl_config",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        },

NAME: "tbl_config" will cause 

![image](https://user-images.githubusercontent.com/5254788/48565561-d0c55f80-e933-11e8-9406-31044ded173e.png)

**Comment by ijoywan** [comment]
when you use eosio::singleton ,you must typedef like this

```
typedef eosio::singleton<"config"_n, tbl_config> config;
typedef eosio::multi_index<"config"_n, tbl_config> dump_for_config;
```
The second line seems redundant, but it is very important for the current version.

**Comment by ekkis** [comment]
but this is clearly a bug so why was this issue closed?

**Comment by vtsurka** [comment]
Have same issue. Maybe reopen it?
@larryk85

**Comment by jeffreyssmith2nd** [comment]
I can confirm the following code on 1.6.2 produces the abi below. I can also confirm the recommended line above to add the `multi_index` typedef produces a correct abi.
```
#include <eosio/asset.hpp>
#include <eosio/eosio.hpp>
#include <eosio/name.hpp>
#include <eosio/singleton.hpp>

class [[eosio::contract]] testing : public eosio::contract {
    public:
        using eosio::contract::contract;

        [[eosio::action]] void test() {
        }

        struct [[eosio::table]] a_config {
            uint64_t bonus_down;
            uint64_t bonus_up;
        };
        typedef eosio::multi_index<"aconfig"_n, a_config> a_config_index;

        struct [[eosio::table]] b_config {
            uint64_t bonus_down;
            uint64_t bonus_up;
        };
        typedef eosio::singleton<"bconfig"_n, b_config> b_config_index;
};
```

```
"tables": [
        {
            "name": "aconfig",
            "type": "a_config",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        },
        {
            "name": "b_config",
            "type": "b_config",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        }
 ],
```

**Comment by sanaraufx** [comment]
This should be fixed with the latest version of cdt.
