### ISSUE TITLE
ABIs don't generate properly if wasm output isn't in current directory

### ISSUE THREAD

**Issue by justinjmoses** [EOSIO/eosio.cdt#281]
Steps to reproduce:

`git clone git@github.com:EOSIO/eosio.contracts.git` 

`mkdir -p build`

`eosio-cpp eosio.contracts/eosio.token/src/eosio.token.cpp -I eosio.contracts/eosio.token/include/ -o build/eosio.token.wasm --abigen`

This is the empty ABI generated
```
{
    "____comment": "This file was generated with eosio-abigen. DO NOT EDIT Thu Nov 15 13:51:58 2018",
    "version": "eosio::abi/1.1",
    "structs": [],
    "types": [],
    "actions": [],
    "tables": [],
    "ricardian_clauses": [],
    "variants": [],
    "abi_extensions": []
}
```

The issue seems be because the `wasm` file isn't in the current directory. When it is, the issue is resolved.

**Comment by ijoywan** [comment]
when you buid a contract outside the contract folder,you must add `-contract` option to figure out the contract name 

for you , the right command is 

```
eosio-cpp eosio.contracts/eosio.token/src/eosio.token.cpp -I eosio.contracts/eosio.token/include/ -o build/eosio.token.wasm --abigen -contract=eosio.token
```

**Comment by justinjmoses** [comment]
Ah I wasn't aware of that requirement. Thank you for the follow up @ijoywan.
