### ISSUE TITLE
version `GLIBCXX_3.4.22' not found (required by /usr/opt/eosio.cdt/1.3.2/bin/clang-7)

### ISSUE THREAD

**Issue by ShangXoL** [EOSIO/eosio.cdt#285]
version `GLIBCXX_3.4.22' not found (required by /usr/opt/eosio.cdt/1.3.2/bin/clang-7) ？

**Comment by Chris-Currin** [comment]
I had the same issue and fixed it using this link: https://stackoverflow.com/questions/43070900/version-glibcxx-3-4-22-not-found

Answer duplicated below
<blockquote>
You need to upgrade libstdc++6 to latest version like this

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```

After that you can check if you get GLIBCXX desired version like this:

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```

</blockquote>

**Comment by lixiaodong** [comment]
![image](https://user-images.githubusercontent.com/1568575/49262661-7aebce00-f482-11e8-9c61-7cbf9a2a48de.png)

still wrong.

**Comment by lixiaodong** [comment]
@Velua Thanks
