### ISSUE TITLE
Can't install or build

### ISSUE THREAD

**Issue by ChrysmOre** [EOSIO/eosio.cdt#286]
I can't seem to install or build from source following the tutorials on eos.io. Trying to install from package results in a huge list of errors that look like:

    E: Release 'eosio.cdt-1.3.2.x86_64.deb' for 'sublime-merge' was not found
    E: Release 'eosio.cdt-1.3.2.x86_64.deb' for 'mysql-connector-java' was not found
    E: Release 'eosio.cdt-1.3.2.x86_64.deb' for 'atom' was not found
    E: Release 'eosio.cdt-1.3.2.x86_64.deb' for 'discord' was not found

Trying to build form source I get as far as running build.sh but it fails halfway through-

    -- Setting up Eosio Wasm Toolchain 1.3.2 at 
    /home/userabuser/Documents/Programming/oes/projects/contracts/eosio.cdt
    -- Configuring done
    -- Generating done
    -- Build files have been written to: 
    /home/userabuser/Documents/Programming/oes/projects/contracts/eosio.cdt
    make: *** No targets specified and no makefile found.  Stop.

Can't find any solutions anywhere. I'm running Debian 8.0 (Jessie)

**Comment by jeffreyssmith2nd** [comment]
I can't reproduce this on 1.6.2, feel free to reopen if it becomes an issue in 1.6.x versions.
