### ISSUE TITLE
CDT 1.4.1 cannot generate correct ABI 

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.cdt#290]
CDT 1.3.2 can compile and generate correct ABI:

https://pastebin.com/ynpqVG8z

But with 1.4.1 it will generate an empty ABI:

https://pastebin.com/1SpHYFyK

Looks like a regression?

**Comment by larryk85** [comment]
This is the abi that that contract generated?

{
    "____comment": "This file was generated with eosio-abigen. DO NOT EDIT Mon Nov 19 09:29:44 2018",
    "version": "eosio::abi/1.1",
    "structs": [
        {
            "name": "addroom",
            "base": "",
            "fields": [
                {
                    "name": "room_id",
                    "type": "uint64"
                },
                {
                    "name": "room_description",
                    "type": "string"
                },
                {
                    "name": "room_owner",
                    "type": "name"
                },
                {
                    "name": "room_rate",
                    "type": "string"
                }
            ]
        },
        {
            "name": "removeroom",
            "base": "",
            "fields": [
                {
                    "name": "room_id",
                    "type": "uint64"
                }
            ]
        },
        {
            "name": "room",
            "base": "",
            "fields": [
                {
                    "name": "room_id",
                    "type": "uint64"
                },
                {
                    "name": "room_description",
                    "type": "string"
                },
                {
                    "name": "room_owner",
                    "type": "name"
                },
                {
                    "name": "room_rate",
                    "type": "string"
                }
            ]
        }
    ],
    "types": [],
    "actions": [
        {
            "name": "addroom",
            "type": "addroom",
            "ricardian_contract": ""
        },
        {
            "name": "removeroom",
            "type": "removeroom",
            "ricardian_contract": ""
        }
    ],
    "tables": [
        {
            "name": "room",
            "type": "room",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        }
    ],
    "ricardian_clauses": [],
    "variants": [],
    "abi_extensions": []
}

**Comment by larryk85** [comment]
Are you correctly specifying the "contract" name when compiling or using `eosio-abigen`?

**Comment by dixia** [comment]
closed as false alarm
