### ISSUE TITLE
ABI gen does not support arrays

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eosio.cdt#295]
I cannot use `uint64_t array[10]` or any other array type in a serialized struct.

The ABI output will just be:

```
TABLE test_table {
    uint64_t foo[26];
};

{
    "name": "test_table",
    "base": "",
    "fields": [
        {
            "name": "foo",
            "type": "[26]"
        }
    ]
}
```

A workaround is using `std::vector<uint64_t>`.

Are arrays supposed to be supported?

**Comment by lonkly** [comment]
Nope, as you have to manually allocate array memory to use it and it does not fit well in wasm. Use vector instead.
