### ISSUE TITLE
how to store chinese chars in table?

### ISSUE THREAD

**Issue by leochan007** [EOSIO/eosio.cdt#296]
i put std::wstring in table def.

compile failed.

    TABLE record {
       uint64_t id;
       uint32_t create_time;
       std::string account;
       std::wstring name;
}

ACTION insert(uint32_t create_time, std::wstring name ..............)

**Comment by cddjr** [comment]
utf8不也行吗，  为什么一定要用wchar-string。。。。

**Comment by leochan007** [comment]
@cddjr using string directly ?

**Comment by jeffreyssmith2nd** [comment]
I can confirm the following code causes a segfault on 1.6.2

```
#include <eosio/asset.hpp>
#include <eosio/eosio.hpp>
#include <eosio/name.hpp>

class [[eosio::contract]] testing : public eosio::contract {
    public:
        using eosio::contract::contract;

        [[eosio::action]]
        void test() {
        }

        struct [[eosio::table]] record {
            uint64_t id;
            uint32_t create_time;
            std::string account;
            std::wstring name;
        };

        typedef eosio::multi_index<eosio::name("record"), record> record_index;
};
```

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
