### ISSUE TITLE
eosio-cpp compile bug

### ISSUE THREAD

**Issue by gzlkylin** [EOSIO/eosio.cdt#301]
This is just a simplified example.

```
#define check(x) ((void)((x) || (dofalse(#x),0))) 
 void abort(); 
 void dofalse (const char *){ 
         abort(); 
 } 
 bool alwaysTrue(){  
         return true; 
 } 
 int main() {
       check(alwaysTrue()); 
//    check(true); 
}
```
compile this file eosio-cpp -c example.cpp
the wat file is:
```
(module
   (type (;0;) (func (param i32)))
   (type (;1;) (func))
   (type (;2;) (func (result i32)))
   (import "env" "__linear_memory" (memory (;0;) 0))
   (import "env" "__indirect_function_table" (table (;0;) 0 anyfunc))
   (import "env" "_Z5abortv" (func (;0;) (type 1)))
   (func (;1;) (type 0) (param i32)
     call 0)
   (func (;2;) (type 2) (result i32)
     i32.const 1)
   (func (;3;) (type 2) (result i32)
     call 0
     unreachable))
```
If I replace the "check(alwaysTrue());" with "check(true);"
```
int main() {
       check(true); 
}
```
output:
```
.....
(func (;3;) (type 2) (result i32)
     unreachable))
```
My question is not "unreachable", which is why "call 0" will appear in the above situation. dofalse absolutely cannot be executed.

More simplified version
```
extern "C" {
void dofalse(void);
}
bool alwayTrue(){return true;}
int main(){
	if (!alwayTrue()) {
		dofalse();
	}
}
```
import func "dofalse" will be executed

**Comment by larryk85** [comment]
The output is what I would expect, you are defining a function that doesn't return a value.  So the compiler will insert an abort and unreachable to keep any unexpected behavior from happening.  If you change your main function to simply return 0 at the end or to void this compiles as you are expecting.  Also, why are you using main?  For these kinds of tests you should be using the `apply` function.

**Comment by gzlkylin** [comment]
> The output is what I would expect, you are defining a function that doesn't return a value. So the compiler will insert an abort and unreachable to keep any unexpected behavior from happening. If you change your main function to simply return 0 at the end or to void this compiles as you are expecting. Also, why are you using main? For these kinds of tests you should be using the `apply` function.

My question is not "unreachable", which is why "call 0" will appear in the above situation. 
dofalse absolutely cannot be executed.

**Comment by gzlkylin** [comment]
> The output is what I would expect, you are defining a function that doesn't return a value. So the compiler will insert an abort and unreachable to keep any unexpected behavior from happening. If you change your main function to simply return 0 at the end or to void this compiles as you are expecting. Also, why are you using main? For these kinds of tests you should be using the `apply` function.

This is just a simplified example.

**Comment by swatanabe-b1** [comment]
> dofalse absolutely cannot be executed.

Wrong.  main has undefined behavior.  The compiler is entirely within its rights here.

In particular, the reason this happens is that the compiler decides that the only way for main to be defined is if ``alwaysTrue`` returns false and ``doFalse`` does not return.  Thus it optimizes away the test and leaves an unconditional call to doFalse.  Then it inlines ``alwaysTrue`` and ``doFalse`` giving the final code that you see.

When you use a literal ``true``, then that make the result of the test visible to the optimizer sooner, giving a different result.
