### ISSUE TITLE
print function should be passed for validation

### ISSUE THREAD

**Issue by cbaus** [EOSIO/eosio.cdt#307]
Hi, this is a suggestion but when validating the transaction, can the print function be disabled?
This relates to [Stack Exchange Topic](https://eosio.stackexchange.com/questions/3163/does-print-cost-cpu-cycles/3379#3379)
The output could still be generated by nodes that want to do that (config setup maybe) but it seems to me the BPs print always.
Am I missing something?

**Comment by jeffreyssmith2nd** [comment]
See #392 for discussion about a "debug" mode that allows print functions to be enabled/disabled in contracts.
