### ISSUE TITLE
CMake ricardian clauses not re-generated on resource files changes

### ISSUE THREAD

**Issue by maoueh** [EOSIO/eosio.cdt#309]
### Versions:
 * eosio.cdt 1.4.1

### Description
When using `CMake`, if the actual resource file containing the ricardian clauses (either the contracts or clauses file) is the only changes, the ABI file is not re-generated correctly when doing a simple `make`.

Repro:

```
# Assuming at root of this repository
cd `examples/hello`
mkdir build
cd build && cmake .. && make && cd ..
echo "Adding stuff at the end of clauses" >> hello.clauses.md
cd build && make cd ..
cat build/hello.abi | grep "Adding stuff at the end of clauses"
echo $?
# Prints 1, should be 0
```

Same thing if `echo "Adding stuff at the end of clauses" >> hello.contracts.md`. The `grep` exit code should be 0.

Sorry if this is already tracked, did a search but did not find anything related.

**Comment by jeffreyssmith2nd** [comment]
I'm seeing this still on 1.6.2

**Comment by swatanabe-b1** [comment]
The reason that this happens is that the resource file is found implicitly based on the contract name instead of being handled by CMake like a normal input file.  CMake doesn't even know whether it exists at all.

**Comment by swatanabe-b1** [comment]
See also #455

**Comment by jeffreyssmith2nd** [comment]
Handled by #748
