### ISSUE TITLE
pure c call action_data_size() throw Error 3070003

### ISSUE THREAD

**Issue by czom** [EOSIO/eosio.cdt#313]
Error 3070003: Serialization Error Processing WASM

**Comment by larryk85** [comment]
@czom I'm going to need a bit more information.  What does your contract code look like?

**Comment by czom** [comment]
> @czom I'm going to need a bit more information. What does your contract code look like?

#include <string.h>
#include <stdlib.h>
#define bool int
#include <eosiolib/print.h>
#include <eosiolib/system.h>
#ifdef __cplusplus
extern "C" {
#else
#define false 0
#endif
    /** declare extern function */
    uint32_t read_action_data( void* msg, uint32_t len );
    uint32_t action_data_size();

    uint8_t char_to_value( char c ) {
        if( c == '.')
            return 0;
        else if( c >= '1' && c <= '5' )
            return (c - '1') + 1;
        else if( c >= 'a' && c <= 'z' )
            return (c - 'a') + 6;
        else
            eosio_assert( false, "character is not in allowed character set for names" );

        return 0; // control flow will never reach here; just added to suppress warning
    }

    uint64_t name( char* str)
    {
        uint64_t value = 0, v;
        size_t strsize, n, i;
        strsize = strlen(str);

        if( strsize > 13 ) {
            eosio_assert( false, "string is too long to be a valid name" );
        }

        n = strsize > 12u ? 12u : strsize;
        for( i = 0; i < n; ++i ) {
            value <<= 5;
            value |= char_to_value( str[i] );
        }

        value <<= ( 4 + 5*(12 - n) );
        if( strsize == 13 ) {
            v = char_to_value( str[12] );
            if( v > 0x0Full ) {
               eosio_assert(false, "thirteenth character in name cannot be a letter that comes after j");
            }
            value |= v;
        }

        return value;
    }

    char* name_as_string( uint64_t value, char* begin, size_t len ) {
         static const char* charmap = ".12345abcdefghijklmnopqrstuvwxyz";
         static const uint64_t mask = 0xF800000000000000ull;
         uint64_t v, i, indx;

         if( (begin + 13) < begin || len < 13 ) return begin;

         v = value;
         for( i = 0;   i < 13; ++i, v <<= 5 ) {
            if( v == 0 ) return begin;

            indx = (v & mask) >> (i == 12 ? 60 : 59);
            *begin = charmap[indx];
            ++begin;
         }

         return begin;
    }

    void hi(uint64_t receiver, uint64_t code) {
        uint64_t v;
        char name[13];
        char *buf = (char*)malloc(8);
        read_action_data(buf, 8);
        read_action_data(NULL, 0);
        action_data_size(); /* call the action_data_size Error 3070003: Serialization Error Processing WASM*/ 
    }

    void apply(uint64_t receiver, uint64_t code, uint64_t action) {
        if ( code == receiver ) {
            if (action == name("hi")) {
                hi(receiver, code);
            } else {
                /* prints(action); */
            }
        }
    }

#ifdef __cplusplus
}
#endif

{
    "version": "eosio::abi/1.1",
    "structs": [
        {
            "name": "hi",
            "base": "",
            "fields": [
                {
                    "name": "user",
                    "type": "name"
                }
            ]
        }
    ],
    "types": [],
    "actions": [
        {
            "name": "hi",
            "type": "hi",
            "ricardian_contract": ""
        }
    ],
    "tables": [],
    "ricardian_clauses": [],
    "variants": [],
    "abi_extensions": []
}

**Comment by czom** [comment]
pure C calling any function without arguments throws an exception.

**Comment by czom** [comment]
eosio-cc has a bug, hello.wasm:00002f3: error: type mismatch in call, expected [i32] but got []

**Comment by czom** [comment]
action_data_size () is defined as action_data_size(void); It works. 
Any function that has no arguments defines the argument to void
