### ISSUE TITLE
same_payer for singletons

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosio.cdt#314]
Seems that same_payer isn't working with singletons?
It's always requesting the authority of the previous payer after the initial payer assumes row.

This works fine
`SingletonTable(_self, scope).set(something, caller_account);`

After the above, this would not.
`SingletonTable(_self, scope).set(something, same_payer);`

**Comment by conr2d** [comment]
`eosio::same_payer` is defined in `multi_index.hpp`.  If you want to use it with singleton, include `multi_index.hpp`.

**Comment by nsjames** [comment]
I've already got that included since I'm using multi_index in other places.
The issue isn't it looking for the `same_payer` variable ( or i'd just replace it with `name("")` ), it's that it complains about wanting the authority of the original row owner when trying to modify the row from a secondary user. 


```
"{"code":500,"message":"Internal Service Error","error":{"code":3090004,"name":"missing_auth_exception","what":"Missing required authority","details":[{"message":"missing authority of eosio","file":"apply_context.cpp","line_number":151,"method":"require_authorization"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":72,"method":"exec_one"}]}}"
```

**Comment by conr2d** [comment]
The contract can set `_self` (contract owner) or an authorizer of action as ram payer. If you deployed your contract to `alice` and `eosio` paid singleton RAM, `bob`'s action can change its ram payer to `bob` or `alice` only. (not `eosio`)

**Comment by nsjames** [comment]
I don't want it to change the payer. I want it to stay the same payer as it already is, and have it modified by other accounts in the same way that a multi_index does. 

`bob does action which creates singleton row in bob's name` -> `alice does action, and modifies bob's row without changing payer`.

**Comment by conr2d** [comment]
Hmm, after reading your comment, I looked for the source code handling ram payer.
https://github.com/EOSIO/eos/blob/master/libraries/chain/apply_context.cpp#L490-L500
https://github.com/EOSIO/eos/blob/master/libraries/chain/apply_context.cpp#L395-L404

It seems that if you not change the occupied RAM size by updating singleton data, `update_db_usage()` is not called, so evaluation for ram payer authorization doesn't occur. Did your update on singleton data change the occupied RAM size?

**Comment by nsjames** [comment]
Indeed, when doing something that wouldn't change ram size ( adding to existing vector ) it doesn't throw errors, but when doing something like adding to a vector it throws.

**Comment by nsjames** [comment]
It seems this is the offending line https://github.com/EOSIO/eos/blob/master/libraries/chain/apply_context.cpp#L400

Which would occur both in cases of lower or higher RAM consumption.

**Comment by nsjames** [comment]
Yes, I think this limitation was introduced after the "RAM Kidnapping" attacks started happening and it's no longer possible to grow rows without some sort of permissioned system. Shame, as that's incredibly limiting for dynamic rows that *should* grow. For instance, with this contract I'm working on part of the design is that users assume full costs of that RAM and get tokens in return for it, which makes this assertion counter-productive.

**Comment by nsjames** [comment]
I'm going to close this ticket out though as it seems this is *"working as intended"*.
