### ISSUE TITLE
seems TABLE macro not generate abi struct in out of CONTRACT macro

### ISSUE THREAD

**Issue by tradzero** [EOSIO/eosio.cdt#345]
eosio-cpp version 1.4.1  
when define TABLE in CONTRACT macro inside, can generate abi strcut, but when define in outside, not work.
code sample:
## test.cpp
```c++
#include "./table.cpp"

CONTRACT test : public contract {
    public:
        TABLE testtab2 {
            uint64_t id;
            uint64_t primary_key() const { return id; }
        };
        typedef multi_index<"testtab2"_n, testtab2> test2_table;
};
```
## table.hpp
```c++
#include <eosiolib/eosio.hpp>

using namespace eosio;

TABLE testtab {
    uint64_t id;
    uint64_t primary_key() const { return id; }
};
typedef multi_index<"testtab"_n, testtab> test_table;
```

run `eosio-cpp test.cpp -o test.wasm --abigen`
## test.abi
```
{
    "____comment": "This file was generated with eosio-abigen. DO NOT EDIT Thu Jan  3 10:35:56 2019",
    "version": "eosio::abi/1.1",
    "structs": [
        {
            "name": "testtab2",
            "base": "",
            "fields": [
                {
                    "name": "id",
                    "type": "uint64"
                }
            ]
        }
    ],
    "types": [],
    "actions": [],
    "tables": [
        {
            "name": "testtab2",
            "type": "testtab2",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        }
    ],
    "ricardian_clauses": [],
    "variants": [],
    "abi_extensions": []
}
```

not testtab in abi file's structs

**Comment by larryk85** [comment]
Yes, this is by design.  The contract macro ([eosio::contract] attribute) acts as a scope for your contract's actions and tables, so if you include another contract's header file (like token) you won't have their actions or tables in your abi.  If you need to define the table outside the scope of your contract you will have to use the `[[eosio::table("<contract name>")]` attribute directly.  So,
```c++
struct [[eosio::table("test")]] testtab {
    uint64_t id;
    uint64_t primary_key() const { return id; }
};
typedef multi_index<"testtab"_n, testtab> test_table;
```

**Comment by tradzero** [comment]
> Yes, this is by design. The contract macro ([eosio::contract] attribute) acts as a scope for your contract's actions and tables, so if you include another contract's header file (like token) you won't have their actions or tables in your abi. If you need to define the table outside the scope of your contract you will have to use the `[[eosio::table("<contract name>")]` attribute directly. So,
> 
> ```c++
> struct [[eosio::table("test")]] testtab {
>     uint64_t id;
>     uint64_t primary_key() const { return id; }
> };
> typedef multi_index<"testtab"_n, testtab> test_table;
> ```

OK Thanks for answer, and i think it should reflect in document. i will close this issue
