### ISSUE TITLE
multi_index compiling error

### ISSUE THREAD

**Issue by gyl19930522** [EOSIO/eosio.cdt#353]
when I am compiling contract file by eosio.cdt 1.4.1, I met a lot of problems of multi_index during compiling, my table has two secondary index, the struct is written as:

         struct [[eosio::table]] basicmatch {
            name            player;
            time_point_sec  ready_time;
            uint32_t        beat_num;

            uint64_t  primary_key()const { return player.value; }
            uint32_t  get_ready_time()const { return ready_time.utc_seconds; }
            uint32_t  get_beat_num()const { return beat_num; }
            EOSLIB_SERIALIZE(basicmatch, (player)(ready_time)(beat_num));
         };
         typedef eosio::multi_index< "basicmatch"_n, basicmatch,
                                    indexed_by< "readytime"_n, const_mem_fun<basicmatch, 
                                    uint32_t, &basicmatch::get_ready_time> >,
                                    indexed_by< "beatnum"_n, const_mem_fun<basicmatch, 
                                    uint32_t, &basicmatch::get_beat_num> > 
                                    > basicmatchs;

Compiling errors occured as following:

/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1710:50: error: 
      implicit instantiation of undefined template
      'eosio::_multi_index_detail::secondary_index_db_functions<unsigned long>'
               i.__iters[index_type::number()] = secondary_index_db_func...
                                                 ^
/usr/local/eosio.cdt/bin/../include/boost/hana/for_each.hpp:46:41: note: in
      instantiation of function template specialization
      'eosio::multi_index<4157073457596809216, eosio::sword::basicmatch,
      eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::emplace(eosio::name, (lambda
      at /home/gyl/eosio.cdt/examples/btlsword/btlsword.cpp:124:31)
      &&)::(anonymous class)::operator()(eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::item &)::(anonymous
      class)::operator()<boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_> >' requested
      here
                (void)Swallow{0, ((void)(*f)(static_cast<Xs&&>(xs)), 0)...};
                                        ^
/usr/local/eosio.cdt/bin/../include/boost/hana/basic_tuple.hpp:117:20: note: in
      instantiation of function template specialization
      'boost::hana::detail::on_each<(lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:39)
      *>::operator()<boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_> &,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, true> >::_> &>' requested
      here
            return static_cast<F&&>(f)(
                   ^
/usr/local/eosio.cdt/bin/../include/boost/hana/unpack.hpp:47:24: note: in
      instantiation of function template specialization
      'boost::hana::unpack_impl<boost::hana::basic_tuple_tag, void>::apply<0, 1,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_>,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, true> >::_> ,
      boost::hana::detail::on_each<(lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:39) *>
      >' requested here
        return Unpack::apply(static_cast<Xs&&>(xs), static_cast<F&&>(f));
                       ^
/usr/local/eosio.cdt/bin/../include/boost/hana/tuple.hpp:225:20: note: in
      instantiation of function template specialization
      'boost::hana::unpack_t::operator()<boost::hana::basic_tuple<boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_>,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, true> >::_> > &,
      boost::hana::detail::on_each<(lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:39) *>
      >' requested here
            return hana::unpack(static_cast<Xs&&>(xs).storage_, static_c...
                   ^
/usr/local/eosio.cdt/bin/../include/boost/hana/unpack.hpp:47:24: note: in
      instantiation of function template specialization
      'boost::hana::unpack_impl<boost::hana::tuple_tag,
      void>::apply<boost::hana::tuple<boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_>,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, true> >::_> > &,
      boost::hana::detail::on_each<(lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:39) *>
      >' requested here
        return Unpack::apply(static_cast<Xs&&>(xs), static_cast<F&&>(f));
                       ^
/usr/local/eosio.cdt/bin/../include/boost/hana/for_each.hpp:56:13: note: 
      (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see
      all)
            hana::unpack(static_cast<Xs&&>(xs),
            ^
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:13: note: in
      instantiation of function template specialization
      'boost::hana::for_each_t::operator()<boost::hana::tuple<boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time>, 0, true> >::_>,
      boost::hana::tuple<boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, false> >::_,
      boost::hana::type_impl<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::index<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num>, 1, true> >::_> > &, (lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1707:39)>'
      requested here
            hana::for_each( _indices, [&]( auto& idx ) {
            ^
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:291:13: note: in
      instantiation of function template specialization
      'eosio::multi_index<4157073457596809216, eosio::sword::basicmatch,
      eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::emplace(eosio::name, (lambda
      at /home/gyl/eosio.cdt/examples/btlsword/btlsword.cpp:124:31)
      &&)::(anonymous class)::operator()<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::item>' requested here
            c(*this);
            ^
/usr/local/eosio.cdt/bin/../include/libcxx/memory:3026:32: note: in
      instantiation of function template specialization
      'eosio::multi_index<4157073457596809216, eosio::sword::basicmatch,
      eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::item::item<(lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1684:51)>'
      requested here
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1684:26: note: in
      instantiation of function template specialization
      'std::__1::make_unique<eosio::multi_index<4157073457596809216,
      eosio::sword::basicmatch, eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::item,
      eosio::multi_index<4157073457596809216, eosio::sword::basicmatch,
      eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > > *, (lambda at
      /usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:1684:51)>'
      requested here
         auto itm = std::make_unique<item>( this, [&]( auto& i ){
                         ^
/home/gyl/eosio.cdt/examples/btlsword/btlsword.cpp:124:16: note: in
      instantiation of function template specialization
      'eosio::multi_index<4157073457596809216, eosio::sword::basicmatch,
      eosio::indexed_by<13442294247463059456,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_ready_time> >,
      eosio::indexed_by<4219197657291161600,
      eosio::const_mem_fun<eosio::sword::basicmatch, unsigned long,
      &eosio::sword::basicmatch::get_beat_num> > >::emplace<(lambda at
      /home/gyl/eosio.cdt/examples/btlsword/btlsword.cpp:124:31)>' requested
      here
      pyhtable.emplace(_self, [&](auto& a) {
               ^
/usr/local/eosio.cdt/bin/../include/eosiolib/multi_index.hpp:124:11: note: 
      template is declared here
   struct secondary_index_db_functions;

**Comment by cassej** [comment]
the same problem on branches 1.5.x and master

**Comment by ashishchandr70** [comment]
I second @cassej - having the same issue with 1.5.0 (master).

**Comment by ashishchandr70** [comment]
> when I am compiling contract file by eosio.cdt 1.4.1, I met a lot of problems of multi_index during compiling, my table has two secondary index, the struct is written as:
> 
 
 ```
     struct [[eosio::table]] basicmatch {
         name            player;
         time_point_sec  ready_time;
         uint32_t        beat_num;
 
         uint64_t  primary_key()const { return player.value; }
         **uint32_t**  get_ready_time()const { return ready_time.utc_seconds; }
         **uint32_t**  get_beat_num()const { return beat_num; }
         EOSLIB_SERIALIZE(basicmatch, (player)(ready_time)(beat_num));
      };
      typedef eosio::multi_index< "basicmatch"_n, basicmatch,
                                 indexed_by< "readytime"_n, const_mem_fun<basicmatch, 
                                 **uint32_t**, &basicmatch::get_ready_time> >,
                                 indexed_by< "beatnum"_n, const_mem_fun<basicmatch, 
                                 **uint32_t**, &basicmatch::get_beat_num> > 
                                 > basicmatchs;
 
```
 

Please refer to https://eosio.github.io/eosio.cdt/1.5.0/namespaceeosio_a47fd92719089a8609af81ee41ba33e78.md#detailed-description - uint32_t is not a supported type for a secondary index using multi-index. I think your issue may be arising from there.

**Comment by ashishchandr70** [comment]
> I second @cassej - having the same issue with 1.5.0 (master).
> 
> @larryk85

No longer an issue. The issue was in my code...returning an unsupported type using a secondary index.

**Comment by ekkis** [comment]
where is it documented what the supported types are?
