### ISSUE TITLE
Are niladic actions supported?

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#359]
I have an action:
```
[[eosio::action]]
void getfees();
```
which I call using cleos:
```
cleos push action mycontract getfees -p myaccount@active
```
but which fails with the error:

>ERROR: RequiredError: data
>Push a transaction with a single action

**does this mean I cannot declare actions without parameters?**

incidentally, even if I pass a blank argument, it doesn't work:
```
cleos push action mycontract getfees '' -p myaccount@active
```
> Error 3015014: Pack data exception
> Error Details:
> Unexpected input encountered while processing struct 'getfees'

this seems to work but it doesn't:
```
cleos push action mycontract getfees '{}' -p myaccount@active
```
> executed transaction: fe3c43a6cf8fe7d253dd1bac972a56d3c47ff909bbf11dafcd35dfbed3f88370  
> 96 bytes  254 us
>      nav.token <= nav.token::getfees           ""
> warn  2019-01-15T00:21:12.674 thread-0  main.cpp:487                  print_resuwarning: transaction executed locally, but may not be confirmed by the network yet

which I say because the implementation of my action looks like this:
```
void token::getfees()
{
    print("testing...");
}
```
and from the output one can see the test string was never printed

**Comment by heifner** [comment]
The nodoes you push the action to must have `--contracts-console` enabled.

**Comment by heifner** [comment]
Try with `cleos --print-response ...` and see if you can see the output.

**Comment by jeffreyssmith2nd** [comment]
On 1.6.2, I'm able to have empty actions, as well as actions that print.

**Comment by ekkis** [comment]
so the issue has to do with the way parameters are passed in from bash.  in the case of niladic methods, an array with an empty string seems to work:

`cleos push action mycontract getfees '[""]' -p myaccount@active`
