### ISSUE TITLE
Add more detail to eosio.cdt 1.3+ API docs

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/eosio.cdt#360]
Great work on new docs, they look much much.  

However it's missing the level of detail we had before:

![Alt text](https://monosnap.com/image/3abcykPIfbqdelKlZWBJek50uZubgm.png)

**Comment by dskvr** [comment]
The docs you have screenshotted were generated from the same annotations using the exact same method as exists on the current documentation. 

[See Here](https://eosio.github.io/eosio.cdt/1.5.0/classeosio_1_1multi__index.html)
<img width="235" alt="screen shot 2019-01-28 at 5 36 00 pm" src="https://user-images.githubusercontent.com/299465/51871011-34500e00-2323-11e9-9f1d-aa27c888f4c4.png">

I believe the reason you believe this is an issue is that our markdown generator does not include classes inline within doxygen groups, so you need to click the class to expose its methods.

See Below...
<img width="970" alt="screen shot 2019-01-28 at 5 37 07 pm" src="https://user-images.githubusercontent.com/299465/51871075-5fd2f880-2323-11e9-8275-9ade29f42d2b.png">

**Comment by gaboesquivel** [comment]
great, I created this before 1.5 docs. 
For a couple a weeks we didn't have that for 1.3 only for 1.2

**Comment by dskvr** [comment]
@gaboesquivel Thanks!
