### ISSUE TITLE
'eosio-init -p xxx' should camelize argument when make a contract skeleton

### ISSUE THREAD

**Issue by drunkhacker** [EOSIO/eosio.cdt#369]
[This line](https://github.com/EOSIO/eosio.cdt/blob/master/tools/init/eosio-init.cpp#L59) uses the argument passed from `eosio-init -p` without sanitizing or such. If I pass a Kebab case string e.g., 'hello-world', this will create `CONTRACT hello-world` which is not valid name for a class.

It'd be good to camelize the input string or prevent the string cannot be used as identifier in C++.

**Comment by jeffreyssmith2nd** [comment]
This was handled in #370, closing.
