### ISSUE TITLE
Debian Package Install url error

### ISSUE THREAD

**Issue by EnjoyAndroid** [EOSIO/eosio.cdt#374]
Debian Package Install url error, the correct url is:

$ wget https://github.com/eosio/eosio.cdt/releases/download/v1.5.0/eosio.cdt_1.5.0-1_amd64.deb
$ sudo apt install ./eosio.cdt_1.5.0-1_amd64.deb

**Comment by jeffreyssmith2nd** [comment]
Readme has been updated with the correct download links.
