### ISSUE TITLE
ripemd160 function doesn't work?

### ISSUE THREAD

**Issue by k26dr** [EOSIO/eosio.cdt#380]
The `ripemd160( const char* data, uint32_t length )` function in crypto.hpp (CDT 1.4) returns nonsensical results. When given an input it returns a hash with 4 null bytes in the end. Importing an external ripemd160 library produces proper results, so I think the CDT function is broken. Has anybody verified that the CDT function works?

**Comment by k26dr** [comment]
Context: I'm caculating a checksum on a public key to convert it to a string. A commit with working code is here: 

https://github.com/eosdac/eosio.lost/pull/3/commits/702f7becc3cc0e6d420596008fe88c164a6bb9e6

Using the CDT version the hex value of the hash of `0389fd66e64abee74e0dc8fd88cdeb1d3fa24076b5cdd4e7d0357ec30d9203d768` (the hashed public key byte encoding for EOS7t1J6fMPeMSDSMhYfeKhADpmvz8ogbNUZdj6hkQwgsgsWcDxXv)  is `5c935537d824dd0d48dd1824ede9484800000000`. 

Using the external library in that commit, the value is `4848e9ed2418dd480ddd24d83755935ce87ccdfd`,

**Comment by k26dr** [comment]
Here's the code used by both versions:

    // add ripemd160 checksum to end of key
    uint8_t hash_output[20];
    ripemd160((uint8_t *)pkeycopy.data.begin(), 33, hash_output);
    memcpy(to_encode + 33, hash_output, 4);

    // CDT ripemd160
    checksum160 cdt_output = ripemd160((const char *)pkeycopy.data.begin(), 33);

**Comment by larryk85** [comment]
I think this is an issue with how you are printing the checksum160, because when I use EOS7t1J6fMPeMSDSMhYfeKhADpmvz8ogbNUZdj6hkQwgsgsWcDxXv as the pubkey and then use ripemd160 and print via eosio::print("Checksum : ", cdt_output, "\n"); or eosio::print_f("Checksum : %\n", cdt_output); I get the same result that I expect to get, which is 4848e9ed2418dd480ddd24d83755935ce87ccdfd.  How are you printing the checksum?

**Comment by k26dr** [comment]
`print(bytetohex((unsigned char *)cdt_output.data(), 20).c_str())`

you're right, sorry, I didn't realize I could just print it straight out. that print method worked for a series of other public and private keys, so I figured it would work here.

**Comment by k26dr** [comment]
does `std::array` not store it's bytes contiguously?
