### ISSUE TITLE
How can I add compiler flag options?

### ISSUE THREAD

**Issue by newro** [EOSIO/eosio.cdt#393]
I'm using on eosio.cdt 1.5.0-rc2 for rex test.
When I tried to -D option for compiler option, It seemed to be not work.
`$> eosio-cpp -DDEFINEKEY=DEFINEVALUE -o contract.wasm contract.cpp -abigen`
I was using EOSIOCPP_CFLAGS environment variable on previous eosiocpp compile script.
`$> export EOSIOCPP_CFLAGS="-DDEFINEKEY=DEFINEVALUE" eosiocpp -o contract.wast contract.cpp`

How can I add compiler flag options with new eosio-cpp version?
-D option and envrionment variable seems to be not work.

**Comment by larryk85** [comment]
This should work as is.  I was able to use -D perfectly well with eosio-cpp. Also, -D has nothing to do with environment variables, they are preprocessor defines (the same as `#define` in your source code).

**Comment by thedeposbank** [comment]
I confirm that. My case:
```
eosio-cpp -DBITCOIN_TESTNET=true -o new.token.wasm new.token.cpp -abigen
/home/andrey/contracts/stablecoin/new.token/new.token.cpp:200:31: error: use of undeclared identifier 'BITCOIN_TESTNET'
                        validate_btc_address(memo, BITCOIN_TESTNET);
                                                   ^
```
Installed from package eosio.cdt-1.5.0-1.x86_64 on Fedora 29

**Comment by ekkis** [comment]
I had a similar problem as described here: https://eosio.stackexchange.com/questions/4521/defining-symbols-for-a-contract-at-compile-time-how/4522#4522

try `eosio-cpp -DBITCOIN_TESTNET=true -E -dD t.cpp  -o - |grep BITCOIN_TESTNET` and see if it generates the required #define
