### ISSUE TITLE
Unable to parse a string containing a float using std::stof

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#404]
this page contains a simple of example of how to do it: http://www.cplusplus.com/reference/string/stof/ so my code looks like this:
```
void token::test()
{
        std::string s("686.97");
        float limit = std::stof(s);
        printf("limit [%f]\n", limit);
}
```
which compiles fine but pukes on running:

> Error 3070002: Runtime Error Processing WASM
> Error Details:
> wabt execution failure (out of bounds memory access)
> pending console output: 

what is the accepted way of parsing a string in a contract?

**Comment by ekkis** [comment]
I've since found that the `atoi` function seems available but `atof` isn't, the latter typically included in stdlib, which I can't include in contracts.  help?

**Comment by ekkis** [comment]
I also get an out of bounds error from `std::strtof`

**Comment by larryk85** [comment]
Hello @ekkis, 

As for smart contract development, it is bad form to do string manipulations/conversions.  These will eat up cpu and ram (they typically generate a lot of functions).  Since this is the case, getting proper support for these functions has been very low priority.  Especially for tests/debugging this functionality is very useful is and is on my radar.

**Comment by ekkis** [comment]
the standard implementation of the `transfer` method accepts a memorandum, which is a string.  if I add parameters to my implementation it will not be supported by the vast majority of clients.  therefore the memo is a good place to encode additional information about a transaction.  in my case, I want to specify that a transfer a user makes to a specific address will be treated as a buy order, in which case the memo field can include information like a limit `limit=105.20`, for which I need to parse the string

given that `atoi` is supported I had to write my own implementation of this functionality like so:
```
    float token::stof(std::string s, float def)
    {   
        if (s == "") return def;
        std::size_t i = s.find(".");
        int digits = s.length() - i - 1;
        s.erase(i, 1); 
        return atoi(s.c_str()) / pow(10, digits);
    }  
```
frankly it's madness that there's no support for the most basic of functionality in EOS, but if you have an alternative approach to my dilemma I'm all ears

**Comment by swatanabe-b1** [comment]
https://github.com/EOSIO/musl/pull/10
