### ISSUE TITLE
How can I just simply build eos-abigen (or other single tool) for EOS?

### ISSUE THREAD

**Issue by lyp830414** [EOSIO/eosio.cdt#417]
How can I just simply build eos-abigen (or other single tool) for EOS?

If using ./build.sh , it takes too long .. 
Are there any fast and simply way to only build tools like eos-abigen under eos tools directory?

**Comment by larryk85** [comment]
No, as it uses libraries built for the compiler.  So, barring building the libraries which is a short amount of time, not much can be done for that.  We also have binary packages for some Linux distros and Mac OS X, do you need to build from source?

**Comment by lyp830414** [comment]
Yes, I want to do some printings and simple code experience on those tools' codes, and want to compile them separately... Are there some easier way to compile those tools by some command or do some easy adaption on cmake / make files or any other way ?

**Comment by jeffreyssmith2nd** [comment]
This is currently a feature we do not intend to support. `tools` has a hard dependency on `eosio_llvm`, which is what takes the significant amount of time.
