### ISSUE TITLE
hidden transaction data

### ISSUE THREAD

**Issue by Acmefocus** [EOSIO/eosio.cdt#421]
Hello,  I'd like to know if the transaction amount can be hidden in the online EOS smart contract. Do you plan to develop hidden transaction data later? Our application wants to hide the transaction amount. Our solution is to use homomorphic addition in smart contracts. But when the seck256k1 library can not be directly referenced in the contracts, can you solve the problem?

**Comment by jeffreyssmith2nd** [comment]
This is not a feature we currently support. This also would be change eos side, so if desired a feature request can be filed there.
