### ISSUE TITLE
I use inline action to transfer users eos to my contract, but there is a permission error,please help

### ISSUE THREAD

**Issue by chain78** [EOSIO/eosio.cdt#428]
here is code:
    action(permission_level{from, "active"_n}, "eosio.token"_n, "transfer"_n,
           std::make_tuple(from, _self, quantity, memo)).send();

I add code permission as below:
       cleos set account permission addressbook active --add-code

error:
error 2019-02-26T23:49:48.913 thread-0  http_plugin.cpp:580           handle_exception     ] FC Exception encountered while processing chain.push_transaction
debug 2019-02-26T23:49:48.914 thread-0  http_plugin.cpp:581           handle_exception     ] Exception Details: 3090003 unsatisfied_authorization: Provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"tester","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"addressbook","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
    {"auth":{"actor":"tester","permission":"active"},"provided_delay":0,"provided_permissions":[{"actor":"addressbook","permission":"eosio.code"}],"provided_keys":[],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:520 check_authorization
pending console output: inline action
    {"console":"inline action"}
    thread-0  apply_context.cpp:72 exec_one

**Comment by nirdesh27** [comment]
You need to add permission of eosio.code to your contract just like this:
`cleos set account permission yourcontract active '{"threshold": 1,"keys": [{"key": "yourcontract public active key","weight": 1}],"accounts": [{"permission":{"actor":"yourcontract","permission":"eosio.code"},"weight":1}]}' owner -p yourcontract@active`

**Comment by nirdesh27** [comment]
But my question here is that if some one other than contract owner wants to send EOS through your contract does he need the permission as well, So every time new user comes he needs new permissions to be granted. Or this thing is hangled by eosjs?

**Comment by chain78** [comment]
I resolve this problem.  I refer this project, the project site :https://github.com/InfiniverseAR/infiniverse-eos

eosjs can make a transcation as：opendeposit  ->   eos token transfer ->   action

the flow as:  opendeposit ->  eos token transfer -> depositeos -> action -> deduct_eos_deposit -> action end
