### ISSUE TITLE
eosio.cdt string

### ISSUE THREAD

**Issue by johndebord** [EOSIO/eosio.cdt#440]
**Environment (Ubuntu  16.04LTS):**
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
Stepping:              3
CPU MHz:               2476.433
CPU max MHz:           3800.0000
CPU min MHz:           800.0000
BogoMIPS:              5587.26
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
```

Given a minimal smart contract (`con.cpp`) with a no-op action:
```
#include <eosio/eosio.hpp>

class [[eosio::contract]] con : public eosio::contract {
public:
    using contract::contract;
    [[eosio::action]] void act()
    { }
};

EOSIO_DISPATCH(con, (act))
```

The size of the said contract comes out out to be:
```
~/con $ ll
total 1
-rwxrwxr-x   1 i              i        743 2019-03-06 13:37 a.out
-rw-rw-r--   1 i              i        202 2019-03-06 13:37 con.cpp
```

Given a minimal smart contract whilst introducing a `std::string`:
```
#include <eosio/eosio.hpp>

class [[eosio::contract]] con : public eosio::contract {
public:
    using contract::contract;
    [[eosio::action]] void act(const std::string& s)
    { }
};

EOSIO_DISPATCH(con, (act))
```

The size of the contract is now:
```
~/con $ ll
total 4
-rwxrwxr-x   1 i              i        3531 2019-03-06 13:46 a.out
-rw-rw-r--   1 i              i         222 2019-03-06 13:46 con.cpp
```
As is shown, this comes out to an extra 2788 bytes of code-bloat.

This poses to be a problem if a developer were to have many trivial/small smart contracts which utilize a `std::string`. But if the smart contract is already larger in nature, then this effect is minimal.

Therefore a new string type shall be developed for size optimization.
This new string class will implement the small string optimization and provide the normal interface that is provided by `std::string` but at a fraction of the memory footprint.

Development can be tracked in branch: [`cdt-string`;](https://github.com/EOSIO/eosio.cdt/tree/cdt-string) `eosio.cdt/libraries/eosiolib/string_impl/`

- [x] Preliminary research
- [x] Skeleton implementation
- [x] Production-ready

**Comment by matt-block** [comment]
Unless I missed it in the source code, there is no [`string::find`](http://www.cplusplus.com/reference/string/string/find/), correct?
