### ISSUE TITLE
assertion failure with message: cannot pass end iterator to modify

### ISSUE THREAD

**Issue by RishalEP** [EOSIO/eosio.cdt#447]

**Comment by RishalEP** [comment]
trustcompanies tablec( _self,issuer.value );
    auto iterator = tablec.find(issuer.value);
                        tablec.modify( iterator, issuer, [&]( auto& s ) {
                        s.value = maximum_supply;
                        });

even if the iterator not at endpoint the error remains... why

**Comment by yousq** [comment]
hi， I meet the same problem with you, have you  resolved this problem?

**Comment by RishalEP** [comment]
yes... It was because i was using the wrong table scope. make sure that the table name and scope you use is correct.

**Comment by nightshade777** [comment]
How did you correct the scope
