### ISSUE TITLE
Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?

### ISSUE THREAD

**Issue by chetanmoradiya** [EOSIO/eosio.cdt#454]
I am getting Error like "**Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?**" when i am trying to create two below test accounts
cleos create account eosio bob EOS8hBfm..........eptTAE4AmqS 
cleos create account eosio alice EOS8hBfm..........eptTAE4AmqS

I am a new in eosio and following tutorial provided by eosio. Help me here to solve this issue.

**Comment by swarnalathakuppusami** [comment]
even iam facing the same problem ... has anybody resolved it

**Comment by jeffreyssmith2nd** [comment]
This is not a CDT issue. The [EOSIO Stack Exchange](https://eosio.stackexchange.com/) or the [Developers Telegram](https://t.me/joinchat/EaEnSUPktgfoI-XPfMYtcQ) would be the right place to ask this.

**Comment by najamsk** [comment]
> This is not a CDT issue. The [EOSIO Stack Exchange](https://eosio.stackexchange.com/) or the [Developers Telegram](https://t.me/joinchat/EaEnSUPktgfoI-XPfMYtcQ) would be the right place to ask this.

dont bother about telegram. i join this group posted their documentation link that was removed automatically and then i think i get banned.  best community support for new users figuring out development with EOS.
