### ISSUE TITLE
`target_ricardian_directory` macro fails to find target

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eosio.cdt#455]
``` cmake
   macro (target_ricardian_directory TARGET DIR)
      target_compile_options( ${TARGET} PUBLIC -R${DIR} )
      file(GLOB contracts ${DIR}/*.contracts.md ${DIR}/*.clauses.md)
      add_dependencies( ${TARGET} ${contracts} )
   endmacro()
```

This macro calls `add_dependencies` to add ricardian files to the contract, but cmake complains non-existence of target. `add_dependencies` creates a relationship between top-level targets, but contract is an external project, so it seems that contract is not visible from top-level execution. Without cmake version, contract is built regardless of this error, but when `cmake_minimum_required` is added with the latest version, build process is aborted.

**Comment by swatanabe-b1** [comment]
Files are not targets in CMake and do not work with add_dependencies.

**Comment by jeffreyssmith2nd** [comment]
Handled by #748
