### ISSUE TITLE
eosio-cpp Issue with CDT 1.5.0 and 1.6.0-rc2 - error: ios.obj

### ISSUE THREAD

**Issue by riccardopersiani** [EOSIO/eosio.cdt#458]
### Description

Compiling a contract, using the `eosio-cpp` compiler, with both *eosio.cdt* **1.5.0** and **1.6.0-rc2**, with the following command:

```bash
eosio-cpp hello.cpp -o hello.wasm -abigen
```

The following **error** shows up:

```javascript
/usr/.../bin/wasm-ld: error: ios.obj: undefined symbol: std::uncaught_exception()
```

Seems to be an issue related with *streams; but, there is not any breaking change documented regarding it. 

### 💥  Possible Causes

The contract uses:
* the library `<sstream>`
* `std::istream`
* `std::ostream` 
* `std::ios_base::failbit`

### What is working

*EDITED*

Using the `eosio-cpp` compiler with the *eosio.cdt* **1.4.x**, the compilation of the contract succeeds.

**Comment by jeffreyssmith2nd** [comment]
If this is still failing for you on 1.6.x, can you share the contract code? It will be hard to debug without more information.

**Comment by lolgolflol** [comment]
Same me.

```
#include <sstream>
```
and Just use std::istringstream somewhere in code.

**Comment by jeffreyssmith2nd** [comment]
This actually seems to be related to issue #186, so I'm going to close this in favor of the older issue.
