### ISSUE TITLE
How to get current_time/now in C++ in 1.6

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eosio.cdt#470]
As `system.h` [header will be removed when using C++ in `v1.7`](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h#L8), I'd like to use an alternative to `now()` and `current_time()` that is in a `.hpp` header.

Even when importing `system.hpp` now, it cannot find these functions:

```
#include <eosio/system.hpp>
error: use of undeclared identifier 'now'; did you mean 'new'?
```

**Comment by duyluong1994** [comment]
From eosio.cdt v1.6 onwards
You have to #include <eosio/system.hpp> and then you can use:

eosio::current_time_point
eosio::current_block_time
to cast from time_point to uint32_t u can use like:
eosio::current_time_point().sec_since_epoch();

**Comment by godmar** [comment]
It is unclear what returning `uint32_t` means. Is the expectation that EOS will have been phased out by the year 2038?  Or does `sec_since_epoch` return a mod 2^32 of the actual time? If so, it seems an error prone API to include.

I checked the [documentation](https://eosio.github.io/eosio.cdt/latest/classeosio_1_1time__point) already, but it didn't clarify.
