### ISSUE TITLE
Compilation warnings & errors using CDT 1.6.1

### ISSUE THREAD

**Issue by ashishchandr70** [EOSIO/eosio.cdt#482]
System Info:

<pre>Description:	Ubuntu 18.04.2 LTS
Release:	18.04
</pre>

I had been using CDT 1.5 until today, when I upgraded to v1.6.1.

After adjusting for the fact that the CDT now installs in /usr/opt instead of /usr/local, I was able to build my contract wasm and abi files, but got these warnings (posting only a few)

<pre>In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/transaction.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/transaction.h:8:2: </b><font color="#AD7FA8"><b>warning: </b></font><b>&quot;&lt;eosiolib/transaction.h&gt; is deprecated use &lt;eosio/transaction.h&gt;. If you</b>
<b>      are using C++ the .h header files will be removed from inclusion entirely in v1.7.0&quot; [-W#warnings]</b>
#warning &quot;&lt;eosiolib/transaction.h&gt; is deprecated use &lt;eosio/transaction.h&gt;. If you are using C++ the .h header files will be removed from inclu...
<font color="#8AE234"><b> ^</b></font>
In file included from /tmp/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/transaction.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/serialize.hpp:7:2: </b><font color="#AD7FA8"><b>warning: </b></font><b>&quot;&lt;eosiolib/serialize.hpp&gt; is deprecated use &lt;eosio/serialize.hpp&gt;&quot;</b>
<b>      [-W#warnings]</b>
#warning &quot;&lt;eosiolib/serialize.hpp&gt; is deprecated use &lt;eosio/serialize.hpp&gt;&quot;
<font color="#8AE234"><b> ^</b></font>
In file included from /tmp/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/transaction.hpp:14:2: </b><font color="#AD7FA8"><b>warning: </b></font><b>&quot;&lt;eosiolib/transaction.hpp&gt; is deprecated use &lt;eosio/transaction.hpp&gt;&quot;</b>
<b>      [-W#warnings]</b>
#warning &quot;&lt;eosiolib/transaction.hpp&gt; is deprecated use &lt;eosio/transaction.hpp&gt;&quot;
</pre>

Here are the headers I have included in my contract's hpp:

```
#pragma once

#include <eosiolib/eosio.hpp>
#include <eosiolib/crypto.h>
#include <string>
#include <utility>
#include <vector>
#include <algorithm>
#include <iterator>
#include <list>
#include <chrono>
#include <time.h>
#include <eosiolib/asset.hpp>
#include <eosiolib/time.hpp>
#include <eosiolib/privileged.hpp>
//#include <eosio/native/intrinsics_def.hpp>
#include <eosio.system/eosio.system.hpp>
#include <eosiolib/transaction.hpp>
````

I then tried to switch over just one of the files, transaction.hpp, over to the new eosio library, just to see if the warning goes away.

Per my path, transaction.hpp is in two locations:

<pre>/usr/opt/eosio.cdt/1.6.1/include/eosiolib/transaction.hpp
/usr/opt/eosio.cdt/1.6.1/include/eosiolib/contracts/eosio/transaction.hpp</pre>

So, I added the /usr/opt/eosio.cdt/1.6.1/include/eosiolib/contracts path to my cmake includes and changed the include directive to

`#include <eosio/transaction.hpp>`

And it immediately broke. It appears that there are a lot of internal header references pointing to <eosiolib/XYZ.hpp> type includes.

Here is the entire log from the build attempt:

<pre>In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:41:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, const char* msg) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:31:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, const char* msg) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:57:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, const std::string&amp; msg) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:47:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, const std::string&amp; msg) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:73:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, std::string&amp;&amp; msg) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:63:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, std::string&amp;&amp; msg) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:90:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, const char* msg, size_t n) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:80:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, const char* msg, size_t n) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:107:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, const std::string&amp; msg, size_t n) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:97:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, const std::string&amp; msg, size_t n) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:6:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/check.hpp:123:16: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;check&apos;</b>
   inline void check(bool pred, uint64_t code) {
<font color="#8AE234"><b>               ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/system.hpp:113:16: </b><font color="#555753"><b>note: </b></font>previous definition is here
   inline void check(bool pred, uint64_t code) {
<font color="#8AE234"><b>               ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:41:7: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;datastream&apos;</b>
class datastream {
<font color="#8AE234"><b>      ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:44:7: </b><font color="#555753"><b>note: </b></font>previous definition is here
class datastream {
<font color="#8AE234"><b>      ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:185:7: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of</b>
<b>      &apos;datastream&lt;unsigned int&gt;&apos;</b>
class datastream&lt;size_t&gt; {
<font color="#8AE234"><b>      ^~~~~~~~~~~~~~~~~~</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:189:7: </b><font color="#555753"><b>note: </b></font>previous definition is here
class datastream&lt;size_t&gt; {
<font color="#8AE234"><b>      ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:262:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&lt;&lt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::list&lt;T&gt;&amp; l) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:276:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::list&lt;T&gt;&amp; l) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:278:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&gt;&gt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::list&lt;T&gt;&amp; l) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:293:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::list&lt;T&gt;&amp; l) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:296:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&lt;&lt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::deque&lt;T&gt;&amp; d) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:312:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::deque&lt;T&gt;&amp; d) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:312:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&gt;&gt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::deque&lt;T&gt;&amp; d) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:329:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::deque&lt;T&gt;&amp; d) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:330:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&lt;&lt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::variant&lt;Ts...&gt;&amp; var) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:348:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::variant&lt;Ts...&gt;&amp; var) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:338:6: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;deserialize&apos;</b>
void deserialize(datastream&lt;Stream&gt;&amp; ds, std::variant&lt;Ts...&gt;&amp; var, int i) {
<font color="#8AE234"><b>     ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:356:6: </b><font color="#555753"><b>note: </b></font>previous definition is here
void deserialize(datastream&lt;Stream&gt;&amp; ds, std::variant&lt;Ts...&gt;&amp; var, int i) {
<font color="#8AE234"><b>     ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:361:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&gt;&gt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::variant&lt;Ts...&gt;&amp; var) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:380:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::variant&lt;Ts...&gt;&amp; var) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:378:13: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&lt;&lt;&apos;</b>
DataStream&amp; operator&lt;&lt;( DataStream&amp; ds, const std::pair&lt;T1, T2&gt;&amp; t ) {
<font color="#8AE234"><b>            ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:398:13: </b><font color="#555753"><b>note: </b></font>previous definition is here
DataStream&amp; operator&lt;&lt;( DataStream&amp; ds, const std::pair&lt;T1, T2&gt;&amp; t ) {
<font color="#8AE234"><b>            ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:394:13: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&gt;&gt;&apos;</b>
DataStream&amp; operator&gt;&gt;( DataStream&amp; ds, std::pair&lt;T1, T2&gt;&amp; t ) {
<font color="#8AE234"><b>            ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:415:13: </b><font color="#555753"><b>note: </b></font>previous definition is here
DataStream&amp; operator&gt;&gt;( DataStream&amp; ds, std::pair&lt;T1, T2&gt;&amp; t ) {
<font color="#8AE234"><b>            ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:412:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&lt;&lt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::optional&lt;T&gt;&amp; opt) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:434:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&lt;&lt;(datastream&lt;Stream&gt;&amp; ds, const std::optional&lt;T&gt;&amp; opt) {
<font color="#8AE234"><b>                           ^</b></font>
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:22:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/transaction.hpp:6:
In file included from /usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/action.hpp:9:
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/contracts/eosio/../../core/eosio/datastream.hpp:429:28: </b><font color="#EF2929"><b>error: </b></font><b>redefinition of &apos;operator&gt;&gt;&apos;</b>
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::optional&lt;T&gt;&amp; opt) {
<font color="#8AE234"><b>                           ^</b></font>
<b>/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/datastream.hpp:452:28: </b><font color="#555753"><b>note: </b></font>previous definition is here
inline datastream&lt;Stream&gt;&amp; operator&gt;&gt;(datastream&lt;Stream&gt;&amp; ds, std::optional&lt;T&gt;&amp; opt) {
<font color="#8AE234"><b>                           ^</b></font>
<font color="#EF2929"><b>fatal error: </b></font>too many errors emitted, stopping now [-ferror-limit=]
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action &lt;addprod&gt; does not have a ricardian contract
Warning, action &lt;deleteprod&gt; does not have a ricardian contract
Warning, action &lt;setdelay&gt; does not have a ricardian contract
Warning, action &lt;setthrhold&gt; does not have a ricardian contract
Warning, action &lt;castvote&gt; does not have a ricardian contract
Warning, action &lt;addprod&gt; does not have a ricardian contract
Warning, action &lt;deleteprod&gt; does not have a ricardian contract
Warning, action &lt;setdelay&gt; does not have a ricardian contract
Warning, action &lt;setthrhold&gt; does not have a ricardian contract
Warning, action &lt;castvote&gt; does not have a ricardian contract
20 errors generated.
Error while processing /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp.
abigen error
CMakeFiles/smartproxy.dir/build.make:62: recipe for target &apos;CMakeFiles/smartproxy.dir/smartproxy.obj&apos; failed
make[5]: *** [CMakeFiles/smartproxy.dir/smartproxy.obj] Error 255
CMakeFiles/Makefile2:67: recipe for target &apos;CMakeFiles/smartproxy.dir/all&apos; failed
make[4]: *** [CMakeFiles/smartproxy.dir/all] Error 2
Makefile:83: recipe for target &apos;all&apos; failed
make[3]: *** [all] Error 2
CMakeFiles/smartproxy.dir/build.make:111: recipe for target &apos;smartproxy-prefix/src/smartproxy-stamp/smartproxy-build&apos; failed
make[2]: *** [smartproxy-prefix/src/smartproxy-stamp/smartproxy-build] Error 2
CMakeFiles/Makefile2:67: recipe for target &apos;CMakeFiles/smartproxy.dir/all&apos; failed
make[1]: *** [CMakeFiles/smartproxy.dir/all] Error 2
Makefile:83: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
Sat Mar 30 20:05:39 CDT 2019 Errors executing make.
</pre>

**Comment by larryk85** [comment]
It shouldn't be installing to /usr/opt for one thing, can you supply me the list of steps you used to install cdt?  For the other failures, these are listed in the migration guide from 1.5.x to 1.6.x.  The old header files are quarantined to eosiolib path and the new headers use eosio.  This was done to not immediately break compilation for your contract, but once you change one include to use the new path you will have to change all of them.  The new `library` should have no reference to eosiolib, so it appears that your contract is still including things from eosiolib.

**Comment by ashishchandr70** [comment]
Steps to install 1.6.1 CDT:

1. Run uninstall.sh from the directory where I had earlier clone 1.5
2. wget https://github.com/eosio/eosio.cdt/releases/download/v1.6.1/eosio.cdt_1.6.1-1_amd64.deb
3. sudo apt install ./eosio.cdt_1.6.1-1_amd64.deb

Also, 

> For the other failures, these are listed in the migration guide from 1.5.x to 1.6.x

Can you provide this link? I could not find it on the readme.md on the main CDT page in GH.

**Comment by smlu** [comment]
Note, try changing all occurrences of `eosiolib` include paths to `eosio`. The redefinition error you're getting is probably due to including different header files which contain the same function definitions.

Specifically,  function `void check(bool pred, const char* msg)` is defined in header files `eosiolib/system.hpp` and `eosio/check.hpp`.  This is due to compatibility issues between cdt <= 1.5 and cdt >= 1.6. 
When you include `eosiolib/eosio.hpp` it includes `eosiolib/system.hpp` via `eosiolib/action.hpp` -> `eosiolib/action.h`. And if you include `eosio/transaction.hpp` it'll also include `eosio/check.hpp`. Compiler then tries to define `check` function from both files since it cannot distinguishes between them (header guards won't prevent this) and emits redefinition error when it encounters the second definition.

**Comment by ashishchandr70** [comment]
Thanks @smlu. I will try this approach and post here as to what happened.

**Comment by ashishchandr70** [comment]
Hi @smlu @larryk85 I think the issue is compounded by the fact that I am also using eosio.system.hpp for including system contracts. 

This is just an extract of the errors being thrown (not the entire error log)

```
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:21:
/home/passwordis1234/eosio.contracts/eosio.system/include/eosio.system/eosio.system.hpp:247:21: error: unknown type name 'unsigned_int'; did you mean
      'eosio::unsigned_int'?
         void init( unsigned_int version, symbol core );
                    ^~~~~~~~~~~~
                    eosio::unsigned_int
/usr/opt/eosio.cdt/1.6.1/bin/../include/eosiolib/core/eosio/varint.hpp:22:11: note: 'eosio::unsigned_int' declared here
   struct unsigned_int {
          ^
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.cpp:6:
In file included from /home/passwordis1234/eosio_dev/smartproxy/contracts/smartproxy/smartproxy.hpp:21:
/home/passwordis1234/eosio.contracts/eosio.system/include/eosio.system/eosio.system.hpp:366:13: error: use of undeclared identifier 'eosio_assert'; did
      you mean 'eosio::internal_use_do_not_use::eosio_assert'?
            eosio_assert(itr != rm.end(), "system contract must first be initialized");
            ^~~~~~~~~~~~
            eosio::internal_use_do_not_use::eosio_assert

```

I will need to upgrade my system contracts' codebase to 1.6.0.
