### ISSUE TITLE
Issue while compiling smart contract - eosio.cdt v1.6.1

### ISSUE THREAD

**Issue by stone89son** [EOSIO/eosio.cdt#489]
Enviroment: Ubuntu 18
Smart Contract Compiler:  eosio.cdt v1.6.1
-I compiled with  eosio.cdt v1.5 successful, but I compile smart contract with eosio.cdt v1.6.1 to error message.
-file jdex.hpp and jdex.cpp in path:  ~/xxx/v.0.02

>  ~/xxx/v.0.02$ eosio-cpp -o jdex.wasm jdex.cpp --abigen
>     Warning, empty ricardian clause file
>     Warning, empty ricardian clause file
>     Warning, action <hello> does not have a ricardian contract
>     Warning, action <revokeorder> does not have a ricardian contract
>     Warning, action <hello> does not have a ricardian contract
>     Warning, action <revokeorder> does not have a ricardian contract
>     /tmp/jdex.cpp:1:10: fatal error: './jdex.hpp' file not found
>     #include "./jdex.hpp"
>              ^~~~~~~~~~~~
>     1 error generated.
>     /usr/opt/eosio.cdt/1.6.1/bin/wasm-ld: error: cannot open /tmp/jdex.cpp.o: No such file or directory

**Comment by conr2d** [comment]
This is related to #472.
You can resolve by add `-I.` in your command:
``` console
$ eosio-cpp -o jdex.wasm jdex.cpp --abigen -I.
```

**Comment by stone89son** [comment]
@conr2d , thank you.
