### ISSUE TITLE
compile failed in 1.6.1 when using [[eosio::on_notify("*::transfer")]]

### ISSUE THREAD

**Issue by darkdong** [EOSIO/eosio.cdt#497]
error: else expression without matching if
000035b: error: OnElseExpr callback failed

but if I use [[eosio::on_notify("eosio.token::transfer")]], compilation is success

**Comment by cc32d9** [comment]
got the same error:   https://github.com/eos-geneva/escrowescrow/tree/cdt_1.6

**Comment by darkdong** [comment]
compile _post_dispatch_ shows the same error, but _pre_dispatch_ ok.

**Comment by slyon** [comment]
@cc32d9 what was your solution to the problem?

**Comment by cc32d9** [comment]
> @cc32d9 what was your solution to the problem?

well I keep the old version of the contract under CDT 1.5. Sitting pretty, waiting for it to resolve by itself :)

**Comment by slyon** [comment]
I see ;-)

I found another work around, by implementing a dummy action, to satisfy the compiler:
https://github.com/slyon/signup/commit/3ed561fe0a39379b9d74a3e7250da25eb515d634#diff-fec48f310f6df993532e742d7fec6b2aR28

**Comment by larryk85** [comment]
There is a fix for this and a few other fixes in branch release_1.6.x_fixes, but yeah if you create another "dummy" notification with a non wildcard ("*") specifier that also works around the issue.

**Comment by cc32d9** [comment]
@larryk85 thanks for letting us know. I'm not in a hurry, will wait for a release

**Comment by pkuphy** [comment]
Workaround in detail:

* `hello.hpp`
```cpp
#include <eosio/eosio.hpp>
#include <eosio/asset.hpp>

using namespace eosio;
using namespace std;

CONTRACT hello : public contract {
public:
    using contract::contract;

    ACTION hi( name nm );

    using hi_action = action_wrapper<"hi"_n, &hello::hi>;

    [[eosio::on_notify("dummy::dummy")]]
    void dummy();

    [[eosio::on_notify("*::transfer")]]
    void transfer_handler(name from, name to, const asset &quantity, string memo);

};
```

* `hello.cpp`
```cpp
#include "hello.hpp"

ACTION hello::hi( name nm ) {
   /* fill in action body */
   print_f("Name : %\n",nm);
}

void hello::dummy() {print("DUMMY");}

void hello::transfer_handler(name from, name to, const asset &quantity, string memo) {
    print_f("Name : %\n",from);
}
```

As @larryk85 mentioned:
> you create another "dummy" notification with a non wildcard ("*") specifier

**Comment by AaronZgl** [comment]
You have to specify a special account before using the “*“.
if you want to use `[[eosio::on_notify("*::${action}")]]`, 
you have to use  `[[eosio::on_notify("${account}::${action}")]]` before that.
for example:
```
 [[eosio::on_notify("my_account::notify_action")]]
 void on_notify_self(){ print("This is a notice from myself."); }

 [[eosio::on_notify("*::notify_action")]]
 void on_notify_other(){ print("This is a notice from someone else."); }
```
the special account like `if` and the * like `else`.

**Comment by jeffreyssmith2nd** [comment]
This has been fixed in 1.6.2. You can see an example using the following code

```
#include <eosio/eosio.hpp>
#include <eosio/asset.hpp>

using namespace eosio;
using namespace std;

CONTRACT hello : public contract {
public:
    using contract::contract;

    ACTION hi( name nm ) {
       /* fill in action body */
       print_f("Name : %\n",nm);
    }

    [[eosio::on_notify("*::transfer")]]
    void transfer_handler(name from, name to, const asset &quantity, string memo) {
        print_f("Name : %\n",from);
    }

};
```

**Comment by vikas-sawant-rwaltz** [comment]
If you are using **EOSIO_DISPATCH** with **ACTION** keyword, 
then replace **ACTION** keyword with **[[eosio::action]] void** from your .hpp file and remove **EOSIO_DISPATCH** from your .cpp file of smart contract.

As **EOSIO_DISPATCH** blocks **eosio::on_notify**.

Please closely check eosio.token contract you will get how use.
[https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.token][1]


  [1]: https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.token

**Comment by Civik1** [comment]
https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.token
Https://womplay. io/eos/honeycv1.ftw
