### ISSUE TITLE
where is  Differences between Version 1.2.x and Version 1.3.x

### ISSUE THREAD

**Issue by treasersimplifies** [EOSIO/eosio.cdt#503]
In README.md: 
## Important !
> Please read the **Differences between Version 1.2.x and Version 1.3.x** section of this readme.

so where is it ???

**Comment by larryk85** [comment]
[Upgrading guides](https://eosio.github.io/eosio.cdt/1.6.0/upgrading). Thanks for bringing this to my attention, we will add this link to the readme with the next release.

**Comment by jeffreyssmith2nd** [comment]
Readme updated with the link to the upgrading guide.

**Comment by stivens13** [comment]
All pages that contain text "Differences between Version 1.2.x and Version 1.3.x" either don't have a hyperlink (https://eosio.github.io/eosio.cdt/latest and https://github.com/EOSIO/eosio.cdt/blob/master/README.md). The link above from @larryk85 is an empty page (tested in Chrome and Safari, including Incognito mode).

**Comment by jeffreyssmith2nd** [comment]
Good catch, the README changes haven't propagated to master yet but the link needs to be updated again due to a restructuring of the documentation site.

Here is the correct link to see the upgrading guide https://eosio.github.io/eosio.cdt/latest/upgrading/1.2-to-1.3
