### ISSUE TITLE
undefined symbol: __floatuntitf

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eosio.cdt#506]
struct table field defined:
        long double sell() const { 
            if(direction == ORDER_SELL){
                return (long double)0;
            }else{
                auto m = (uint128_t)pair << 64 | (uint64_t)price.amount;
                return static_cast<long double>(m);
            }
        }
cmake compiled errors:
/usr/local/Cellar/eosio.cdt/1.6.1/opt/eosio.cdt/bin/wasm-ld: error: CMakeFiles/***.wasm.dir/src/dex.cpp.o: undefined symbol: __floatuntitf

**Comment by Lizard-King101** [comment]
what was the solution????

**Comment by riotom** [comment]
solution is easy.
you are should be check smartcontract for store types.
like in table uint128_t but you in code try put uint64_t
before put need prepare like uint128_t(value_64t_sample)
