### ISSUE TITLE
abigen_output option ignored by eosio-cpp

### ISSUE THREAD

**Issue by arhag** [EOSIO/eosio.cdt#513]
`-abigen_output` does not appear to have any effect on where the generated ABI is stored (tested with eosio.cdt v1.6.1).

Also, eosio-cpp generates an ABI by default anyway. If this is not the intended behavior, it should disable writing out the ABI file unless `-abigen` is provided. If it is the intended behavior then the `-abigen` option should be removed and optionally eosio-cpp should include a new `-no-abigen` option to disable writing out the ABI file.

Also, is the standalone `eosio-abigen` tool needed anymore?

**Comment by johndebord** [comment]
In reference to [PR #6](https://github.com/EOSIO/lld/pull/6) and [PR #517](https://github.com/EOSIO/eosio.cdt/pull/517), there is now a new flag for `eosio-ld` giving you the option to opt out of generating a `.abi` file via the flag `-no-abigen`.

**Comment by nathanhourt** [comment]
For the record, these issues are still present in v1.7.0: ABI is generated regardless of whether `-abigen` is passed or not, and `-abigen_output` has no effect on where the ABI is put. Thus these flags are, AFAICT, completely ignored.

Curiously, passing `-no-abigen` does indeed suppress the creation of an ABI file, but it also causes an error:
```
$ eosio-cpp -no-abigen hello.cpp
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <hi> does not have a ricardian contract
/opt/eosio.cdt/eosio.cdt/bin/wasm-ld: error: unknown argument: -no-abigen
```

...and for formality's sake...

```
$ eosio-cpp -version
eosio-cpp version 1.7.0
```

**Comment by sanaraufx** [comment]
This should be fixed in the latest version of cdt.
