### ISSUE TITLE
Compile and unit test examples

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eosio.cdt#514]
I reached the **Native Tester/Compilation** section in the eosio.cdt [guide](https://eosio.github.io/eosio.cdt/1.6.0/guides/native-tester.html#native-testercompilation) where it directed me to "`./examples/hello/tests/hello_test.cpp` for working examples."

From the source tree of `eosio.cdt`, I'm not sure how to run the hello example tests though.  What should I do to compile and run the unit tests for the examples?

I did create a root `eosio.cdt/build` than ran `cmake ..` and make just fine.  However, there is no hello_tests target.  This is probably excluded by choice: looking at `eosio.cdt/CMakeFiles.txt`, it does not include the `examples` directory.  Running `cmake ..` from a new `build` directory in the examples folder did not create any targets (If it matters I already have a `eosio.cdt/build`).

What is the preferred way to get this working?

**Comment by stefanzarembinski** [comment]
For me, it works:


eosio-cpp -o <path>/examples/hello/build/hello_test -I=/usr/opt/eosio.cdt/1.6.1/include/eosiolib/capi -I=/usr/opt/eosio.cdt/1.6.1/include/eosiolib/native -I=/usr/opt/eosio.cdt/1.6.1/include/eosiolib/native/eosio -I=<path>/examples/hello -I=<path>/examples/hello/include -abigen -fnative -R=<path>/examples/hello/ricardian <path>/examples/hello/src/hello.cpp <path>/examples/hello/tests/hello_test.cpp

**Comment by stefanzarembinski** [comment]
Correction: includes are not necessary, I have them for the intelisense of my system.


eosio-cpp -o <path>/examples/hello/build/hello_test -I=<path>/examples/hello/include -abigen -fnative -R=<path>/examples/hello/ricardian <path>/examples/hello/src/hello.cpp <path>/examples/hello/tests/hello_test.cpp
