### ISSUE TITLE
multiindex::upper_bound returns same value as lower_bound

### ISSUE THREAD

**Issue by matei-radu** [EOSIO/eosio.cdt#524]
When using a secondary index, `multiindex::upper_bound` and `multiindex::lower_bound` return iterators pointing at the same object with `lower_bound` being the correct one of the two.

## How to reproduce
Table definition:
```cpp
TABLE player {
    uint64_t id;
    uint64_t score;
    uint64_t rank;
  
    uint64_t primary_key() const { return id;    }
    uint64_t get_score()   const { return score; }
};

typedef multi_index<"players"_n, row, 
    indexed_by<"byscore"_n, const_mem_fun<player, uint64_t, &player::get_score>>
> player_index;
```

Actual records in the table:

| id | score | rank |
|:--:|:-----:|:----:|
| 0 | 1000 | 10 |
| 1 | 1005 | 9 |
| 2 | 1010 | 8 |
| 3 | 1015 | 7 |
| 4 | 1020 | 6 |
| 5 | 1025 | 5 |
| 6 | 1030 | 4 |
| 7 | 1035 | 3 |
| 8 | 1040 | 2 |
| 9 | 1045 | 1 |

Usage within an action:
```cpp
uint64_t score = 1032;

player_index players(get_self(), get_self().value);

auto score_index = players.get_index<"byscore"_n>();
auto upper_itr = score_index.upper_bound(score); // upper_itr->score should be 1030
auto lower_itr = score_index.lower_bound(score); // lower_itr->score should be 1035
```

`upper_itr` and `lower_itr` should be pointing to the objects with id 6 and 7 respectively, however, they both point to the same object with id 7 and score 1035.

My understanding is that this scenario should only occur when the `score` in the example above is matched in the table (e.g. `score = 1035` which would match object with id `7`).

**Comment by arhag** [comment]
It is correct behavior for `upper_bound` in the example given to point to the record with an `id` of 7.

The `multi_index` `upper_bound` is following the same definition as `upper_bound` seen elsewhere, for example: https://en.cppreference.com/w/cpp/algorithm/upper_bound.

I think I see what the cause of the confusion is. Our documentation has an incorrect description of `upper_bound`. I have created an issue for correcting that: https://github.com/EOSIO/eosio.cdt/issues/542.

By the way, if you do want to find the table with the highest key that is less than or equal to the provided key, all you need to do is get the iterator with the `upper_bound` and then go one backwards (but first make sure to check that the iterator returned by `upper_bound` is not pointing to the row at the beginning of the table). (And if you want strictly less than, do the same thing but use `lower_bound` instead.)

**Comment by matei-radu** [comment]
@arhag But if that is the case, what is the difference between upper and lower bound? They both behave the same (or at least produce the same result) and, if we correct the documentation as you suggested, that too would be identical to `lower_bound`'s description.

**Comment by arhag** [comment]
@matei-radu:

They aren't the same behavior. To use your example, a lower_bound search with a lookup key of 1030 would return id 6 but an upper_bound search with a lookup key of 1030 would return id 7.

These definitions are useful because they allow you to get the equal range easily. So if you wanted all the rows that have a secondary key of X, you would do a lower_bound(X) and then iterate forward until you reach upper_bound(X) (that last one should be excluded since it won't be in the equal range).
