### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ansigroup** [EOSIO/eosio.cdt#527]
Hello,

we found an issue (cdt 1.5.0-1.6.1)  on using construction which include array of self objects, like `std::vector<testtab>` :

```
TABLE testtab {
  uint64_t    id;
  std::vector<testtab> container; 

  auto primary_key() const {  return id; }
};
```
This construction is used in simpleassets.io (NFT standart) for attaching NFTs and FTs into others NFTs (https://github.com/CryptoLions/SimpleAssets/blob/master/include/SimpleAssets.hpp#L529)

Using CDT 1.5.0 - wasm was created but abi was failed. For deploying wasused manually modified abi file (https://github.com/CryptoLions/SimpleAssets/blob/master/SimpleAssets.abi#L539)  and result was OK (img below). 

![image](https://user-images.githubusercontent.com/37701692/59544648-3d312d00-8f1c-11e9-9f9e-36c4d094bc7f.png)

With cdt 1.6.1. building is failed totaly and no wasm or abi is created.

Test project with construction:
[test.tar.gz](https://github.com/EOSIO/eosio.cdt/files/3292567/test.tar.gz)

Thanks,
Best Regards,
Bohdan

**Comment by jeffreyssmith2nd** [comment]
Confirmed on 1.6.2 as well.

**Comment by jeffreyssmith2nd** [comment]
Actually, I must have tested with 1.6.1. With 1.6.2 (built from source on the v1.6.2 tag), the compilation succeeds but the ABI generation fails. Can you test again with 1.6.2 and let me know what results you get?

**Comment by ansigroup** [comment]
> Actually, I must have tested with 1.6.1. With 1.6.2 (built from source on the v1.6.2 tag), the compilation succeeds but the ABI generation fails. Can you test again with 1.6.2 and let me know what results you get?

tested on 1.6.2 failed both abi and wasm.

**Comment by jeffreyssmith2nd** [comment]
Tested again with the brew package for 1.6.2 and am indeed seeing this. Not sure why it seemed like I wasn't previously.

**Comment by ansigroup** [comment]
Issue fixed. Just confirmed. Thank you very much.
