### ISSUE TITLE
eosio-cpp returns 0 on error

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#528]
running eosio.cdt 1.5.0:
```bash
$ eosio-cpp t.cpp -o t.wasm --abigen -D'__BURN__=\"burn\"'
```
crashes:
``` 
In file included from /Users/ekkis/dev/t.cpp:1:
./t.hpp:53:20: error: use of undeclared identifier '__BURN__'
                name BURN = name(__BURN__);
                                 ^
1 error generated.
Error while processing /Users/ekkis/dev/t.cpp.
```
but if I examine the return value:
```bash
$ echo $?
```
it doesn't see the problem:
> 0

it's broken

**Comment by jeffreyssmith2nd** [comment]
I'm not seeing this on several different types of failures, I see different error codes for different types.

Can you share more of the contract that is giving you the error?

**Comment by ekkis** [comment]
it must have been a 1.5.0 issue.  I upgraded a while back and as of 1.6.1 this seems to work properly.  closing...
