### ISSUE TITLE
Troubles with -D for eosio-cpp

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#529]
if I run the command below with CDT 1.5.0:
```bash
$ eosio-cpp t.cpp -o t.wasm --abigen -D'__BURN__=\"burn\"'
```
I get the error below:
```
In file included from /Users/ekkis/dev/t.cpp:1:
./t.hpp:53:20: error: use of undeclared identifier '__BURN__'
                name BURN = name(__BURN__);
                                 ^
```
however, if I look at the preprocessor output:
```bash
$ eosio-cpp t.cpp -o - -D'__BURN__=\"burn\"' -E -dD |grep BURN
```
I can not only see the define properly created but I can see that the reference has been properly replaced with the value (2nd line):
```
> #define __BURN__ "burn"
>  name BURN = name("burn");
```
yet, the code won't compile. if I manually replace the line:
```
                name BURN = name(__BURN__);
```
with:
```
                name BURN = name("burn");
```
it compiles just fine.  what is wrong with this?

**Comment by ekkis** [comment]
this was closed without resolution.  I'm having the same problem on CDT 1.6.3

**Comment by swatanabe-b1** [comment]
See #736.  1.6.3 was released a month before that.

**Comment by ekkis** [comment]
so this shows as merged, but it hasn't yet been released?
