### ISSUE TITLE
v1.6.1 -D passing quotes properly?

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#531]
I have (for testing purposes) the following code:
```c++
[[eosio::action]]
void t() {   
    print("\n[", __TEST__, "]");
}
```
if I compile the code like this:
```bash
$ eosio-cpp t.cpp -D__TEST__=worked
```
it will fail because it generates a line like this, which obviously needs quotes:
```
#define __TEST__ worked
```
so at first I tried:
```bash
$ eosio-cpp t.cpp -D__TEST__="worked"
```
but that didn't work:
```
#define __TEST__ worked
```
so I tried all these variations:
```bash
$ eosio-cpp t.cpp -D__TEST__=\"worked\"
#define __TEST__ worked
$ eosio-cpp t.cpp -D__TEST__="\""worked"\""
#define __TEST__ worked
$ eosio-cpp t.cpp -D__TEST__=\"\"worked\"\"
#define __TEST__ ""worked""
$ eosio-cpp t.cpp -D'__TEST__="worked"'
#define __TEST__ worked
$ eosio-cpp t.cpp -D'__TEST__=\"worked\"'
#define __TEST__ \"worked\"
$ eosio-cpp t.cpp -D"__TEST__=\"worked\""
#define __TEST__ worked
$ eosio-cpp t.cpp -D__TEST__=""worked""
#define __TEST__ worked
$ eosio-cpp t.cpp -D'__TEST__=""worked""'
#define __TEST__ ""worked""
```
the last of which puzzled me.  so 2 quotes inside of ticks come across but a single quote inside of ticks doesn't??

I'm reporting this as a bug (instead of asking on StackExchange) because I believe the preprocessor is doing something funky with quotes.  this is not a shell issue.

what I need is:
```
#define __TEST__ "worked"
```
can anyone figure out how to make that happen?

p.s. of course, I can't just write:
```c++
[[eosio::action]]
void t() {   
    print("\n[__TEST__]");
}
```
since the preprocessor will not replace values within string literals, so I need the define generated to quote the value

**Comment by GassaFM** [comment]
This works for me:
~~~~~
cat >test.cpp <<EOF
#pragma message (TEST)
EOF
eosio-cpp test.cpp -c -DTEST='\"123\"'
~~~~~

With version:
~~~~~
eosio-cpp --version
eosio-cpp version 1.3.2
~~~~~

**Comment by ekkis** [comment]
this is what I get for 1.6.1
```
/Users/ekkis/dev/eos/x.cpp:1:18: error: expected string literal in pragma message
#pragma message (TEST)
                 ^
<command line>:3:14: note: expanded from here
#define TEST \"123\"
             ^
/Users/ekkis/dev/eos/x.cpp:1:18: error: expected unqualified-id
<command line>:3:15: note: expanded from here
#define TEST \"123\"
              ^
2 errors generated.
Error while processing /Users/ekkis/dev/eos/x.cpp.
abigen error
```

**Comment by GassaFM** [comment]
Try just `'"123"'` instead of `'\"123\"'`, then.

**Comment by ekkis** [comment]
```
x.cpp:1:18: error: expected string literal in pragma message
#pragma message (TEST)
                 ^
<command line>:3:14: note: expanded from here
#define TEST 123
             ^
1 error generated.
```

**Comment by GassaFM** [comment]
Sad. The `'\"'` vs. `'"'` looks like a bug indeed.

**Comment by ekkis** [comment]
I'm going to have to downgrade because I can't even compile stuff, see: https://github.com/EOSIO/eosio.cdt/issues/530

**Comment by Buzhanin** [comment]
Just use stringizing operator.
For example:
```
#define TOSTR(T) #T

[[eosio::action]]
void t() {   
    print("\n[", TOSRT(__TEST__), "]");
}
```

**Comment by ekkis** [comment]
wow!  well that works.  I don't understand how but it works.  a million thanks.

I'm going to leave this issue open since the compiler does have a problem and it should be fixed

**Comment by ekkis** [comment]
@Buzhanin sadly I spoke too soon.  your solution works but the -D parameter doesn't.  I was so excited to see it compile that I failed to notice what it actually printed on the log: `__TEST__` -- in other words, it quoted it, but it quoted the literal and the #define got ignored

**Comment by ekkis** [comment]
and sadly, 1.6.1 breaks -E so I can no longer see the output of the preprocessor

**Comment by Buzhanin** [comment]
My bad. I forgot that it should be more tricky.

Replace

`#define TOSTR(T) #T`

with

```
#define TOSTR_(T) #T
#define TOSTR(T) TOSTR_(T)
```

**Comment by ekkis** [comment]
yes.  I consulted with someone who knows more about these matters than I do and he stated it's a matter of double evaluation:
```
> <Kaslai> You need an extra layer of macros
> <Kaslai> #define TOSTR2(T) #T \n #define TOSTR(T) TOSTR2(T)
> <Kaslai> The reason is that the stringification will stringify the token exactly
> as presented to the macro
> <Kaslai> If you have a second macro in between the stringification and the use
> of the macro, both the outside function-like macro and your _X_ macro will expand
> at the same time
> <Kaslai> Before expansion: print(TOSTR(_X_)); First expansion: print(TOSTR2(wow)); 
> Second expansion: print("wow");
> <Kaslai> Without the extra later it doesn't get the change to expand the _X_ 
> macro into wow
```
