### ISSUE TITLE
How to get infomation about block in eos contract?

### ISSUE THREAD

**Issue by zonxin** [EOSIO/eosio.cdt#533]
I want to get then current block number and the block ID for a given block number in eos contract. Does anyone know how to get the information ?

**Comment by johndebord** [comment]
Check out [Issue #6695](https://github.com/EOSIO/eos/issues/6695) for a good read on this topic. I think you will find it extremely useful.
But the bottom line is that this functionality would require a new intrinsic; thus a fork of the network.

Currently there is an issue open from the community requesting this feature. But for the time being, we don't have plans to implement this feature.
