### ISSUE TITLE
v 1.6.1 running only the preprocessor

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#534]
on OSX I can do this:
```
$ eosio-cpp x.cpp
```
but I can no longer do this (I used to be able to, in v1.5.0):
```
$ eosio-cpp x.cpp -E -dD
```
I get the following errors:

> Error while trying to load a compilation database:
> Could not auto-detect compilation database for file "x.cpp"
> No compilation database found in /Users/ekkis/dev/eos or any parent directory
> fixed-compilation-database: Error while opening fixed database: No such file or directory
> json-compilation-database: Error while opening JSON database: No such file or directory
> Running without flags.
> /Users/ekkis/dev/eos/x.cpp:1:10: fatal error: 'eosio/eosio.hpp' file not found
> #include <eosio/eosio.hpp>
>          ^~~~~~~~~~~~~~~~~
> Warning, empty ricardian clause file
> Warning, empty ricardian clause file
> Warning, action <t> does not have a ricardian contract
> 1 error generated.
> Error while processing /Users/ekkis/dev/eos/x.cpp.
> abigen error

these are useful flags as they allow me to check for preprocessor-generated code, but now it's broken

**Comment by jeffreyssmith2nd** [comment]
Confirmed seeing this on 1.6.2

**Comment by form2l1n** [comment]
Confirmed seeing this also in Linux built apt version

**Comment by fospring** [comment]
I also meet the same problem,on `OS X`, I can compile with:
```bash
eosio-cpp hello.cpp -o hello.wasm
```
But I want to view macro extened by `preprocessor` with option `-E`:
```bash
eosio-cpp -E hello.cpp
``` 
error reported with:
```bash
/Users/fospring/work/cpp/src/github.com/EOSIO/test_contract/hello/hello.cpp:1:10: fatal error:
      'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~~~~~~
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <hi> does not have a ricardian contract
1 error generated.
Error while processing /Users/fospring/work/cpp/src/github.com/EOSIO/test_contract/hello/hello.cpp.
abigen error
```
