### ISSUE TITLE
duplicate symbol error when linking contracts consisting of multiple .cpp files

### ISSUE THREAD

**Issue by arhag** [EOSIO/eosio.cdt#539]
The EOSIO.CDT eosiolib header files include implementations of certain functions, such as `eosio::send_deferred`, in the header files. When trying to link a contract consisting of multiple cpp files that each include those problematic header files (such as `transaction.hpp`), the linker gives a duplicate symbol error.

**Comment by swatanabe-b1** [comment]
Fixed in https://github.com/EOSIO/eosio.cdt/pull/479
