### ISSUE TITLE
eosio-cpp spoiled abi file and run abigen without option

### ISSUE THREAD

**Issue by mikolajsobolewski** [EOSIO/eosio.cdt#548]
Hello.
I run     
``eosio-cpp  ${contractdir}/$contract.cpp -o ${contractdir}/${contract}.wasm``
``${contractdir}`` also contains ``${contract}.abi`` and running of the command is rewriting my abi file without ``-abigen`` option.

**Comment by jeffreyssmith2nd** [comment]
See #513, a new flag will be coming that allows you to disable abi generation. Closing in favor of the earlier issue.
