### ISSUE TITLE
Compilation has been stuck

### ISSUE THREAD

**Issue by Parth2412** [EOSIO/eosio.cdt#556]
- I am trying to set up my own local network EOSIO and for that, I am following [boot-bios-sequence](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence).

- I am going step by step so I installed binaries of EOSIO and EOSIO.CDT as said at [step 1.1](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence#section--1-1-install-pre-compiled-eosio-and-eosio-cdt-binaries-) so when you go for EOSIO.CDT it will redirect you to [here](https://github.com/EOSIO/eosio.cdt#debian-package-install). This package is not there in the EOSIO.CDT releases so I downloaded the binary of [v.1.6.1](https://github.com/EOSIO/eosio.cdt/releases/tag/v1.6.1)

- And It goes perfect until step 1.7 but in step 1.8 it asks for clone the [eosio.contract](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence#section--1-8-build-eosio-contracts-) so I cloned that and run "./build.sh" script it took more than 3 hours to compile but It was not successfully compiled as the script stuck at 100% and said that "Linking CXX file to eosio.system.wasm", it won't be completed. 

- I tried with other EOSIO.CDT versions but I faced the same issue. I don't know what is the exact issue because it won't give me any type of error. it just simply reached to 100% and then it stuck and doesn't compile successfully. 

- I am using three AWS instances with the same configuration (8 GB RAM, 30 GB HDD, 2 CPUs)  and all have ubuntu 16.04 LTS
![Screenshot from 2019-07-18 18-10-08](https://user-images.githubusercontent.com/23364077/61458179-83e4cd80-a987-11e9-9a87-b432d20308ba.png)

**Comment by jeffreyssmith2nd** [comment]
This is likely the same issue as #471 and #741. Should be resolved in #896
