### ISSUE TITLE
error: use of undeclared identifier 'eosio_assert'

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eosio.cdt#573]
Running into this error when building with `eosio-cpp` version 1.6.2 every time code contains use of `eosio_assert`

```
error: use of undeclared identifier 'eosio_assert'; did you mean
      'eosio::internal_use_do_not_use::eosio_assert'?
        eosio_assert(first_name.size() > 0, "first name should be more than 0 characters long");
        ^~~~~~~~~~~~
        eosio::internal_use_do_not_use::eosio_assert
```

**Comment by conr2d** [comment]
Use `eosio::check` instead of `eosio_assert`. Calling C APIs (or its wrappers having namespace `eosio::internal_use_do_not_use`) directly isn't supported now.
