### ISSUE TITLE
v1.6.2 link broke 

### ISSUE THREAD

**Issue by kriskoin** [EOSIO/eosio.cdt#583]
this link https://github.com/eosio/eosio.cdt/releases/download/v1.6.2/eosio.cdt-1.6.2-1.fedora-x86_64.rpm is broken, when i try to download with the commanf wget https://github.com/eosio/eosio.cdt/releases/download/v1.6.2/eosio.cdt-1.6.2-1.fedora-x86_64.rpm  i got the err msg : 

wget https://github.com/eosio/eosio.cdt/releases/download/v1.6.2/eosio.cdt-1.6.2-1.fedora-x86_64.rpm

**Comment by jeffreyssmith2nd** [comment]
That's expected, that package does not exist. You can go the Releases section and look at Assets to see what packages are available.

https://github.com/EOSIO/eosio.cdt/releases/tag/v1.6.2
