### ISSUE TITLE
ABI generation fails if -o filename differs from contract name

### ISSUE THREAD

**Issue by tj800x** [EOSIO/eosio.cdt#588]
When compiling a test.cpp contract, specifying the output as anything other than "test.wasm" will cause the contract to be compiled to wasm but the abigen to fail with a with wasm-ld reporting "error: fatal failure: contract with no actions and trying to create dispatcher".  This is potentially confusing because this appears to be the same error message that appears when the contract's class name doesn't match the cpp filename.

$ eosio-cpp -I ../include -o nottest.wasm ../src/test.cpp --abigen

  Result: No *.abi file

$ eosio-cpp -I ../include -o test.wasm ../src/test.cpp --abigen

  Result: test.abi file is successfully created.

**Comment by jeffreyssmith2nd** [comment]
On the latest code, it no longer errors out. However abi generation still fails.

**Comment by sanaraufx** [comment]
This is by design. If you change the -o filename, you need to explicitly pass in --contract_name.
