### ISSUE TITLE
Add .prefix() expression to {name}

### ISSUE THREAD

**Issue by DenisCarriere** [EOSIO/eosio.cdt#648]
It would be very helpful to have an expression that is able to retrieve the **prefix** of an EOSIO `name` type.

Currently only `.suffix()` is available.

## Example 1

```c
name account = name{"my.account"};
name suffix = account.suffix(); // => "account"
name prefix = account.prefix(); // => "my"
```

## Example 2

For names with multiple prefixes, split name at the first `.` dot to the right.

```c
name account = name{"a.my.account"};
name suffix = account.suffix(); // => "account"
name prefix = account.prefix(); // => "a.my"

name subsuffix = prefix.suffix(); // => "my"
name subprefix = prefix.prefix(); // => "a"
```

## References

- [eosiolib/name.hpp](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/name.hpp#L135)

**Comment by DenisCarriere** [comment]
Added an additional example in the case of multiple prefixes (ex: `a.my.account`)

**Comment by zacck** [comment]
Can we close this since it seems to be completed?

**Comment by DenisCarriere** [comment]
🎉 awesome, completed indeed

Thanks @victorj8 for the implementation!
