### ISSUE TITLE
-frtti support for eosio-cpp

### ISSUE THREAD

**Issue by tigran-gruv** [EOSIO/eosio.cdt#657]
I'm using eosio-cdt 1.6.2

The compiler gives the following error:

`include/static_variant.hpp:29:13: error: use of typeid requires -frtti`
`                if (id == typeid(F).hash_code())
`

When I add that manually, I'm given

 `eosio-cpp: Unknown command line argument '-frtti'.  Try: 'eosio-cpp -help'`

And in the list of `eosio-cpp -help` I don't see that flag.

**Comment by larryk85** [comment]
We will not be adding RTTI support for smart contract development at this time.  In a future release we might see needs that require us to add support.  What particularly is your need for RTTI?

**Comment by tigran-gruv** [comment]
I was trying using static_variant implementation which uses typeid() function. So I got that error.
Now I'm using another solution to my problem. But I think it would be useful to have it.
Thank you for your response.
