### ISSUE TITLE
Description of end() in multi-index is completely misleading

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.cdt#683]
end() and cend() in multi-index are documented wrongly. 

Lines 831, 854 in 
https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/multi_index.hpp
and also the documentation on developers portal are misleading:

```
Returns an iterator pointing to the `object_type` with the highest primary key value in the Multi-Index table.
```

It's not true. end() is returning a non-existing object that is past the highest key value.

**Comment by iamveritas** [comment]
This has been addressed in [29e23f0](https://github.com/EOSIO/eosio.cdt/commit/29e23f0c43bc2a960df397958f5814e5dac05598)

**Comment by tbfleming** [comment]
Still not correct.

**Comment by iamveritas** [comment]
Please add more details explaining what is incorrect. Thank you.

**Comment by tbfleming** [comment]
Here's a quote directly from the ISO C++ standard for `vector::end()`:

`end()` returns an iterator which is the past-the-end value for the container. If the container is empty, then `begin() == end()`

Key points:
* The iterator is past-the-end. Never refer to it pointing to something past the end.
* Creating a strawman "theoretical" element is unnecessary. Iterators don't always refer to something, just like pointers don't always point to something.

**Comment by tbfleming** [comment]
More detail in the standard pointed out by @swatanabe-b1: 

> Just as a regular pointer to an array guarantees that there is a pointer value pointing past the last element of the array, so for any iterator type there is an iterator value that points past the last element of a corresponding sequence. Such a value is called a "past-the-end value".

> Values of an iterator `i` for which the expression `*i` is defined are called "dereferenceable". The library never assumes that past-the-end values are dereferenceable. Iterators can also have singular values that are not associated with any sequence.

**Comment by iamveritas** [comment]
here's two searches through the ICO C++ standard sources:

https://github.com/cplusplus/draft/search?q=%22iterator+referring+to%22&unscoped_q=%22iterator+referring+to%22

and 

https://github.com/cplusplus/draft/search?q=%22iterator+pointing+to%22&unscoped_q=%22iterator+pointing+to%22

there are several places which use the expression `iterator pointing to` and `iterator referring to` are used.

also the ICO C++ standard website is [mentioning here](https://isocpp.org/std/the-standard) the `www.cplusplus.com` as a valid albeit not authoritative source of information.

the current annotation which you call "incorrect" it is using the same terms used by the `www.cplusplus.com` here: http://www.cplusplus.com/reference/vector/vector/end/

I think it's commonly accepted both ways of saying `there is an iterator value that points past the` as well as `the iterator that points past the`, by the C++ ICO standard and the community in general.

My conclusion is that we are splitting hairs here with no real benefit.

**Comment by tbfleming** [comment]
> there are several places which use the expression iterator pointing to and iterator referring to.

yes, but not an `end` iterator

**Comment by iamveritas** [comment]
This is what we have now: "An iterator referring to the `past-the-end` element in the multi index container."

`referring` is not the same as `pointing`.
"A pointer has its own memory address and size on the stack (4 bytes on x86), whereas a reference shares the same memory address (with the original variable) but also takes up some space on the stack."

saying `an iterator referring to the past-the-end element of the multi index container` it is the same thing as explained in below paragraph which you mentioned:

`Just as a regular pointer to an array guarantees that there is a pointer value pointing past the last element of the array, so for any iterator type there is an iterator value that points past the last element of a corresponding sequence. Such a value is called a "past-the-end value". `

It is not saying is pointing to something past the end, like you have been asking here:`Never refer to it pointing to something past the end`. It is saying it is referring which is the same thing as saying `is the past-the-end element/value`.

I really not see what is wrong here.

**Comment by swatanabe-b1** [comment]
The iterator does not refer to the past-the-end value.  There is no past-the-end value.  It is the iterator itself that is past-the-end.

**Comment by iamveritas** [comment]
> There is no past-the-end value. It is the iterator itself that is past-the-end.

this is from the source quoted above by you and tbfleming:
`so for any iterator type there is an iterator value that points past the last element of a corresponding sequence. Such a value is called a "past-the-end value"`

this is not getting me anywhere farther in understanding. may I suggest if you feel so strong about this to take ownership of it and fix the code comment/annotation as per your understanding? Thank you.

**Comment by tbfleming** [comment]
Maybe this will help:
* An iterator has a value. This is different from what it points at.
* An iterator value may point *at* something, point *past* something, or be uninitialized. The iterator can point past the container's end. The standard calls the iterator's value in this case "past-the-end value"; it does not say it's pointing at or refering to a "past-the-end value".

We can word it exactly like the ISO C++ standard words it: `end()` returns an iterator which is the past-the-end value for the container. If the container is empty, then `begin() == end()`

**Comment by tbfleming** [comment]
Let's an analogy:

```
int a[256];       // Assume this is at address 0x1000
int *p = a;       // p has value 0x1000, it points to a[0]
int *e = a + 256; // e has value 0x1100.
```

`e` does not point at anything. It points past the array's end. In this case, another name for the value `0x1100` is the past-the-end value for `a`.
