### ISSUE TITLE
readme: deb package file name is wrong

### ISSUE THREAD

**Issue by GassaFM** [EOSIO/eosio.cdt#689]
At https://github.com/EOSIO/eosio.cdt#debian-package-install, the file name is shown as:
```
$ wget https://github.com/eosio/eosio.cdt/releases/download/v1.6.2/eosio.cdt_1.6.2-1_amd64.deb
$ sudo apt install ./eosio.cdt_1.6.2-1_amd64.deb
```

The actual file name is `eosio.cdt_1.6.2-1-ubuntu-18.04_amd64.deb`, so the readme should perhaps be corrected on both occasions.

**Comment by larryk85** [comment]
Should now have the naming of packages in the automation pipeline correctly working now, thanks for the heads up.
