### ISSUE TITLE
segfault when using template

### ISSUE THREAD

**Issue by cmadh** [EOSIO/eosio.cdt#729]
Following code leads to a segfault. 
(I assume it's this part as there's no other place in the contract I'm working with templates)

function:
`

         template<typename T>
         void addmovableasset(name *player_name, planetstable &planets,planetstable::const_iterator &planet, uint16_t asset_id)
         {

         T asset = T();
         char type_buffer[sizeof(asset)];
         memcpy(type_buffer, &asset, sizeof(asset));
         vector<char> serialized_asset = vector<char>(type_buffer, type_buffer + sizeof(asset));

         pair<uint16_t, vector<char>> asset_pair = pair<uint16_t,vector<char>>(asset_id, serialized_asset);

         vector<pair<uint16_t, vector<char>>> movable_assets = planet->movable_assets;
         movable_assets.push_back(asset_pair);

             planets.modify(planet, *player_name, [&]( auto& p) {
                  p.movable_assets = movable_assets;
              });
         }`

function-call: 
`           
      addmovableasset<colony_ship_type>(&player_name, planets, planet, asset_id);
`

crash-report:
[eosio.cdt.crash.zip](https://github.com/EOSIO/eosio.cdt/files/3817624/eosio.cdt.crash.zip)

**Comment by cmadh** [comment]
Tried with cdt-versions 1.6.1 and 1.7.0 RC. Crash-report is from version 1.7.0.

**Comment by swatanabe-b1** [comment]
I can't reproduce this.

**Comment by cmadh** [comment]
I'll investigate and come back.

**Comment by cmadh** [comment]
ok, my original thought was wrong.

@swatanabe-b1  try the following to reproduce:

` TABLE tests {uint64_t                    id;
         array<uint8_t,32>           hash;
         uint64_t primary_key()      const { return id; }
    };
    typedef multi_index<name("tests"), tests> tests_table;
`

**Comment by cmadh** [comment]
> Segmentation fault      (core dumped) eosio-cpp -abigen -I $PROJECT_INCLUDE_PATH -R $PROJECT_RESOURCE_PATH -contract $contractname -o "$contractname.wasm" $mainfile

**Comment by swatanabe-b1** [comment]
The abi generator can't handle std::array.  In general, it seems to choke on non-type template parameters.

**Comment by MrToph** [comment]
@sanaraufx I assume this has been fixed because you closed it? Could you link to the PR that fixed this?
