### ISSUE TITLE
access to all trx actions

### ISSUE THREAD

**Issue by slyon** [EOSIO/eosio.cdt#739]
Is it possible to access the list (vector) of the current transaction's actions?

E.g. if we have a trx with two actions:
mycontract::action1 & eosio.token::transfer

Can I check from within mycontract::action1 that there is one more action inside this trx and it is an eosio.token::transfer action from user1 to user2?

**Comment by swatanabe-b1** [comment]
There is no API for this, and even if there were it couldn't include inline actions.

**Comment by swatanabe-b1** [comment]
It is possible to use a notification on the transfer, however: https://developers.eos.io/eosio-home/docs/notification-handlers
