### ISSUE TITLE
include `time_point_sec::from_iso_string` in CDT

### ISSUE THREAD

**Issue by DenisCarriere** [EOSIO/eosio.cdt#747]
It would be very useful to include `time_point_sec::from_iso_string` into the CDT

That way it would allow to parse datetime strings directly in the smart contract, currently the only way to parse datetime string is to push the action and have it parsed by nodeos using the chain plugin.

```c++
const time_point& current_time = time_point::from_iso_string("2020-01-01T00:00:00.000");
```

**error**

```c++
 error: no member named 'from_iso_string' in
      'eosio::time_point'
```

The logic is already written in the `fc/time` library, not too sure how difficult it would be to include in the CDT

https://github.com/EOSIO/fc/blob/df5a17ef0704d7dd96c444bfd9a70506bcfbc057/src/time.cpp#L35-L64

**Comment by larryk85** [comment]
Reasonable enough to add to the next release.  Thanks for the suggestion.

**Comment by DenisCarriere** [comment]
@larryk85  that would be great add-on

At the moment, there's a lot of smart contract ideas/potential that requires the ability to add a fixed dates.

Ex: Setup a payment schedule on the 1st of every month

The current work around has been to do time intervals of 30 days (2592000 seconds) instead of doing a fixed dates approach (not ideal, but works).

**Comment by DenisCarriere** [comment]
@victorj8 Thanks for taking on this feature request 👍 really appreciate your work

**Comment by jeffreyssmith2nd** [comment]
Handled by #806
