### ISSUE TITLE
unnecessary concurrency throttling on Linux in build.sh

### ISSUE THREAD

**Issue by godmar** [EOSIO/eosio.cdt#750]
I'd like to share the following minor observation.

While building the CDT, I noticed that it utilized only 1 core. Upon investigation, I found that the current build.sh makes overly conservative assumptions about how many cores it should use based on how much memory is available on a machine. Specifically, it looks at "free" memory (in the output of the [free(1)](http://man7.org/linux/man-pages/man1/free.1.html) command.) An arguably better measure would be "available" memory ([$7 instead of $4](https://github.com/EOSIO/eosio.cdt/blob/master/build.sh#L75)).  Even in that case, you could build with minimal impact on other running applications. It may not make a difference for those sitting in front of beefy machines, but it can make a difference on a smaller machine with say only 16 GB of memory.

On a related note, I have not found it necessary to require 4GB of available memory per core. That seems overly conservative as well. eosio.cdt built just fine for me on a 16GB RAM laptop using all 8 cores (via `make -j8`). Perhaps 2GB per core would suffice.

**Comment by larryk85** [comment]
The reason this is set so conservatively is for our CICD systems.  When we first created these scripts for that purpose, that kept them from crashing.  We could add an option for the user to supply a jobs count to override this.

**Comment by jeffreyssmith2nd** [comment]
With the release of version 1.7, the build process is now simply `mkdir build && cd build && cmake .. && make -j <#ofcores>`.

Since the build script is no longer the recommended build strategy, I'm closing this. Please feel free to open new issue(s) if you have any other build concerns.
