### ISSUE TITLE
Static member initialisation corrupted

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.cdt#751]
I've posted here as a question https://eosio.stackexchange.com/questions/5106/static-values-get-mangled, in case I'm just doing something badly but I think this is a bug with the compiler.  I have the code below:
```c++
#include <eosio/eosio.hpp>
#include <eosio/asset.hpp>

namespace eosio {
    class UTL {
        public:
        static name code;
        static symbol sym;
    };  

    class [[eosio::contract("static")]] dapp : public contract {
        public:

        dapp(name receiver, name code, datastream<const char*> ds) 
            : eosio::contract(receiver, code, ds) {
            UTL::code = code;
            print("\nconstructor(I): code=", UTL::code);
            UTL::sym = symbol("XX", 2); 
            print("\nconstructor(II): code=", UTL::code);
        }   

        [[eosio::action]]
        void tst() {
            print("\ntst(): code=", UTL::code, ", sym=", UTL::sym);
        }   
    };  
}
```
from which it can be seen that as soon as the second initilisation occurs (UTL::sym), the value of the first one (UTL::code) gets messed up

this approach is very useful as it allows me to create static methods for things for which I don't really need to or want to instantiate an object.  but the static methods need access to certain variables, which can easily be initialised during the contract constructor

however, this fails.  here's typical output:

> constructor(I): code=testacct
> constructor(II): code=......2scp2.c,

from which it can be seen that the value of `code` becomes corrupt

I'm running on eosio v1.8.4.  help?

**Comment by larryk85** [comment]
This is not a problem with CDT.  Your program is using undefined behavior, and as such is doing something weird.  You have to explicitly initialize those fields.

```c++
#include <eosio/eosio.hpp>
#include <eosio/asset.hpp>

using namespace eosio;
class UTL {
   public:
      static name code;
      static symbol sym;
};

// initialize the static fields
name UTL::code = name{};
symbol UTL::sym = symbol{};

class [[eosio::contract]] test : public contract {
   public:
      test(name r, name c, datastream<const char*> d) : contract(r,c,d) {
         UTL::code = c;
         print_f("code= %\n", UTL::code);
         UTL::sym = symbol("XX", 2);
         print_f("code= %, sym= %\n", UTL::code, UTL::sym);
      }

      [[eosio::action]]
      void tst() {
         print_f("tst() : code= %, sym= %\n", UTL::code, UTL::sym);
      }
};
```

Output of `cleos push action eosio tst '[]' -p eosio` without static initialization:
```
>> code= eosio
>> code= .........flg.2, sym= 2,XX
>> tst() : code= .........flg.2, sym= 2,XX
```

Output of `cleos push action eosio tst '[]' -p eosio` with the static initialization:
```
>> code= eosio
>> code= eosio, sym= 2,XX
>> tst() : code= eosio, sym= 2,XX
```
Let me know if you have any other questions.  Thanks for bringing this up, I will add this to a list of C++ gotchas for smart contract developers.

**Comment by ekkis** [comment]
ah! you're entirely correct.  thank you for this.  my bad
