### ISSUE TITLE
Add functionality to specify that an action shall not have  a Ricardian Contract.

### ISSUE THREAD

**Issue by johndebord** [EOSIO/eosio.cdt#752]
Currently, a warning is emitted for every action that does not provide a Ricardian Contract.
In some cases a Ricardian Contract is not necessary.

I propose to alleviate the warnings during the compilation phase of a smart contract by adding the ability to specify that there shall not be a Ricardian Contract for a specific action.

<img width="798" alt="screenshot" src="https://user-images.githubusercontent.com/35586806/70177278-115f5a80-16a8-11ea-84fc-16680361fc47.png">

**Comment by larryk85** [comment]
Anyone writing a smart contract should be compelled to write Ricardian contracts for the actions.  It's a pattern that we want to promote, adding a flag to disables those warning helps to discourage that.  Every action that is defined in the developers smart contract should have some type of Ricardian contract, if they are that frustrated with it, they can create an empty RC in the file with the rest of their Ricardian contracts, but we don't want to promote that.  If truly don't require a Ricardian contract for that action, then I would question the validity of that action in the first place.  Obviously, it will not generate warnings for these contracts when compiling libraries or code that is not part of your "contract" module.

**Comment by canab** [comment]
There might be (and we have) a lot of action for the test purpose. They are never compiled in a production mode. And disabling warnings for them would be really helpful. Either by the flag or  annotation in code.
For example: 20 .cpp files and 20 test actions produce 400 wornings during the cmake compilation.

**Comment by jeffreyssmith2nd** [comment]
Thanks for the reminder, a new flag was added in #853. So this will be available in the next CDT release.
