### ISSUE TITLE
Change the default installation path of eosio.cdt from `/usr/local/` to `/usr/local/include/`.

### ISSUE THREAD

**Issue by johndebord** [EOSIO/eosio.cdt#753]
The installation path of where `eosio.cdt` is installed should remain consistent with the installation path of where `eosio` is installed.

Currently:
`eosio` is installed in path `/usr/local/include/`; referenced [here](https://github.com/EOSIO/eos/blob/master/CMakeLists.txt#L7).
`eosio.cdt` is installed in path `/usr/local/`; referenced [here](https://github.com/EOSIO/eosio.cdt/blob/master/CMakeLists.txt#L28).

**Comment by larryk85** [comment]
I don't understand this one.  We do not want to install to /usr/local/include, that is user installed system header files.  EOSIO doesn't install to /usr/local/include, it installs to /usr/local/eosio, this is consistent with eosio.cdt.  If that is not the case, then we need to consider that a bug on the EOS repo.

**Comment by johndebord** [comment]
I see. Then, the bug is in the `eos` repo; I'll file a new issue.
<img width="717" alt="screenshot" src="https://user-images.githubusercontent.com/35586806/70251379-61dcc380-174d-11ea-9228-4ea96af5fb54.png">
