### ISSUE TITLE
compile errors with table containing public_key

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eosio.cdt#769]
Using 1.7.0-rc1. When a table contains a `public_key` I'm getting compile errors. For example,

```c++
#include <eosio/eosio.hpp>
#include <eosio/crypto.hpp>

using namespace eosio;


class [[eosio::contract]] custy : public contract {
   public:
      using contract::contract;

      [[eosio::action]]
      void startcreate(name owner, unsigned_int keytype, uint64_t keyid) {
         require_auth(owner);
         key_index keys(get_self(), owner.value);

         keys.emplace(owner, [&](auto& row) {
           row.keyid = keyid;
         });
      }

   private:
      struct [[eosio::table]] keytable {
         uint64_t keyid;
         checksum256 salt;
         public_key pub;

         uint64_t primary_key() const { return keyid; }
      };
      typedef eosio::multi_index<"keytable"_n, keytable> key_index;
};
```

when compiling this I get a couple errors like

```
/home/spoon/cdt/eosio.cdt/bin/../include/boost/pfr/detail/offset_based_getter.hpp:63:3: error: 
      static_assert failed "Member sequence does not indicate correct size for struct type!"
  static_assert(sizeof(U) == sizeof(S), "Member sequence does not indicate correct size fo...
```

I've noticed that if I change the definition of `public_key` in `crypto.hpp` from

```c++
using public_key = std::variant<ecc_public_key, ecc_public_key, webauthn_public_key>;
```
to
```c++
 using public_key = std::variant<ecc_public_key, ecc_public_key>
```

I can compile successfully. However with that change the serialization seems busted still -- it's only serializing 33 bytes which makes me suspect the variant type isn't getting serialized out.

**Comment by larryk85** [comment]
This is a shortcoming of Boost::PFR, until a suitable replacement is added add the macro `EOSLIB_SERIALIZE( keytable, (keyid)(salt)(pub) )` to your table definition.

**Comment by yyh1102** [comment]
Add `EOSLIB_SERIALIZE` makes build a little slow and not pretty. When to fix this?

**Comment by tbfleming** [comment]
Our internal testing shows the opposite: using the macro speeds up builds.

**Comment by spoonincode** [comment]
Closure reason? WONTFIX?

**Comment by tbfleming** [comment]
PFR's approach may not be fixable since it relies on `auto& [x1, x2, x3, ..., xn] = blah` syntax to do its magic.

**Comment by jeffreyssmith2nd** [comment]
Since we have the `EOSLIB_SERIALIZE` short term workaround, and long term plan to hopefully remove PFR, I was looking at it as basically a wontfix.

**Comment by jeffreyssmith2nd** [comment]
So out of curiosity, I tested this with my llvm9 changes that included a change to PFR. The contract successfully compiles and the size of a row (using the datastream<size_t> overload) is 74. Which I think is the expected size? 8 (`uint64_t`) + 32 (`checksum256`) + 1 (variant) + 33 (`ecc_public_key`)

**Comment by tbfleming** [comment]
Nice!
