### ISSUE TITLE
eosio-abigen can not compatible with target_include_directories of cmake

### ISSUE THREAD

**Issue by cz-it** [EOSIO/eosio.cdt#78]
my work directory is:
tree .
.
|---- main.cpp
|----main.hpp
├── game
│   ├── common.hpp
│   ├── game.cpp
│   ├── game.hpp
└── table
  |     ├── gameinfo.hpp

and CMakeList:
set(CMAKE_CXX_FLAGS " -abigen ${CMAKE_CXX_FLAGS} ")

add_executable( minoritygame.wasm
        ${CMAKE_SOURCE_DIR}/game/game.cpp
        ${CMAKE_SOURCE_DIR}/main.cpp )
target_include_directories( game.wasm  PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/ )

cause my "target_include_directories" is "PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/ " .so in game.cpp ,I use : 

#include "table/gameinfo.hpp"

when "make" the wasm will be generated successfully . but the abi file will cuase : 

game.cpp:4:10: fatal error: 'game/game.hpp' file not found
#include "game/game.hpp"

if I use "#include gameinfo.hpp" and add table to target_include_directories .it cause the same error.

so . I guess eosio-abigen  dose not support multi directory or nested directory

**Comment by larryk85** [comment]
resolved by #88
