### ISSUE TITLE
How Ricardian statements should be loaded into ABI file

### ISSUE THREAD

**Issue by santteegt** [EOSIO/eosio.cdt#79]
Hello,

When running `eosio-cpp hello.cpp -o hello.wasm -abigen` or `eosio-abigen hello.cpp --output=hello.abi` the Ricardian contract statements are not being imported into the ABI file. I checked your last release, and it mentions the `ricardeos.py` script but it accepts a separate clause-*-rc.md for each statement, which looks a little inefficient. How do we have to define the rc.md files now ? It also looks that the rc.md file names that belong to the hello smart contract in the examples folder should be updated to be recognized by the python script

Regards

**Comment by lucca65** [comment]
Yeah, I'm having the exact same issue. no flag or option on `eosio-cpp` to import the `_rc.md` files into the ABI.

How should we proceed?

**Comment by larryk85** [comment]
Added support in v1.4.0.  Read the readme for more information on how to get `eosio-cpp` to import your ricardian contracts and clauses.
