### ISSUE TITLE
Unable to use eosiolib with only C / without C++?

### ISSUE THREAD

**Issue by liamcurry** [EOSIO/eosio.cdt#80]
Is it possible to use `eosiolib` without C++? I would expect that the items listed under the [C API reference](https://developers.eos.io/eosio-cpp/reference) would be usable with only C, but I'm running into compiler errors when I target `c11`. I have been finding these errors while generating bindings for Rust.

It seems like C compilers are unable to parse `[[noreturn]]` on this line:

https://github.com/EOSIO/eosio.cdt/blob/c692723166bcc2d21b16f798b06b9c7b4abd8188/libraries/eosiolib/system.h#L71

The memory functions here are listed under the "C API" section but are only accessible with C++:

https://github.com/EOSIO/eosio.cdt/blob/c692723166bcc2d21b16f798b06b9c7b4abd8188/libraries/eosiolib/memory.hpp#L26

**Comment by larryk85** [comment]
Currently no.  In a future release we will have better support for true C only.
