### ISSUE TITLE
abigen should block C data type "array" 

### ISSUE THREAD

**Issue by allenhan2** [EOSIO/eosio.cdt#802]
abigen generates:
                {
                    "name": "cat_list",
                    "type": "[10]"
                }

source code :

#include <eosio/eosio.hpp>

using namespace eosio;

class [[eosio::contract("arrayerr")]] arrayerr : public eosio::contract {

public:
    static constexpr uint64_t MAX_CATEGORY_NUM = 10;
    arrayerr(name receiver, name code,  datastream<const char*> ds): contract(receiver, code, ds) {}

    [[eosio::action]]
    void printacct(name user) {
        require_auth(user);
        acct_index accts(get_self(), get_first_receiver().value);

        auto itr = accts.find(user.value);
        if( itr != accts.end() )
        {
            print("account:[", user, "], ");
            for(const auto& c : itr->cat_list)
            {
                print("category:[", c.cat_name);
                print("], id:[", c.cat_id, "]");
            }
        } else{
            print("Error: not exist account:", user);
        }
    }
private:
    struct category {
        std::string cat_name;
        uint64_t cat_id;
        category() = default;
    };
    struct [[eosio::table]] acct {
        name key;
        category cat_list[MAX_CATEGORY_NUM];
        uint64_t primary_key() const { return key.value; }
    };
    uint64_t cat_num = 0;
    typedef eosio::multi_index<"account"_n, acct> acct_index;
};

**Comment by taokayan** [comment]
please use std::vector<category> instead.

**Comment by jeffreyssmith2nd** [comment]
Duplicates #457
