### ISSUE TITLE
EOSIO Tester does not work with eosio/transaction

### ISSUE THREAD

**Issue by jafri** [EOSIO/eosio.cdt#811]
It looks like EOSIO Tester does not work when your contract imports 
```#include <eosio/transaction.hpp>```

conflicting types for 'is_feature_activated’, 'send_deferred' and ‘cancel_deferred'

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
