### ISSUE TITLE
minor style issues on class eosio::block_timestamp page

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.cdt#815]
minor style issues on class eosio::block_timestamp page. From file :libraries/eosiolib/core/eosio/time.hpp

**Comment by iamveritas** [comment]
@dixia can you pls add more details, what has to be fixed here?

**Comment by iamveritas** [comment]
doc page in question: https://developers.eos.io/manuals/eosio.cdt/v1.6/classeosio_1_1block__timestamp/#class-eosioblock_timestamp

**Comment by dixia** [comment]
there is a " and and ". should able to find if you search that on the page

**Comment by iamveritas** [comment]
pages where this occurs:
https://developers.eos.io/manuals/eosio.cdt/latest/classeosio_1_1block__timestamp#detailed-description
https://developers.eos.io/manuals/eosio.cdt/v1.6/namespaceeosio_1_1__datastream__detail#detailed-description
https://developers.eos.io/manuals/eosio.cdt/v1.5/classeosio_1_1block__timestamp#detailed-description
https://developers.eos.io/manuals/eosio.cdt/v1.4/classeosio_1_1block__timestamp/#detailed-description
