### ISSUE TITLE
memory corruption under 32 bytes alignment memory allocation

### ISSUE THREAD

**Issue by learnforpractice** [EOSIO/eosio.cdt#837]
The following code will corrupt the  allocated memory.

```c++
#include <stdint.h>
#include <eosio/system.hpp>
#include <eosio/print.hpp>

using namespace eosio;

//32 bytes aligned struct
struct alignas(32) A {
};
extern "C" void apply(uint64_t receiver, uint64_t code, uint64_t action) {
    int align = 32;
    int32_t *memory_corruption_test;

    //make sure code will not return at the line of 
    //https://github.com/EOSIO/musl/blob/1fe3e67a0f98abac43f1a613fd294d0e2808476d/src/malloc/memalign.c#L35
    while (true) {
        memory_corruption_test = (int32_t*)malloc(sizeof(int32_t)*2);
        void *mem = (char *)memory_corruption_test+8;//next malloc return address
        void *new_mem = (void *)((uintptr_t)mem + align-1 & -align);
        if (new_mem != mem) {
            break;
        }
    }

    memory_corruption_test[1] = 1;

    //new operator will call function __memalign in src/malloc/memalign.c
    //__memalign will corrupt the memory at memory_corruption_test[1]
    new A();
    check(memory_corruption_test[1] == 1, "oops! memory corrupted\n");
}
```
Problem originate from
https://github.com/EOSIO/musl/blob/1fe3e67a0f98abac43f1a613fd294d0e2808476d/src/malloc/memalign.c#L48

eosio simple malloc is not compatible with musl malloc,  code in src/malloc/memalign.c will lead to a memory corruption under the situation of allocating a 32 bytes aligned memory.

**Comment by larryk85** [comment]
Thanks for bringing this up.  As the type is an `over-aligned` type, it falls firmly in the undefined/implementation defined region of new/delete/malloc/free.  As such, it will lower on the priority list of things to do.  

If you are using this for a specific reason, can you let me know what that is?

**Comment by learnforpractice** [comment]
I encontered this problem when I was porting evmone to eosio.

https://github.com/ethereum/evmone/blob/578ce076062f9942be296c66f2fd620ff75b417a/lib/evmone/execution_state.hpp#L33

If eosio.sdk does not support 32 bytes alignment , the compiler should at least give developer a warning or throw an error.

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
