### ISSUE TITLE
CDT Build issues

### ISSUE THREAD

**Issue by nksanthosh** [EOSIO/eosio.cdt#839]
1. Warnings over Ricardian contracts are spamming the build, there should be a flag to disable this warning

2. Build times seem longer than expected, it seems to rebuild more than necessary

3. Warning about date.h including sstream which bloats wasm, we shouldn’t be bloating wasm just by including standard headers (unless we really need sstream). This may also be contributing heavily to build times

**Comment by jeffreyssmith2nd** [comment]
See #752 for discussion of 1.

2. On develop, I have not seen a noticeable change in build times. There will be one however once the tester stuff comes in, though that is to be expected.

3. Where are you seeing this? I don't think I've seen it on develop.

**Comment by tbfleming** [comment]
Note: these are about building contracts with CDT, especially when using CMake (2, 3).

**Comment by jeffreyssmith2nd** [comment]
All of these have been addressed.
