### ISSUE TITLE
Question: why empty binary_extension<T> serializes to T{}?

### ISSUE THREAD

**Issue by zxcat** [EOSIO/eosio.cdt#852]
Hi! Trying to understand the reason, why serializetion and deserialization of empty `binary_extension` are not compatible to each other.
When serialize empty binary extension, it writes to stream default value of a wrapped type: https://github.com/EOSIO/eosio.cdt/blob/a6b8d3fc289d46f4612588cdd7223a3d549238f6/libraries/eosiolib/core/eosio/binary_extension.hpp#L181-L185
But when deserialize, empty binary extension supported: https://github.com/EOSIO/eosio.cdt/blob/a6b8d3fc289d46f4612588cdd7223a3d549238f6/libraries/eosiolib/core/eosio/binary_extension.hpp#L197-L205

Are there problems to "write nothing" when serialize empty binary extension?
Or what benefits the current behaviour gives?

**Comment by swatanabe-b1** [comment]
If a class contains multiple binary_extensions, then it would cause an invalid format if there were holes.

**Comment by zxcat** [comment]
@swatanabe-b1, I see.
Thought binary extensions can only be skipped in order from the last to the first, and holes are not allowed.
Now it's clear. Thank you!
