### ISSUE TITLE
Allow `optional<bool>` as action parameter

### ISSUE THREAD

**Issue by DenisCarriere** [EOSIO/eosio.cdt#862]
Getting an error whenever I enter an `optional<bool>` however it does work for other EOSIO types such as `optional<name>`

This seems like a valid syntax in C++
https://www.boost.org/doc/libs/1_56_0/libs/optional/doc/html/boost_optional/tutorial/a_note_about_optional_bool_.html

## Code example

```c++
#include <eosio/eosio.hpp>
#include <optional>

using namespace eosio;
using namespace std;

class [[eosio::contract]] hello : public contract {
  public:
      using contract::contract;

      [[eosio::action]]
      void hi( optional<bool> option ) {
         if ( option == true ) print( "print me" );
      }
};
```

## ❌ error message

```bash
/var/folders/sc/k5bwq66j0g16dn721lwhvf540000gn/T//hello.cpp:32:15: error: use of undeclared identifier '_Bool'
std::optional<_Bool> arg1; ds >> arg1;
              ^
/var/folders/sc/k5bwq66j0g16dn721lwhvf540000gn/T//hello.cpp:32:22: error: C++ requires a type specifier for all
      declarations
std::optional<_Bool> arg1; ds >> arg1;
                     ^
2 errors generated.
```

## expected ABI

```json
{
    "name": "hi",
    "base": "",
    "fields": [
        {
            "name": "option",
            "type": "bool?"
        }
    ]
}
```

## Inline `optional<bool>` does work ✅ 

```c++
[[eosio::action]]
void hi( ) {
  optional<bool> option = true;
  if ( option == true ) print( "print me" );
}
```

**Comment by jeffreyssmith2nd** [comment]
Which version of CDT are you using? This compiles successfully for me on a build off of develop.

**Comment by DenisCarriere** [comment]
@jeffreyssmith2nd I'm using `eosio-cpp version 1.7.0`

I haven't tried compiling with the develop branch, if that's the case, then this issue should be fixed at the next CDT release 👍

**Comment by jeffreyssmith2nd** [comment]
Interestingly it worked for me on `master` too, which should be reflective of 1.7. Are you using a brew package?

**Comment by DenisCarriere** [comment]
@jeffreyssmith2nd strange that 1.7 works for you

I'm on MacOS Catalina, pretty sure that doesn't have any impact.

Are you attempting to compile?

```c++
#include <eosio/eosio.hpp>
#include <optional>

using namespace eosio;
using namespace std;

class [[eosio::contract]] hello : public contract {
  public:
      using contract::contract;

      [[eosio::action]]
      void hi( optional<bool> option ) {
         if ( option == true ) print( "print me" );
      }
};
```

Still getting an error with `eosio-cpp version 1.7.0`

```
$ eosio-cpp hello.cpp -o hello.wasm
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <hi> does not have a ricardian contract
/var/folders/sc/k5bwq66j0g16dn721lwhvf540000gn/T//hello.cpp:31:15: error: use of undeclared identifier '_Bool'
std::optional<_Bool> arg0; ds >> arg0;
              ^
/var/folders/sc/k5bwq66j0g16dn721lwhvf540000gn/T//hello.cpp:31:22: error: C++ requires a type specifier for all declarations
std::optional<_Bool> arg0; ds >> arg0;
                     ^
2 errors generated.
/usr/local/Cellar/eosio.cdt/1.7.0/opt/eosio.cdt/bin/wasm-ld: error: cannot open /var/folders/sc/k5bwq66j0g16dn721lwhvf540000gn/T//hello.cpp.o: No such file or directory
```

**Comment by jeffreyssmith2nd** [comment]
Just spun up a brand new Catalina VM and installed 1.7 via brew and that compiled fine.

Can you try uninstalling CDT, running `eosio-cpp` (it should fail, if not then maybe you've got conflicting installs somehow) and reinstalling CDT?

**Comment by DenisCarriere** [comment]
Tried reinstalling & installing CDT on MacOS, still getting the same error.

I also installed the latest CDT 1.7.0 on Debian "GNU/Linux 10 (buster)" and getting similar error:

https://github.com/eosio/eosio.cdt#debian-package-install

```bash
$ cat /etc/debian_version
10.3

$ eosio-cpp --version
eosio-cpp version 1.7.0

$ eosio-cpp hello.cpp -o hello.wasm
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <hi> does not have a ricardian contract
/tmp/hello.cpp:31:15: error: use of undeclared identifier '_Bool'
std::optional<_Bool> arg0; ds >> arg0;
              ^
/tmp/hello.cpp:31:22: error: C++ requires a type specifier for all declarations
std::optional<_Bool> arg0; ds >> arg0;
                     ^
2 errors generated.
/usr/opt/eosio.cdt/1.7.0/bin/wasm-ld: error: cannot open /tmp/hello.cpp.o: No such file or directory
```

**Comment by smlu** [comment]
@jeffreyssmith2nd I get similar error on the latest `develop` branch (Ubuntu 20.04).
If I move defintion to cpp source file I get following error:
`eosio-cpp: eosio.cdt/eosio_llvm/tools/clang/include/clang/AST/DeclCXX.h:672: struct DefinitionData &clang::CXXRecordDecl::data() const: Assertion DD && "queried property of class with no definition"' failed.`

I've also tried using different template type (`std::optional<std::vector<uint8_t>>`)  and it failed with the same error.

**Comment by jeffreyssmith2nd** [comment]
I wasn't originally able to reproduce this, but now I can. We'll reopen this for investigation.

**Comment by DenisCarriere** [comment]
Great thank 👍 glad you are able to reproduce

**Comment by jeffreyssmith2nd** [comment]
This should be fixed in develop now

**Comment by DenisCarriere** [comment]
👍  great thanks for the fix @jeffreyssmith2nd
