### ISSUE TITLE
branch: eosio-cdt-2.1-staging-b - EOSIO_DISPATCH_INTERNAL

### ISSUE THREAD

**Issue by kryton** [EOSIO/eosio.cdt#868]
macro EOSIO_DISPATCH_INTERNAL assumes 'executed' is defined.
it is called from EOSIO_DISPATCH_HELPER

```

extern "C" {
    void apply (uint64_t receiver, uint64_t code, uint64_t action ) {
        auto self = receiver;

        if ( code == self ) {

            switch( action ) {
                EOSIO_DISPATCH_HELPER( dgoods, (setconfig)(create)(issue)(burnnft)(burnft)(transfernft)(transferft)(listsalenft)(closesalenft)(logcall)(freezemaxsup) )
            }
        }

        else {
            if ( code == name("eosio.token").value && action == name("transfer").value ) {
                execute_action( name(receiver), name(code), &dgoods::buynft );
            }
        }
    }
}

```

**Comment by b1aafulei** [comment]
This is related to some recent code changes, in particular, the commit [Update Macro based Dispatcher](https://github.com/EOSIO/eosio.cdt/commit/f1ee46fb0c660694093c25c7735c4e95391a0e0a) by Dan.

My observation on the current `branch: eosio-cdt-2.1-staging-b` is that the new changes will cause problems to `EOSIO_DISPATCH`.

First of all, there are two calling paths:

```
Path 1: EOSIO_ACTIONS --> EOSIO_DISPATCH_HELPER --> EOSIO_DISPATCH_INTERNAL
Path 2: EOSIO_DISPATCH --> EOSIO_DISPATCH_HELPER --> EOSIO_DISPATCH_INTERNAL
```

Now a new boolean variable `executed` is defined in `EOSIO_ACTIONS`, and `EOSIO_DISPATCH_INTERNAL` will use it, assuming its existence. If it cannot see the variable, it will complain.

If we follow path 1 and everything should be fine, and we can argue that `EOSIO_DISPATCH_HELPER` is for internal usage and it shouldn't be called directly by a contract writer.

However, if we follow path 2 and start with `EOSIO_DISPATCH` (this macro is extensively used in many contracts), it seems that `executed` still cannot be seen.

**Comment by b1aafulei** [comment]
I made a pull request #870 for a quick fix for the above problem that I mentioned. It is still suggested that a contract writer not call any helper macro like `EOSIO_DISPATCH_HELPER`. But at minimum `executed` should be in scope if the entry point is `EOSIO_DISPATCH`.

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
