### ISSUE TITLE
Clang upgrade

### ISSUE THREAD

**Issue by rachit2501** [EOSIO/eosio.cdt#879]
I was trying to install eosio.cdt. When I  tried to run `./build.sh` , the following error got thrown:
```
Package clang-4.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'clang-4.0' has no installation candidate
E: Unable to locate package lldb-4.0
E: Couldn't find any package by glob 'lldb-4.0'
E: Couldn't find any package by regex 'lldb-4.0'
E: Unable to locate package libclang-4.0-dev
E: Couldn't find any package by glob 'libclang-4.0-dev'
E: Couldn't find any package by regex 'libclang-4.0-dev'

```

It appears that the issue is with the version of clang. I am easily able to download clang-6.0. The issue arrives on installing clang-4.0. Upgrading this underlying dependency should be done, cause the old version might have trouble with the newer version of Ubuntu and other distros.

**Comment by tbfleming** [comment]
As of 1.7 (possibly earlier), build scripts aren't supported. Some are obsolete and are being removed. Others are part of the cicd system and don't run well outside it. See the build instructions in the readme.

**Comment by rachit2501** [comment]
Okay. I also followed installation instructions for ubuntu 18 but it also doesn't; seems to work with ubuntu 20 there are several dependencies issues. Working with containers is currently the only solution to this problem on ubuntu 20. Since this new release is LTS, so rolling a version for that is requested.

**Comment by sanaraufx** [comment]
Support for Ubuntu 20.04 is now supported
