### ISSUE TITLE
[docs] show explicitly which header file is required 

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.cdt#890]
would be useful to show explicitly which header file is required from pages like this:

https://developers.eos.io/manuals/eosio.cdt/latest/group__system/#detailed-description

**Comment by iamveritas** [comment]
given the current way of generating the “Modules” section we can not pull the header file name for each of those items and subitems listed under modules without a level of effort which is not counterweighting the benefits.
we do have the header file info for generated reference documentation though.
