### ISSUE TITLE
Easier copy & paste for install command in README.md

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eosio.cdt#902]
This is very minor issue, but in `README.md` in root directory, unlike the example of MacOS install command, the examples of Linux install command includes `$` symbol at the first of every line.

```
brew tap eosio/eosio.cdt
brew install eosio.cdt
```

```
$ wget https://github.com/eosio/eosio.cdt/releases/download/v1.7.0/eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb
$ sudo apt install ./eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb
```

Can you remove these `$` for copy & paste multiple line of commands at a time?

**Comment by iamveritas** [comment]
fixed by https://github.com/EOSIO/eosio.cdt/commit/3899c3a4c0979ccb71dd67ca4b21a953bb40efc7
