### ISSUE TITLE
eosio.cdt/libraries/eosiolib/types.h:72:8: error: redefinition of 'public_key'

### ISSUE THREAD

**Issue by lzqjfly** [EOSIO/eosio.cdt#93]
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/libc/musl/include/stdlib.h:11:9: warning: 
      'NULL' macro redefined [-Wmacro-redefined]
#define NULL 0L

/Users/Sanxiao/eosiocdt/eosio.cdt/build/EosioClang-prefix/src/EosioClang-build/lib/clang/7.0.0/include/stddef.h:      100:13: note: 
      previous definition is here
#define NULL __null

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:72:8: error: 
      redefinition of 'public_key'
struct public_key {

/usr/local/include/eosiolib/types.h:34:8: note: previous definition is here
struct public_key {

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:80:8: error: 
      redefinition of 'signature'
struct signature {

/usr/local/include/eosiolib/types.h:38:8: note: previous definition is here
struct signature {

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:88:16: error: 
      redefinition of 'checksum256'
struct ALIGNED(checksum256) {

/usr/local/include/eosiolib/types.h:42:16: note: previous definition is here
struct ALIGNED(checksum256) {

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:96:16: error: 
      redefinition of 'checksum160'
struct ALIGNED(checksum160) {

/usr/local/include/eosiolib/types.h:46:16: note: previous definition is here
struct ALIGNED(checksum160) {

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:104:16: error: 
      redefinition of 'checksum512'
struct ALIGNED(checksum512) {

/usr/local/include/eosiolib/types.h:50:16: note: previous definition is here
struct ALIGNED(checksum512) {

In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/privileged.hpp:4:
/Users/Sanxiao/eosiocdt/eosio.cdt/libraries/eosiolib/types.h:115:8: error: 
      redefinition of 'account_permission'
struct account_permission {

/usr/local/include/eosiolib/types.h:57:8: note: previous definition is here
struct account_permission {

1 warning and 6 errors generated.
make[2]: *** [libraries/eosiolib/CMakeFiles/eosio.dir/eosiolib.cpp.o] Error 255
make[1]: *** [libraries/eosiolib/CMakeFiles/eosio.dir/all] Error 2
make: *** [all] Error 2

**Comment by Gui-Jun** [comment]
I have the same bug.
Please let me know the solution.

**Comment by larryk85** [comment]
You have eosiolib installed in your /usr/local/include.  You will want to either move it to some other location so eosio-cpp doesn't try to include it or simply ```rm``` it.

**Comment by Gui-Jun** [comment]
> You have eosiolib installed in your /usr/local/include. You will want to either move it to some other location so eosio-cpp doesn't try to include it or simply `rm` it.

Thanks... Resolved it.
