### ISSUE TITLE
eosio-cpp not compiling contract

### ISSUE THREAD

**Issue by emperorjm** [EOSIO/eosio.cdt#98]
I am trying to compile the "eosio.token" contract with the following "**eosio-cpp -o eosio.token.wasm eosio.token.cpp --abigen**" but nothing is being generated within the terminal and the process won't complete.

A "**eosio.token.wasm**" and "**eosio.token.wasm.tmpefe1114**" are generated within the token folder. What could be causing this? If there are errors in the token contract the command shows the errors but otherwise it just shows the cursor blinking and will not complete.

I am using the latest version of CDT.

**Comment by emperorjm** [comment]
Thanks a lot. It now works.

**Comment by emperorjm** [comment]
It see

**Comment by emperorjm** [comment]
Had to use "**eosiocpp -o gosharetoken.wasm gosharetoken.cpp**" to generate the wasm. "**eosio-cpp**" is just not working out for me at all.

**Comment by xiongxinag** [comment]
Cpu core number is adjusted to 2 cores . And it will work
